<a href="https://colab.research.google.com/github/tougheye/Data_processing/blob/main/99_in_juris_list.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The project is to find whether any employee reported in Unit 99 appeared in the UPTE juris list

In [1]:
import pandas as pd

# Import the latest Unit 99 data
unit_99_data = pd.ExcelFile("/content/drive/MyDrive/Data/Unit_99_Title_Claim/Historical 99 Data/UPTE_99_as_of_6_3_2026.xlsx")
unit_99_data.sheet_names

['Sheet1']

In [21]:
unit_99_df = unit_99_data.parse("Sheet1")
unit_99_df.shape

(172900, 25)

In [22]:
unit_99_df.columns

Index(['Location/Business Unit', 'Employee Lived Name', 'Job Code',
       'Job Code Description', 'Most Recent Date of Hire in Empl Rcd',
       'Job Expected End Date', 'Employee Class', 'Employee Class Description',
       'FTE', 'Job Hourly Rate', 'Annual Salary', 'Department ID',
       'Department Description', 'Location Code', 'Location Code Description',
       'EE Work Location Address 1', 'EE Work Location Address 2',
       'EE Work Location Address 3', 'EE Work Location Floor',
       'EE Work Location City', 'EE Work Location State',
       'EE Work Location Zip Code', 'EE Work Email Address', 'EE Work Phone',
       'Employee Relation Description'],
      dtype='object')

In [9]:
# function to standardize the email addresses for matching

def standardize_email(df, column_name):
    df[column_name] = df[column_name].str.lower().str.strip()
    return df

In [3]:
# Import the latest juris_data

juris_data = pd.ExcelFile("/content/Combined_I254_DATA_HX_RX_TX_07062026.xlsx")
juris_data.sheet_names

['All Units', 'Transfers & Separations']

In [4]:
juris_df = juris_data.parse('All Units')
juris_df.shape

(23810, 58)

In [7]:
juris_df.columns

Index(['Type Change Code/ADC Update Code',
       'Type Change Description/Action Description', 'Employee (EE) ID',
       'Employee Name', 'Bargaining Unit', 'Location/Business Unit',
       'Job Indicator', 'Employment Record Number', 'Jobcode',
       'Job Title Abbr Name', 'General Deductions Dues Indicator',
       'Annual Pay Rate 1.0 FTE', 'Step', 'Appt. %', 'Employee Class',
       'Employee Class Description', 'Appt Rep Code',
       'Most Recent Date of Hire in Empl Record',
       'Earliest in Unit Begin Date for Empl Record', 'Job Expected End Date',
       'Department ID', 'Department ID Description', 'Home Address 1',
       'Home Address 2', 'Home City', 'Home State', 'Home Zip',
       'Home Address Disclosure Flag', 'Home Phone',
       'Home Phone Disclosure Flag', 'Personal Email Address',
       'Personal Email Address Disclosure Flag', 'Personal Cell Phone No.',
       'Personal Cell Phone No. Disclosure Flag', 'Location Description',
       'EE Work Location Building', 'EE Work Location Address1',
       'EE Work Location Address2', 'EE Work Location Room/Suite',
       'EE Work Location Floor', 'EE Work Location City',
       'EE Work Location State', 'EE Work Location Zip Code',
       'EE Work Location Cubicle', 'Account Number', 'Account Title',
       'EE Work Email Address', 'EE Work Phone', 'LOA Begin Date',
       'LOA Anticipated Return Date', 'Leave of Absence Type Action Code',
       'Leave of Absence Description/Action Code Translation', 'ERIT %',
       'ERIT Begin Date', 'ERIT End Date', 'Separation Date',
       'Separation Reason Code Description', 'Unit'],
      dtype='object')

In [12]:
cols_to_keep = ['Employee (EE) ID', 'Employee Name', 'Bargaining Unit',
                'Location/Business Unit','Job Title Abbr Name', 'General Deductions Dues Indicator',
       'Annual Pay Rate 1.0 FTE', 'Step', 'Appt. %', 'Employee Class',
       'Employee Class Description', 'Appt Rep Code','Most Recent Date of Hire in Empl Record',
       'Earliest in Unit Begin Date for Empl Record', 'Job Expected End Date',
       'Department ID', 'Department ID Description', 'Location Description',
       'EE Work Location Building', 'EE Work Location Address1', 'EE Work Email Address',
       'EE Work Location Address2', 'EE Work Location Room/Suite',
       'EE Work Location Floor', 'EE Work Location City','EE Work Location State', 'EE Work Location Zip Code']

In [24]:
# Save the updated juris data wit hselected column and standardized email addresses
juris_final_df = standardize_email(df=juris_df[cols_to_keep], column_name='EE Work Email Address')
juris_final_df.columns = [f"{col}_juris" if col != 'EE Work Email Address' else col for col in juris_final_df.columns ]
juris_final_df.head()

/tmp/ipykernel_2643/164842776.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].str.lower().str.strip()

,Employee (EE) ID_juris,Employee Name_juris,Bargaining Unit_juris,Location/Business Unit_juris,Job Title Abbr Name_juris,General Deductions Dues Indicator_juris,Annual Pay Rate 1.0 FTE_juris,Step_juris,Appt. %_juris,Employee Class_juris,...,Location Description_juris,EE Work Location Building_juris,EE Work Location Address1_juris,EE Work Email Address,EE Work Location Address2_juris,EE Work Location Room/Suite_juris,EE Work Location Floor_juris,EE Work Location City_juris,EE Work Location State_juris,EE Work Location Zip Code_juris
0,10002441,"Lagunas,Karla Flores",HX,LACMP,CLIN SOCIAL WORKER 3,D,140079.65,8.0,0.70,2,...,WW 300 Med Plaza/1200,Goldberg,300 Medical Plaza Drwy,klagunas@mednet.ucla.edu,NaN,Room 1200,1,Los Angeles,CA,90095
1,10004172,"Ealy,Laurel Christine",HX,MECMP,CNSLNG PSYCHOLOGIST 3 HX,D,154813.06,18.0,1.00,2,...,Staff: Remote-Out of State,S_OUTOFST,Out of State,leichler@ucmerced.edu,Staff: Remote-Out of State,NaN,NaN,NaN,NaN,00000
2,10006172,"Gifford,Allison Keller",HX,DVMED,CLIN LAB SCI SPEC,D,150732.72,4.0,1.00,2,...,Main Hospital,NaN,2315 Stockton Blvd,akgifford@ucdavis.edu,NaN,NaN,NaN,Sacramento,CA,95817
3,10007535,"Simon,Dominic Anthony",HX,LACMP,ATH TRAINER 1 HX,NaN,83311.20,0.0,0.10,4,...,John Wooden Center,NaN,221 Westwood Plaza,dsimon829@ucla.edu,Cultural & Recreational Affairs,2ND FLOOR,2,Los Angeles,CA,90095
4,10007535,"Simon,Dominic Anthony",HX,LACMP,ATH TRAINER 1 HX,NaN,98658.00,0.0,0.05,4,...,John Wooden Center,NaN,221 Westwood Plaza,dsimon829@ucla.edu,Cultural & Recreational Affairs,2ND FLOOR,2,Los Angeles,CA,90095

In [23]:
# standardize 99 email address

final_99_df = standardize_email(df=unit_99_df, column_name='EE Work Email Address')
final_99_df.columns = [f"{col}_99" if col != 'EE Work Email Address' else col for col in final_99_df.columns ]
final_99_df.head()

,Location/Business Unit_99,Employee Lived Name_99,Job Code_99,Job Code Description_99,Most Recent Date of Hire in Empl Rcd_99,Job Expected End Date_99,Employee Class_99,Employee Class Description_99,FTE_99,Job Hourly Rate_99,...,EE Work Location Address 1_99,EE Work Location Address 2_99,EE Work Location Address 3_99,EE Work Location Floor_99,EE Work Location City_99,EE Work Location State_99,EE Work Location Zip Code_99,EE Work Email Address,EE Work Phone_99,Employee Relation Description_99
0,ASLA1,"Chapman,Scott",007239,ANL 6,1995-12-18,NaT,2,Staff: Career,1.0,55.948276,...,308 Westwood Plaza,ACKERMAN,,,Los Angeles,CA,90095,schapman@asucla.ucla.edu,310/825-2827,"All Others, Not Confidential"
1,ASLA1,"Baskin,Jane",007234,ANL 1,2006-08-21,NaT,2,Staff: Career,1.0,30.982759,...,308 Westwood Plaza,ACKERMAN,,,Los Angeles,CA,90095,jbaskin@asucla.ucla.edu,310/206-0775,"All Others, Not Confidential"
2,ASLA1,"Krieger,Christian",007235,ANL 2,2021-08-12,NaT,2,Staff: Career,1.0,25.540230,...,308 Westwood Plaza,ACKERMAN,,,Los Angeles,CA,90095,ckrieger@asucla.ucla.edu,310/825-7410,"All Others, Not Confidential"
3,ASLA1,NaN,004921,STDT 2,2025-11-01,2026-10-31,5,Student: Casual/Restricted,0.1,17.900000,...,308 Westwood Plaza,ACKERMAN,,,Los Angeles,CA,90095,amandabaquir24@ucla.edu,Pending,"All Others, Not Confidential"
4,ASLA1,"Camacho Osuna,Jose",007234,ANL 1,2025-12-15,NaT,2,Staff: Career,1.0,26.340994,...,308 Westwood Plaza,ACKERMAN,,,Los Angeles,CA,90095,jcamacho@asucla.ucla.edu,310/206-0776,"All Others, Not Confidential"

In [26]:
juris_in_99_email_match = juris_final_df.merge(final_99_df, how='inner', on='EE Work Email Address')

In [27]:
juris_in_99_email_match.to_excel("June_99_in_juris_email_match.xlsx")