<a href="https://colab.research.google.com/github/tougheye/Data_processing/blob/main/99_list_process.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Upload Job Codes Summary file

In [1]:
import pandas as pd

mar_2026_job_code_review_all = pd.read_excel("/content/drive/MyDrive/Data/UCOP_Job_Codes_Summary/UPTE-26-015_Job Summary Report_3.20.26.xlsx", sheet_name="Job Code Review")

# mar_2026_job_code_review_all.head()

,Salary Plan SETID,Jobcode SETID,Job Code,Eff Date,Salary Grade Eff Status,Descr,Short Descr,Job Function,Sal Admin Plan,Grade,...,Last Update,Last Updated by,Last Updated Date Time,Key Job Code,CTO/OS Subgroup,Sys/Local Ind,OnCall Eligible,Elig Shift Diff,Classified,OSHPD Code
0,ASLA1,UCSHR,000245,1901-01-01,A,DIR,DIR,312,PE,K07,...,2014-07-16,UC_JPARK,2015-10-06 13:57:11.999,N,M10,L,N,N,2,00
1,ASLA1,UCSHR,000245,1901-01-01,A,DIR,DIR,312,PE,K05,...,2014-07-16,UC_JPARK,2015-10-06 13:57:11.999,N,M10,L,N,N,2,00
2,ASLA1,UCSHR,000245,1901-01-01,A,DIR,DIR,312,PE,K02,...,2014-07-16,UC_JPARK,2015-10-06 13:57:11.999,N,M10,L,N,N,2,00
3,ASLA1,UCSHR,000245,1901-01-01,A,DIR,DIR,312,PE,K04,...,2014-07-16,UC_JPARK,2015-10-06 13:57:11.999,N,M10,L,N,N,2,00
4,ASLA1,UCSHR,000245,1901-01-01,A,DIR,DIR,312,PE,K03,...,2014-07-16,UC_JPARK,2015-10-06 13:57:11.999,N,M10,L,N,N,2,00

In [2]:
mar_2026_job_code_review_all.shape

(46081, 48)

UPload the Pivot summary of the 99 list to bring in the fields from Job Codes Summary. Then filter the titles that are in the CTOs where UPTE has representation

In [3]:
head_cnt_all_99_df = pd.read_excel("/content/Apr_2026_99_list_summary.xlsx", sheet_name="All_Non-LBNL_99_title_cnts")
head_cnt_all_99_df.head()

,Job Title,UPTE Unit for CTO,Current Status UPTE / UAW Titles in 99,Grand Total,Total All Others (Confirmed target),"All Others, Confidential","All Others, Not Confidential",Excluded from Coverage,"Manager, Confidential","Manager, Not Confidential",Not Applicable - Contingent Wk,Not Covered HEERA (Out of Stat,"Stud Academic Title, No HEERA","Supervisor, Confidential","Supervisor, Not Confidential","Supervisor, Represented"
0,ABSOLUTE RETURNS INV DIR,NaN,NaN,2,1,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ABSOLUTE RETURNS INV MGR 3,NaN,NaN,2,0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
2,ACAD ACHIEVEMENT CNSLR 3,NaN,SSAP,4,3,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
3,ACAD ACHIEVEMENT CNSLR 4,NaN,SSAP,18,1,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.0,NaN
4,ACAD ACHIEVEMENT CNSLR 5,NaN,SSAP,11,3,NaN,3.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,7.0,NaN

In [4]:
head_cnt_all_99_df.shape

(1973, 16)

Upload the UPTE CTO classes

In [7]:
upte_classes = pd.read_excel("/content/Apr_2026_99_list_summary.xlsx", sheet_name="UPTE_classes")
upte_classes

,CTO/OS Subgroup,CTO/OS Subgroup Name,UPTE Total title Cnt,UPTE Classes,Total Title ATB,% Total title UPTE,0.99,99 Title Cnts,9C,9F,...,UF,UH,UL,WC,WE,WH,WK,WN,WS,WT
0,A10,RECREATIONAL SERVICES & ATHLETICS,2,HX/TX,17,0.117647,83.33%,15,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
1,A15,EXTERNAL AFFAIRS,1,TX,33,0.030303,80.56%,29,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,B15,CLERICAL/ADMIN,1,TX,110,0.009091,37.07%,43,14.66,0.86,...,0.00,0.00,0.00,7.76,2.59,0.00,0.00,0.00,0.00,0.00
3,C10,FOOD SERVICES,1,HX,10,0.100000,41.67%,5,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,8.33,0.00,0.00,8.33,0.00
4,D10,COMMUNICATION,12,TX,33,0.363636,58.82%,20,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
5,D15,ARTS,16,TX,29,0.551724,46.88%,15,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,3.12
6,E10,ARCHITECTURE & PLANNING,10,RX/TX,30,0.333333,69.7%,23,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
7,E20,ENGINEERING,7,TX,24,0.291667,69.23%,18,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
8,F10,INFORMATION TECHNOLOGY SERVICES,17,TX,81,0.209877,69.47%,66,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,1.05,0.00,0.00,0.00,0.00
9,F20,ADMINISTRATIVE SUPPORT & ANALYSIS,2,TX/HX,85,0.023529,81%,81,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
10,G15,FACILITIES,3,TX,178,0.016854,11.7%,22,0.00,1.06,...,0.00,0.00,0.00,0.00,0.00,0.00,0.53,0.00,0.53,0.00
11,G45,MARINE TRADES,3,TX,26,0.115385,21.43%,6,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
12,H15,MEDICAL TECHNICIANS,1,TX,97,0.010309,12.5%,13,0.00,12.50,...,0.00,0.00,0.00,0.00,6.73,0.00,0.00,0.00,0.00,0.00
13,H20,MEDICAL TECHNOLOGISTS,4,TX,140,0.028571,20.39%,31,0.00,5.92,...,1.32,0.00,0.00,0.00,7.89,1.97,0.00,0.00,0.00,0.00
14,H35,NURSING SERVICES,5,HX,138,0.036232,21.92%,32,0.00,0.68,...,0.00,1.37,0.68,0.00,1.37,2.74,0.00,8.22,0.00,0.00
15,H40,"ALL PHYSICIANS & DENTISTS, INCLUDING PHYSICIAN...",2,HX,22,0.090909,75%,18,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
16,H45,MEDICAL ADMINISTRATION AND AUX SERVICES,5,HX,140,0.035714,31.21%,49,0.00,28.66,...,0.00,0.00,0.00,0.64,2.55,0.00,0.00,0.00,0.00,0.00
17,H50,PHARMACISTS,3,HX,22,0.136364,41.67%,10,0.00,0.00,...,0.00,0.00,0.00,0.00,4.17,4.17,0.00,0.00,0.00,0.00
18,H65,COUNSELING & SOCIAL SERVICES,18,HX,38,0.473684,37.04%,20,0.00,0.00,...,0.00,0.00,0.00,1.85,0.00,3.70,0.00,0.00,0.00,0.00
19,H80,THERAPEUTIC SERVICES,15,HX,40,0.375000,19.61%,10,0.00,0.00,...,0.00,0.00,0.00,0.00,3.92,3.92,0.00,0.00,0.00,0.00
20,H85,OPTOMETRISTS,1,HX,2,0.500000,66.67%,2,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
21,I10,ANIMAL CARE SERVICES - TECHNICIANS,4,TX,5,0.800000,16.67%,1,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
22,I20,LABORATORY AND RESEARCH SUPPORT,19,RX/TX,37,0.513514,37.21%,16,0.00,0.00,...,0.00,0.00,0.00,0.00,2.33,0.00,0.00,0.00,0.00,0.00
23,I25,MUSEUM AND LIBRARY SERVICES,5,RX/TX,10,0.500000,41.67%,5,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
24,LBL,LBNL,61,TX/RX,1223,0.049877,57.15%,699,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [33]:
upte_cto_subgroups = upte_classes['CTO/OS Subgroup'].values

In [31]:
upte_cto_subgroups

array(['RECREATIONAL SERVICES & ATHLETICS', 'EXTERNAL AFFAIRS',
       'CLERICAL/ADMIN', 'FOOD SERVICES', 'COMMUNICATION', 'ARTS',
       'ARCHITECTURE & PLANNING', 'ENGINEERING',
       'INFORMATION TECHNOLOGY SERVICES',
       'ADMINISTRATIVE SUPPORT & ANALYSIS', 'FACILITIES', 'MARINE TRADES',
       'MEDICAL TECHNICIANS', 'MEDICAL TECHNOLOGISTS', 'NURSING SERVICES',
       'ALL PHYSICIANS & DENTISTS, INCLUDING PHYSICIANS AS',
       'MEDICAL ADMINISTRATION AND AUX SERVICES', 'PHARMACISTS',
       'COUNSELING & SOCIAL SERVICES', 'THERAPEUTIC SERVICES',
       'OPTOMETRISTS', 'ANIMAL CARE SERVICES - TECHNICIANS',
       'LABORATORY AND RESEARCH SUPPORT', 'MUSEUM AND LIBRARY SERVICES',
       'LBNL'], dtype=object)

Separate Out Columns to keep from Job Code Review tab to join them on the 99 summary table

In [13]:
job_code_review_cols_keep = ['Job Code', 'Descr', 'Short Descr', 'Union Code', 'FLSA Status']

Bring in the Census/OCC Code Description, EEO1 Reporting Cod Description, 'CTO/OS Subgroup', and CTO Description columns from Non-Represented Job Codes tab

In [10]:
non_repr_job_codes = pd.read_excel("/content/drive/MyDrive/Data/UCOP_Job_Codes_Summary/UPTE-26-015_Job Summary Report_3.20.26.xlsx", sheet_name="Non-Represented Job Codes")
non_repr_job_codes.head()

,Salary Plan SETID,Status - Job Code,Job Code,Job Code Description,Eff Date - Salary Grade,Salary Grade Eff Status,Union Code,FLSA Status,Personnel Program/CLASS_INDC,Elig Shift Diff,...,Max/Annual,CTO/OS Subgroup,CTO Description,SOC Code,SOC Code Description,Census/OCC Code,Census/OCC Code Description,EEO1 Reporting Code,EEO1 Reporting Cod Description,OSHPD Code
0,ASLA1,A,000245,DIR,2019-11-01,A,99,E,2,N,...,143550.00,M10,MANAGERS,11-1021,00,0020,General And Operations Managers,B,First/Mid Level Officials,00
1,ASLA1,A,000245,DIR,2019-11-01,A,99,E,2,N,...,158604.48,M10,MANAGERS,11-1021,00,0020,General And Operations Managers,B,First/Mid Level Officials,00
2,ASLA1,A,000245,DIR,2019-11-01,A,99,E,2,N,...,174661.20,M10,MANAGERS,11-1021,00,0020,General And Operations Managers,B,First/Mid Level Officials,00
3,ASLA1,A,000245,DIR,2019-11-01,A,99,E,2,N,...,192743.28,M10,MANAGERS,11-1021,00,0020,General And Operations Managers,B,First/Mid Level Officials,00
4,ASLA1,A,000245,DIR,2019-11-01,A,99,E,2,N,...,217841.04,M10,MANAGERS,11-1021,00,0020,General And Operations Managers,B,First/Mid Level Officials,00

In [11]:
non_repr_job_codes.shape

(22059, 33)

In [16]:
non_repr_job_code_cols_keep = ['Job Code Description', 'CTO/OS Subgroup',
       'CTO Description', 'EEO1 Reporting Cod Description', 'Census/OCC Code']

merge FLSA, short descriptions and job codes to the 99 summary

In [23]:
head_cnt_all_99_w_jc_review = head_cnt_all_99_df.merge(mar_2026_job_code_review_all[job_code_review_cols_keep], left_on='Job Title', right_on='Descr', how='left').drop_duplicates(subset='Job Title')

In [26]:
head_cnt_all_99_w_jc_review.columns

Index(['Job Title', 'UPTE Unit for CTO',
       'Current Status UPTE / UAW Titles in 99', 'Grand Total',
       'Total All Others (Confirmed target)', 'All Others, Confidential',
       'All Others, Not Confidential', 'Excluded from Coverage',
       'Manager, Confidential', 'Manager, Not Confidential',
       'Not Applicable - Contingent Wk', 'Not Covered HEERA (Out of Stat',
       'Stud Academic Title, No HEERA', 'Supervisor, Confidential',
       'Supervisor, Not Confidential', 'Supervisor, Represented', 'Job Code',
       'Descr', 'Short Descr', 'Union Code', 'FLSA Status'],
      dtype='object')

In [28]:
head_cnt_all_99_w_non_rep_jc = head_cnt_all_99_w_jc_review.merge(non_repr_job_codes[non_repr_job_code_cols_keep], left_on='Job Title', right_on='Job Code Description', how='left').drop_duplicates(subset='Job Title')

In [30]:
head_cnt_all_99_w_non_rep_jc.columns

Index(['Job Title', 'UPTE Unit for CTO',
       'Current Status UPTE / UAW Titles in 99', 'Grand Total',
       'Total All Others (Confirmed target)', 'All Others, Confidential',
       'All Others, Not Confidential', 'Excluded from Coverage',
       'Manager, Confidential', 'Manager, Not Confidential',
       'Not Applicable - Contingent Wk', 'Not Covered HEERA (Out of Stat',
       'Stud Academic Title, No HEERA', 'Supervisor, Confidential',
       'Supervisor, Not Confidential', 'Supervisor, Represented', 'Job Code',
       'Descr', 'Short Descr', 'Union Code', 'FLSA Status',
       'Job Code Description', 'CTO/OS Subgroup', 'CTO Description',
       'EEO1 Reporting Cod Description', 'Census/OCC Code'],
      dtype='object')

In [37]:
head_cnt_all_99_w_non_rep_jc.columns

Index(['Job Title', 'UPTE Unit for CTO',
       'Current Status UPTE / UAW Titles in 99', 'Grand Total',
       'Total All Others (Confirmed target)', 'All Others, Confidential',
       'All Others, Not Confidential', 'Excluded from Coverage',
       'Manager, Confidential', 'Manager, Not Confidential',
       'Not Applicable - Contingent Wk', 'Not Covered HEERA (Out of Stat',
       'Stud Academic Title, No HEERA', 'Supervisor, Confidential',
       'Supervisor, Not Confidential', 'Supervisor, Represented', 'Job Code',
       'Short Descr', 'Union Code', 'FLSA Status', 'CTO/OS Subgroup',
       'CTO Description', 'EEO1 Reporting Cod Description', 'Census/OCC Code'],
      dtype='object')

Drop the duplicated Job code Description and Descr columns that are the same column as Job Title

In [36]:
head_cnt_all_99_w_non_rep_jc.drop(columns=['Job Code Description', 'Descr'], inplace=True)

In [39]:
final_non_lbnl_titles = head_cnt_all_99_w_non_rep_jc[head_cnt_all_99_w_non_rep_jc['CTO/OS Subgroup'].isin(upte_cto_subgroups)]

In [42]:
column_df_list = final_non_lbnl_titles.columns

In [43]:
column_order = ['Job Code','Job Title', 'Short Descr', 'UPTE Unit for CTO',
       'Current Status UPTE / UAW Titles in 99', 'Union Code', 'FLSA Status', 'CTO/OS Subgroup',
       'CTO Description', 'EEO1 Reporting Cod Description', 'Census/OCC Code', 'Grand Total',
       'Total All Others (Confirmed target)', 'All Others, Confidential',
       'All Others, Not Confidential', 'Excluded from Coverage',
       'Manager, Confidential', 'Manager, Not Confidential',
       'Not Applicable - Contingent Wk', 'Not Covered HEERA (Out of Stat',
       'Stud Academic Title, No HEERA', 'Supervisor, Confidential',
       'Supervisor, Not Confidential', 'Supervisor, Represented']

In [45]:
final_non_lbnl_titles[column_order].to_excel("non_lbnl_apr_99_summary.xlsx", index=False)