<a href="https://colab.research.google.com/github/tougheye/Data_processing/blob/main/99_list_process.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

mar_2026_job_code_review_all = pd.read_excel("/content/drive/MyDrive/Data/UCOP_Job_Codes_Summary/UPTE-26-015_Job Summary Report_3.20.26.xlsx", sheet_name="Job Code Review")

mar_2026_job_code_review_all.head()

,Salary Plan SETID,Jobcode SETID,Job Code,Eff Date,Salary Grade Eff Status,Descr,Short Descr,Job Function,Sal Admin Plan,Grade,...,Last Update,Last Updated by,Last Updated Date Time,Key Job Code,CTO/OS Subgroup,Sys/Local Ind,OnCall Eligible,Elig Shift Diff,Classified,OSHPD Code
0,ASLA1,UCSHR,000245,1901-01-01,A,DIR,DIR,312,PE,K07,...,2014-07-16,UC_JPARK,2015-10-06 13:57:11.999,N,M10,L,N,N,2,00
1,ASLA1,UCSHR,000245,1901-01-01,A,DIR,DIR,312,PE,K05,...,2014-07-16,UC_JPARK,2015-10-06 13:57:11.999,N,M10,L,N,N,2,00
2,ASLA1,UCSHR,000245,1901-01-01,A,DIR,DIR,312,PE,K02,...,2014-07-16,UC_JPARK,2015-10-06 13:57:11.999,N,M10,L,N,N,2,00
3,ASLA1,UCSHR,000245,1901-01-01,A,DIR,DIR,312,PE,K04,...,2014-07-16,UC_JPARK,2015-10-06 13:57:11.999,N,M10,L,N,N,2,00
4,ASLA1,UCSHR,000245,1901-01-01,A,DIR,DIR,312,PE,K03,...,2014-07-16,UC_JPARK,2015-10-06 13:57:11.999,N,M10,L,N,N,2,00

Warning: Total number of columns (48) exceeds max_columns (20) limiting to first (20) columns.

In [2]:
mar_2026_job_code_review_all.shape

(46081, 48)

In [3]:
head_cnt_all_99_df = pd.read_excel("/content/Apr_2026_99_list_summary.xlsx", sheet_name="All_Non-LBNL_99_title_cnts")
head_cnt_all_99_df.head()

,Job Title,UPTE Unit for CTO,Current Status UPTE / UAW Titles in 99,Grand Total,Total All Others (Confirmed target),"All Others, Confidential","All Others, Not Confidential",Excluded from Coverage,"Manager, Confidential","Manager, Not Confidential",Not Applicable - Contingent Wk,Not Covered HEERA (Out of Stat,"Stud Academic Title, No HEERA","Supervisor, Confidential","Supervisor, Not Confidential","Supervisor, Represented"
0,ABSOLUTE RETURNS INV DIR,NaN,NaN,2,1,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ABSOLUTE RETURNS INV MGR 3,NaN,NaN,2,0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
2,ACAD ACHIEVEMENT CNSLR 3,NaN,SSAP,4,3,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
3,ACAD ACHIEVEMENT CNSLR 4,NaN,SSAP,18,1,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.0,NaN
4,ACAD ACHIEVEMENT CNSLR 5,NaN,SSAP,11,3,NaN,3.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,7.0,NaN

In [4]:
head_cnt_all_99_df.shape

(1973, 16)

In [5]:
upte_classes = pd.read_excel("/content/Apr_2026_99_list_summary.xlsx", sheet_name="UPTE_classes")
upte_classes.head()

,CTO/OS Subgroup,CTO/OS Subgroup Name,UPTE Total title Cnt,UPTE Classes,Total Title ATB,% Total title UPTE,0.99,99 Title Cnts,9C,9F,...,UF,UH,UL,WC,WE,WH,WK,WN,WS,WT
0,A10,RECREATIONAL SERVICES & ATHLETICS,2,HX/TX,17,0.117647,83.33%,15,0.00,0.00,...,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.00,0.0
1,A15,EXTERNAL AFFAIRS,1,TX,33,0.030303,80.56%,29,0.00,0.00,...,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.00,0.0
2,B15,CLERICAL/ADMIN,1,TX,110,0.009091,37.07%,43,14.66,0.86,...,0.0,0.0,0.0,7.76,2.59,0.00,0.0,0.0,0.00,0.0
3,C10,FOOD SERVICES,1,HX,10,0.100000,41.67%,5,0.00,0.00,...,0.0,0.0,0.0,0.00,0.00,8.33,0.0,0.0,8.33,0.0
4,D10,COMMUNICATION,12,TX,33,0.363636,58.82%,20,0.00,0.00,...,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.00,0.0

In [6]:
mar_2026_job_code_review_all.columns

Index(['Salary Plan SETID', 'Jobcode SETID', 'Job Code', 'Eff Date',
       'Salary Grade Eff Status', 'Descr', 'Short Descr', 'Job Function',
       'Sal Admin Plan', 'Grade', 'Step', 'Manager Level', 'Survey Salary',
       'Union Code', 'Retro Rate', 'Retro Percent', 'Currency', 'Stnd Hrs/Wk',
       'Work Period', 'Comp Frequency', 'Job Family', 'Reg/Temp', 'Tipped',
       'Med Checkup', 'FLSA Status', 'EEO-1 Cat', 'EEO-4 Cat', 'EEO-5 Cat',
       'EEO-6 Cat', 'SOC', 'IPEDSS Code', 'OCC', 'Telework', 'Company',
       'Encmb Indc', 'Posn Mgmt?', 'Enc Sal Optn', 'Enc Sal Amt',
       'Last Update ', 'Last Updated by', 'Last Updated Date Time',
       'Key Job Code', 'CTO/OS Subgroup', 'Sys/Local Ind', 'OnCall Eligible',
       'Elig Shift Diff', 'Classified', 'OSHPD Code'],
      dtype='object')

Separate Out Columns to keep from Job Code Review tab

In [7]:
job_code_review_cols = ['Job Code', 'Descr', 'Short Descr', 'CTO/OS Subgroup', 'Union Code', 'FLSA Status']