<a href="https://colab.research.google.com/github/tougheye/Data_processing/blob/main/collapsing_columns.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

excel_file = pd.ExcelFile("/content/UPTE_Newly_Accreted_codes.xlsx")
tab_names = excel_file.sheet_names

In [7]:
df = excel_file.parse(tab_names[2], dtype=str)

df.head(50)

,Location/Business Unit,Jobcode,Job Title Abbr Name,Title Group
0,BKCMP,9535,ANML HEALTH TCHN 3,ANML HEALTH TCHN
1,BKCMP,9525,ANML TCHN,ANML TCHN
2,BKCMP,9523,ANML TCHN PRN,ANML TCHN
3,BKCMP,9524,ANML TCHN SR,ANML TCHN
4,BKCMP,5436,APPLICATIONS PROGR 1 TX,Applications Prog
5,BKCMP,5437,APPLICATIONS PROGR 2 TX,Applications Prog
6,BKCMP,6103,ARTIST,ARTIST
7,BKCMP,6102,ARTIST SR,ARTIST
8,BKCMP,5162,AV IT ENGR 3 TX,AV IT ENGR
9,BKCMP,5163,AV IT ENGR 4 TX,AV IT ENGR
10,BKCMP,4458,BEH HEALTH COUNSELOR 2 HX,BEH HEALTH COUNSELOR
11,BKCMP,4459,BEH HEALTH COUNSELOR 3 HX,BEH HEALTH COUNSELOR
12,BKCMP,4460,BEH HEALTH COUNSELOR 4 HX,BEH HEALTH COUNSELOR
13,BKCMP,5311,BROADCAST COMM SPEC 2 TX,BROADCAST COMM SPEC
14,BKCMP,5446,BUS SYS ANL 2 TX,Bus Sys Anal
15,BKCMP,7359,BUS TCHL SUPP ANL 2 TX,BUS TCHL SUPP ANL
16,BKCMP,7358,BUS TCHL SUPP ANL 3 TX,BUS TCHL SUPP ANL
17,BKCMP,6681,CART CAPTIONIST,CART CAPTIONIST
18,BKCMP,6682,CART CAPTIONIST PD,CART CAPTIONIST
19,BKCMP,8940,CLIN LAB SCI,CLIN LAB SCI
20,BKCMP,8956,CLIN LAB SCI PD,CLIN LAB SCI
21,BKCMP,8939,CLIN LAB SCI SPEC,CLIN LAB SCI
22,BKCMP,9313,CLIN SOCIAL WORKER 3,SOCIAL WORKER
23,BKCMP,9558,CNSLNG PSYCHOLOGIST 3 HX,PSYCHOLOGIST
24,BKCMP,6379,CNSLNG PSYCHOLOGIST 4 HX GF,PSYCHOLOGIST
25,BKCMP,5165,COMM AND NETWORK TCHL ANL 2 TX,COMM AND NETWORK TCHL ANL
26,BKCMP,5168,COMM AND NETWORK TCHL ANL 3 TX,COMM AND NETWORK TCHL ANL
27,BKCMP,6380,COMM AND NTWK TCHL ANL 4 TX GF,COMM AND NETWORK TCHL ANL
28,BKCMP,6381,COMM AND NTWK TCHL ANL 5 TX GF,COMM AND NETWORK TCHL ANL
29,BKCMP,4804,COMPUTER RESC SPEC 2,COMPUTER RESC SPEC
30,BKCMP,5449,DATA SYS ANL 1 TX,Data Sys Anal
31,BKCMP,5453,DATA SYS ANL 2 TX,Data Sys Anal
32,BKCMP,7170,DEV TCHN 5,DEV TCHN
33,BKCMP,7684,EDITOR,EDITOR
34,BKCMP,4505,EDUC TCHL SPEC 3 TX,EDUC TCHL SPEC
35,BKCMP,4506,EDUC TCHL SPEC 4 TX,EDUC TCHL SPEC
36,BKCMP,5302,EHS SPEC 2 NEX RX,EHS SPEC
37,BKCMP,7141,EHS TCHN PRN,EHS TCHN
38,BKCMP,7142,EHS TCHN SR,EHS TCHN
39,BKCMP,8301,ELECTR TCHN PRN,ELECTR TCHN
40,BKCMP,5460,INFO SYS ANL 1 TX,Info Sys Anal
41,BKCMP,9605,LAB AST 1,LAB AST
42,BKCMP,9603,LAB AST 2,LAB AST
43,BKCMP,9602,LAB AST 3,LAB AST
44,BKCMP,9601,LAB AST 4,LAB AST
45,BKCMP,8311,LAB GLASSBLOWER PRN,LAB GLASSBLOWER
46,BKCMP,8654,LAB MECHN HELPER,LAB MECHN
47,BKCMP,8651,LAB MECHN PRN,LAB MECHN
48,BKCMP,8652,LAB MECHN SR,LAB MECHN
49,BKCMP,4031,LIFEGUARD,LIFEGUARD

In [8]:
print(df.columns)

Index(['Location/Business Unit', 'Jobcode', 'Job Title Abbr Name',
       'Title Group'],
      dtype='object')

In [9]:
grouped_df = df.groupby(['Location/Business Unit', 'Title Group']).agg(
    Jobcodes=('Jobcode', lambda x: ', '.join(x)),
    Job_Title_Abbr_Names=('Job Title Abbr Name', lambda x: ', '.join(x))
).reset_index()

display(grouped_df)

,Location/Business Unit,Title Group,Jobcodes,Job_Title_Abbr_Names
0,BKCMP,ANML HEALTH TCHN,9535,ANML HEALTH TCHN 3
1,BKCMP,ANML TCHN,"9525, 9523, 9524","ANML TCHN, ANML TCHN PRN, ANML TCHN SR"
2,BKCMP,ARTIST,"6103, 6102","ARTIST, ARTIST SR"
3,BKCMP,AV IT ENGR,"5162, 5163","AV IT ENGR 3 TX, AV IT ENGR 4 TX"
4,BKCMP,Applications Prog,"5436, 5437","APPLICATIONS PROGR 1 TX, APPLICATIONS PROGR 2 TX"
...,...,...,...,...
727,UCOP1,POPULATION HEALTH SPEC,5417,POPULATION HEALTH SPEC 3 HX
728,UCOP1,SYS ADM,"4698, 4699","SYS ADM 2 TX, SYS ADM 3 TX"
729,UCOP1,SYS INTEGRATION ENGR,6394,SYS INTEGRATION ENGR 4 TX GF
730,UCOP1,TECH SUPP ANL,"7347, 7348","TECH SUPP ANL 2, TECH SUPP ANL 3"
731,UCOP1,USER EXP DESIGNER,6396,USER EXP DESIGNER 4 TX GF