<a href="https://colab.research.google.com/github/tougheye/Data_processing/blob/main/Doctor_workload_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This project is to take in the medical cost reports and compare the doctor workload data year over year

In [187]:
import pandas as pd

hosp_name = "UCSF_Parnassus"          #update the hospital name
cost_report_file_path = "/content/UCSF_Doc_workload_Anal.xlsx"    #update file path
cost_report_file = pd.ExcelFile(cost_report_file_path)
file_tabs = cost_report_file.sheet_names
file_tabs

['Active_Doc_Cnt', 'Service_Breakdown', 'Unit_cost_rev', 'FTE']

Read the Doctor count tab

In [188]:
doc_headcount_df = cost_report_file.parse(file_tabs[0], header=[0,1,2])
doc_headcount_df.head()

  Unnamed: 0_level_0       Unnamed: 1_level_0  \
  Unnamed: 0_level_1       Unnamed: 1_level_1
            Line No.       Clinical Specialty
0              110.0       Aerospace Medicine
1              115.0   Allergy and Immunology
2              120.0           Anesthesiology
3              125.0  Cardiovascular Diseases
4              130.0         Child Psychiatry

                Unnamed: 2_level_0                 2025                      \
                Unnamed: 2_level_1       Hospital Based
  2024-25  Change total Headcounts (1)\nBoard Certified (2)\nBoard Eligible
0                              NaN                  NaN                 NaN
1                         0.052632                 20.0                 NaN
2                        -0.920398                 16.0                23.0
3                         0.000000                 86.0                 3.0
4                         0.000000                  2.0                 2.0

                                                                            \
                         Non-Hospital Based
  Total Hospital Based (4)\nBoard Certified (5)\nBoard Eligible (6)\nOther
0                  0.0                  NaN                 NaN        NaN
1                 20.0                  NaN                 NaN        NaN
2                 39.0                  NaN                 NaN        NaN
3                 89.0                  NaN                 NaN        NaN
4                  4.0                  NaN                 NaN        NaN

                                  ...                           2021  \
  Residents/Fellows (Enter FTEs)  ... Residents/Fellows (Enter FTEs)
                  (7)\nResidents  ...                   (8)\nFellows
0                            NaN  ...                            NaN
1                            NaN  ...                           1.52
2                          67.71  ...                          13.95
3                            NaN  ...                           1.28
4                            NaN  ...                            NaN

                  2020                                           \
        Hospital Based
  (1)\nBoard Certified (2)\nBoard Eligible Total Hospital Based
0                  NaN                 NaN                  0.0
1                 19.0                 1.0                 20.0
2                138.0                11.0                149.0
3                 55.0                 1.0                 56.0
4                 12.0                 2.0                 14.0

                                                       \
    Non-Hospital Based
  (4)\nBoard Certified (5)\nBoard Eligible (6)\nOther
0                  NaN                 NaN        NaN
1                  NaN                 NaN        NaN
2                  NaN                 NaN        NaN
3                  NaN                 NaN        NaN
4                  NaN                 NaN        NaN


  Residents/Fellows (Enter FTEs)
                  (7)\nResidents (8)\nFellows (8)\nFellows.1
0                            NaN          NaN            NaN
1                            NaN         3.96       0.000000
2                          59.81        12.54      -0.738255
3                            NaN         1.99       0.589286
4                            NaN          NaN      -0.714286

[5 rows x 56 columns]

In [189]:
doc_headcount_df.columns = [f"{year}_{hosp}_{cat}" for year, hosp, cat in doc_headcount_df.columns]

# doc_headcount_df.columns

In [190]:
column_dict = {'Unnamed: 0_level_0_Unnamed: 0_level_1_Line No.': "Line No",
               'Unnamed: 1_level_0_Unnamed: 1_level_1_Clinical Specialty': "Clinical Specialty",
                '2025_Hospital Based_(1)\nBoard Certified': '2025_Board Certified',
                '2025_Hospital Based_(2)\nBoard Eligible': '2025_Board Eligible',
                '2024_Hospital Based_(1)\nBoard Certified': '2024_Board Certified',
                '2024_Hospital Based_(2)\nBoard Eligible': '2024_Board Eligible',
                '2023_Hospital Based_(1)\nBoard Certified': '2023_Board Certified',
                '2023_Hospital Based_(2)\nBoard Eligible': '2023_Board Eligible',
                '2022_Hospital Based_(1)\nBoard Certified': '2022_Board Certified',
                '2022_Hospital Based_(2)\nBoard Eligible': '2022_Board Eligible',
                '2021_Hospital Based_(1)\nBoard Certified': '2021_Board Certified',
                '2021_Hospital Based_(2)\nBoard Eligible': '2021_Board Eligible',
                '2020_Hospital Based_(1)\nBoard Certified': '2020_Board Certified',
                '2020_Hospital Based_(2)\nBoard Eligible': '2020_Board Eligible'}

In [191]:
doc_headcount_df.rename(columns=column_dict, inplace=True)
doc_headcount_df.fillna(0, inplace=True)
doc_headcount_df.head()

,Line No,Clinical Specialty,Unnamed: 2_level_0_Unnamed: 2_level_1_2024-25 Change total Headcounts,2025_Board Certified,2025_Board Eligible,2025_Hospital Based_Total Hospital Based,2025_Non-Hospital Based_(4)\nBoard Certified,2025_Non-Hospital Based_(5)\nBoard Eligible,2025_Non-Hospital Based_(6)\nOther,2025_Residents/Fellows (Enter FTEs)_(7)\nResidents,...,2021_Residents/Fellows (Enter FTEs)_(8)\nFellows,2020_Board Certified,2020_Board Eligible,2020_Hospital Based_Total Hospital Based,2020_Non-Hospital Based_(4)\nBoard Certified,2020_Non-Hospital Based_(5)\nBoard Eligible,2020_Non-Hospital Based_(6)\nOther,2020_Residents/Fellows (Enter FTEs)_(7)\nResidents,2020_Residents/Fellows (Enter FTEs)_(8)\nFellows,2020_Residents/Fellows (Enter FTEs)_(8)\nFellows.1
0,110.0,Aerospace Medicine,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.000000
1,115.0,Allergy and Immunology,0.052632,20.0,0.0,20.0,0.0,0.0,0.0,0.00,...,1.52,19.0,1.0,20.0,0.0,0.0,0.0,0.00,3.96,0.000000
2,120.0,Anesthesiology,-0.920398,16.0,23.0,39.0,0.0,0.0,0.0,67.71,...,13.95,138.0,11.0,149.0,0.0,0.0,0.0,59.81,12.54,-0.738255
3,125.0,Cardiovascular Diseases,0.000000,86.0,3.0,89.0,0.0,0.0,0.0,0.00,...,1.28,55.0,1.0,56.0,0.0,0.0,0.0,0.00,1.99,0.589286
4,130.0,Child Psychiatry,0.000000,2.0,2.0,4.0,0.0,0.0,0.0,0.00,...,0.00,12.0,2.0,14.0,0.0,0.0,0.0,0.00,0.00,-0.714286

In [192]:
# REad the cost report category comparison file to get the specialty matches with service categories

category_details = pd.read_excel("/content/drive/MyDrive/Cost_rept_comp_categories.xlsx")

In [193]:
category_details['Cost_rev_row'] = category_details['Cost_rev_row'].fillna(0).astype(int)

Read the Services data from the updloaded file

In [194]:
service_unit_df = cost_report_file.parse(file_tabs[2], header=[0,1])
# service_unit_df.head()

In [195]:
service_unit_df.columns = [f"{year}_{cat}" for year, cat in service_unit_df.columns]

In [196]:
col_dict = {'Unnamed: 0_level_0_Line No.': "Line No",
            'Unnamed: 1_level_0_Revenue Producing Centers': "Revenue Producing Centers",
            '2025_(1)\nUnits of Service\nfrom Pg 17 Col 13': "2025_Units of Service",
            '2024_(1)\nUnits of Service\nfrom Pg 17 Col 13': "2024_Units of Service",
            '2023_(1)\nUnits of Service\nfrom Pg 17 Col 13': "2023_Units of Service",
            '2022_(1)\nUnits of Service\nfrom Pg 17 Col 13': "2022_Units of Service",
            '2021_(1)\nUnits of Service\nfrom Pg 17 Col 13': "2021_Units of Service",
            '2020_(1)\nUnits of Service\nfrom Pg 17 Col 13': "2020_Units of Service"}

In [197]:
service_unit_df.rename(columns=col_dict, inplace=True)
service_unit_df.head()

,Line No,Revenue Producing Centers,Unnamed: 2_level_0_Unit of Serv/Doc Prod Hr. 2025,2025_Units of Service,2025_Net Gain,2025_(4)\nTotal Patient\nCare Costs\nfrom Pg 20 Col 16\nLns 505 thru 915,2025_(11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22,2025_Unit of Serv/Doc Prod Hr. 2024,2024_Units of Service,2024_Net Gain,...,2020_Net Gain,2020_(4)\nTotal Patient\nCare Costs\nfrom Pg 20 Col 16\nLns 505 thru 915,2020_(11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22,2020_(11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22.1,2020_(11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22.2,2020_(11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22.3,2020_(11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22.4,2020_(11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22.5,2020_(11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22.6,2020_(11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22.7
0,NaN,Daily Hospital Services,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5.0,Medical/Surgical Intensive Care,17.872570,16550.0,345136820.0,129805911.0,474942731.0,NaN,15886.0,329752599.0,...,285329129.0,95704210.0,381033339.0,NaN,NaN,NaN,NaN,NaN,NaN,Pathologists
2,10.0,Coronary Care,16.451098,8242.0,184438979.0,62095789.0,246534768.0,NaN,8182.0,185064529.0,...,174689991.0,48511266.0,223201257.0,NaN,NaN,NaN,NaN,NaN,NaN,Oncologists
3,15.0,Pediatric Intensive Care,26.510593,12513.0,385156628.0,94550877.0,479707505.0,NaN,11974.0,370505050.0,...,351988038.0,73811155.0,425799193.0,NaN,NaN,NaN,NaN,NaN,NaN,Surgeons
4,20.0,Neonatal Intensive Care,7.576070,19122.0,562327101.0,130199301.0,692526402.0,13.177364,19094.0,546898331.0,...,453604865.0,101819163.0,555424028.0,NaN,NaN,NaN,NaN,NaN,NaN,Radiologists

In [198]:
# cast the line no to int to match the cost report file
service_unit_df['Line No'] = service_unit_df['Line No'].fillna(0).astype(int)

In [199]:
serv_unit_col_list = ['Line No', 'Revenue Producing Centers']
for year in range(2025, 2019, -1):
  col_label = f"{year}_Units of Service"
  serv_unit_col_list.append(col_label)
  service_unit_df[col_label] = service_unit_df[col_label].fillna(0).astype(int)

# serv_unit_col_list

In [200]:
# doc_per_serv_unit = pd.DataFrame()
col_list = ['Line No', 'Clinical Specialty']
for year in range(2025, 2019, -1):
  col_label = f"{year}_Total_Hosp_doc"
  doc_headcount_df[col_label] = doc_headcount_df[f"{year}_Board Certified"] + doc_headcount_df[f"{year}_Board Eligible"]
  doc_headcount_df[col_label] = doc_headcount_df[col_label].astype(int)
  col_list.append(col_label)

**Create the doctor vs workload comparison dataframe**

In [201]:
doc_v_service_df = category_details.merge(doc_headcount_df[col_list], on= 'Clinical Specialty', how='left').rename(columns={'Line No': 'Line No_doc'})
doc_v_service_df = doc_v_service_df.merge(service_unit_df[serv_unit_col_list], left_on='Cost_rev_row', right_on='Line No', how='inner').drop(columns=['Line No_doc', 'Line No',"Revenue Producing Centers"]).drop_duplicates().reset_index(drop=True)

Calculate services per doctors

In [202]:
import numpy as np
for year in range(2025, 2019, -1):
  col_label = f"{year}_Total_serv_per_doc"

  denominator = doc_v_service_df[f"{year}_Total_Hosp_doc"]
  # handle the doctor count 0 preventing an infinity
  doc_v_service_df[col_label] = doc_v_service_df[f"{year}_Units of Service"].div(denominator.replace(0, np.nan)).round(2)

Add doctor count comparison from 2020 to 2025

In [203]:
from os import replace
denom = doc_v_service_df['2020_Total_Hosp_doc']
nom = doc_v_service_df['2025_Total_Hosp_doc'] - doc_v_service_df['2020_Total_Hosp_doc']
doc_v_service_df['Doc_diff_2020_2025'] = (
    nom.div(denom.replace(0,np.nan))  * 100
).map('{:.2f}%'.format)

Set columns in the right order

In [204]:
col_order = ['Clinical Specialty', 'Cost_rev_row', 'Rev_prod_center',
       'Standard Unit\nof Measure', "Doc_diff_2020_2025", '2025_Total_serv_per_doc',
       '2024_Total_serv_per_doc', '2023_Total_serv_per_doc',
       '2022_Total_serv_per_doc', '2021_Total_serv_per_doc',
       '2020_Total_serv_per_doc' ,'2025_Total_Hosp_doc',
       '2024_Total_Hosp_doc', '2023_Total_Hosp_doc', '2022_Total_Hosp_doc',
       '2021_Total_Hosp_doc', '2020_Total_Hosp_doc', '2025_Units of Service',
       '2024_Units of Service', '2023_Units of Service',
       '2022_Units of Service', '2021_Units of Service',
       '2020_Units of Service']

In [205]:
doc_v_service_df = doc_v_service_df[col_order]

In [206]:
doc_v_service_df.to_excel(f"{hosp_name}_doc_v_service.xlsx")