<a href="https://colab.research.google.com/github/tougheye/Data_processing/blob/main/Doctor_workload_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This project is to take in the medical cost reports and compare the doctor workload data year over year

In [3]:
import pandas as pd

cost_report_file_path = "/content/Reagan_Doc_Workload_Anal.xlsx"
cost_report_file = pd.ExcelFile(cost_report_file_path)
file_tabs = cost_report_file.sheet_names
file_tabs

['Doc_Headcnt', 'Unit_of_Serv', 'Unit_serv_cost_rev']

In [4]:
doc_headcount_df = cost_report_file.parse(file_tabs[0], header=[0,1,2])
doc_headcount_df.head()

  Unnamed: 0_level_0       Unnamed: 1_level_0  \
  Unnamed: 0_level_1       Unnamed: 1_level_1
            Line No.       Clinical Specialty
0                110       Aerospace Medicine
1                115   Allergy and Immunology
2                120           Anesthesiology
3                125  Cardiovascular Diseases
4                130         Child Psychiatry

                       Unnamed: 2_level_0                 2025  \
                       Unnamed: 2_level_1       Hospital Based
  Change total Headcounts from Prev. Year (1)\nBoard Certified
0                                     NaN                  NaN
1                               -0.380952                 13.0
2                                0.005076                198.0
3                               -0.449198                103.0
4                               -0.409091                 13.0

                                                               \

  (2)\nBoard Eligible Change total Headcounts from Prev. Year
0                 NaN                                     NaN
1                 NaN                                0.500000
2                 NaN                               -0.019900
3                 NaN                                0.044693
4                 NaN                                0.157895

                  2024                      \
        Hospital Based
  (1)\nBoard Certified (2)\nBoard Eligible
0                  NaN                 NaN
1                 21.0                 NaN
2                197.0                 NaN
3                187.0                 NaN
4                 22.0                 NaN

                                                          2023  \
                                                Hospital Based
  Change total Headcounts from Prev. Year (1)\nBoard Certified
0                                     NaN                  NaN
1                               -0.125000                 14.0
2                                0.092391                201.0
3                                0.000000                179.0
4                                     NaN                 19.0

                                                               \

  (2)\nBoard Eligible Change total Headcounts from Prev. Year
0                 NaN                                     NaN
1                 NaN                                1.000000
2                 NaN                               -0.167421
3                 NaN                                     NaN
4                 NaN                                     NaN

                  2022                      \
        Hospital Based
  (1)\nBoard Certified (2)\nBoard Eligible
0                  NaN                 NaN
1                 16.0                 NaN
2                184.0                 NaN
3                179.0                 NaN
4                  NaN                 NaN

                                                          2021  \
                                                Hospital Based
  Change total Headcounts from Prev. Year (1)\nBoard Certified
0                                     NaN                  NaN
1                               -0.272727                  8.0
2                                0.589928                221.0
3                                     NaN                  NaN
4                                     NaN                  NaN

                                      2020
                            Hospital Based
  (2)\nBoard Eligible (1)\nBoard Certified (2)\nBoard Eligible
0                 NaN                  NaN                 NaN
1                 NaN                 11.0                 NaN
2                 NaN                139.0                 NaN
3                 NaN                  NaN                 NaN
4                 NaN                  NaN                 NaN

In [6]:
doc_headcount_df.columns[3]

(2025, 'Hospital Based', '(1)\nBoard Certified')

In [7]:
doc_headcount_df.columns = [f"{year}_{hosp}_{cat}" for year, hosp, cat in doc_headcount_df.columns]

doc_headcount_df.columns

Index(['Unnamed: 0_level_0_Unnamed: 0_level_1_Line No.',
       'Unnamed: 1_level_0_Unnamed: 1_level_1_Clinical Specialty',
       'Unnamed: 2_level_0_Unnamed: 2_level_1_Change total Headcounts from Prev. Year',
       '2025_Hospital Based_(1)\nBoard Certified',
       '2025_Hospital Based_(2)\nBoard Eligible',
       '2025_Hospital Based_Change total Headcounts from Prev. Year',
       '2024_Hospital Based_(1)\nBoard Certified',
       '2024_Hospital Based_(2)\nBoard Eligible',
       '2024_Hospital Based_Change total Headcounts from Prev. Year',
       '2023_Hospital Based_(1)\nBoard Certified',
       '2023_Hospital Based_(2)\nBoard Eligible',
       '2023_Hospital Based_Change total Headcounts from Prev. Year',
       '2022_Hospital Based_(1)\nBoard Certified',
       '2022_Hospital Based_(2)\nBoard Eligible',
       '2022_Hospital Based_Change total Headcounts from Prev. Year',
       '2021_Hospital Based_(1)\nBoard Certified',
       '2021_Hospital Based_(2)\nBoard Eligible',
       '2020_Hospital Based_(1)\nBoard Certified',
       '2020_Hospital Based_(2)\nBoard Eligible'],
      dtype='object')

In [8]:
column_dict = {'Unnamed: 0_level_0_Unnamed: 0_level_1_Line No.': "Line No",
               'Unnamed: 1_level_0_Unnamed: 1_level_1_Clinical Specialty': "Clinical Specialty",
                '2025_Hospital Based_(1)\nBoard Certified': '2025_Board Certified',
                '2025_Hospital Based_(2)\nBoard Eligible': '2025_Board Eligible',
                '2024_Hospital Based_(1)\nBoard Certified': '2024_Board Certified',
                '2024_Hospital Based_(2)\nBoard Eligible': '2024_Board Eligible',
                '2023_Hospital Based_(1)\nBoard Certified': '2023_Board Certified',
                '2023_Hospital Based_(2)\nBoard Eligible': '2023_Board Eligible',
                '2022_Hospital Based_(1)\nBoard Certified': '2022_Board Certified',
                '2022_Hospital Based_(2)\nBoard Eligible': '2022_Board Eligible',
                '2021_Hospital Based_(1)\nBoard Certified': '2021_Board Certified',
                '2021_Hospital Based_(2)\nBoard Eligible': '2021_Board Eligible',
                '2020_Hospital Based_(1)\nBoard Certified': '2020_Board Certified',
                '2020_Hospital Based_(2)\nBoard Eligible': '2020_Board Eligible'}

In [15]:
doc_headcount_df.dtypes

Line No                                                                            int64
Clinical Specialty                                                                object
Unnamed: 2_level_0_Unnamed: 2_level_1_Change total Headcounts from Prev. Year    float64
2025_Board Certified                                                             float64
2025_Board Eligible                                                              float64
2025_Hospital Based_Change total Headcounts from Prev. Year                      float64
2024_Board Certified                                                             float64
2024_Board Eligible                                                              float64
2024_Hospital Based_Change total Headcounts from Prev. Year                      float64
2023_Board Certified                                                             float64
2023_Board Eligible                                                              float64
2023_Hospital Based_Change total Headcounts from Prev. Year                      float64
2022_Board Certified                                                             float64
2022_Board Eligible                                                              float64
2022_Hospital Based_Change total Headcounts from Prev. Year                      float64
2021_Board Certified                                                             float64
2021_Board Eligible                                                              float64
2020_Board Certified                                                             float64
2020_Board Eligible                                                              float64
2025_Total_Hosp_doc                                                              float64
2024_Total_Hosp_doc                                                              float64
2023_Total_Hosp_doc                                                              float64
2022_Total_Hosp_doc                                                              float64
2021_Total_Hosp_doc                                                              float64
dtype: object

In [9]:
doc_headcount_df.rename(columns=column_dict, inplace=True)
doc_headcount_df.fillna(0, inplace=True)
doc_headcount_df

,Line No,Clinical Specialty,Unnamed: 2_level_0_Unnamed: 2_level_1_Change total Headcounts from Prev. Year,2025_Board Certified,2025_Board Eligible,2025_Hospital Based_Change total Headcounts from Prev. Year,2024_Board Certified,2024_Board Eligible,2024_Hospital Based_Change total Headcounts from Prev. Year,2023_Board Certified,2023_Board Eligible,2023_Hospital Based_Change total Headcounts from Prev. Year,2022_Board Certified,2022_Board Eligible,2022_Hospital Based_Change total Headcounts from Prev. Year,2021_Board Certified,2021_Board Eligible,2020_Board Certified,2020_Board Eligible
0,110,Aerospace Medicine,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
1,115,Allergy and Immunology,-0.380952,13.0,0.0,0.500000,21.0,0.0,-0.125000,14.0,0.0,1.000000,16.0,0.0,-0.272727,8.0,0.0,11.0,0.0
2,120,Anesthesiology,0.005076,198.0,0.0,-0.019900,197.0,0.0,0.092391,201.0,0.0,-0.167421,184.0,0.0,0.589928,221.0,0.0,139.0,0.0
3,125,Cardiovascular Diseases,-0.449198,103.0,0.0,0.044693,187.0,0.0,0.000000,179.0,0.0,0.000000,179.0,0.0,0.000000,0.0,0.0,0.0,0.0
4,130,Child Psychiatry,-0.409091,13.0,0.0,0.157895,22.0,0.0,0.000000,19.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
5,135,Colon and Rectal Surgery,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
6,140,Dental,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,-1.000000,0.0,0.0,0.000000,19.0,0.0,0.0,0.0
7,145,Dermatology,-0.161290,52.0,0.0,0.319149,62.0,0.0,0.236842,47.0,0.0,0.187500,38.0,0.0,0.142857,32.0,0.0,28.0,0.0
8,150,Diagnostic Radiology,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
9,155,Forensic Pathology,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
10,160,Gastroenterology,0.250000,5.0,0.0,0.000000,4.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
11,165,General/Family Practice,-0.416667,49.0,0.0,1.333333,84.0,0.0,0.161290,36.0,0.0,-0.483333,31.0,0.0,0.538462,60.0,0.0,39.0,0.0
12,170,General Preventative Medicine,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
13,175,General Surgery,-0.163043,77.0,0.0,0.010989,92.0,0.0,0.045977,91.0,0.0,-0.534759,87.0,0.0,0.989362,187.0,0.0,94.0,0.0
14,180,Internal Medicine,-0.088924,584.0,0.0,0.232692,641.0,0.0,0.241050,520.0,0.0,-0.288625,419.0,0.0,0.263948,589.0,0.0,466.0,0.0
15,185,Neurological Surgery,-0.074074,25.0,0.0,0.038462,27.0,0.0,0.300000,26.0,0.0,-0.545455,20.0,0.0,1.000000,44.0,0.0,22.0,0.0
16,190,Neurology,-0.238411,115.0,0.0,0.013423,151.0,0.0,-0.006667,149.0,0.0,0.200000,150.0,0.0,0.524390,125.0,0.0,82.0,0.0
17,195,Nuclear Medicine,-0.090909,10.0,0.0,0.000000,11.0,0.0,0.000000,11.0,0.0,0.000000,11.0,0.0,0.222222,11.0,0.0,9.0,0.0
18,200,Obstetrics and Gynecology,-0.270833,70.0,0.0,-0.172414,96.0,0.0,0.054545,116.0,0.0,0.134021,110.0,0.0,0.979592,97.0,0.0,49.0,0.0
19,205,Occupational Medicine,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
20,210,Oncology,-0.339181,113.0,0.0,-0.065574,171.0,0.0,0.045714,183.0,0.0,0.682692,175.0,0.0,0.507246,104.0,0.0,69.0,0.0
21,215,Ophthalmology,0.405405,104.0,0.0,-0.051282,74.0,0.0,-0.133333,78.0,0.0,-0.328358,90.0,0.0,0.810811,134.0,0.0,74.0,0.0
22,220,Oral Surgery (Dentists Only),0.272727,14.0,0.0,0.100000,11.0,0.0,0.000000,10.0,0.0,-0.696970,10.0,0.0,4.500000,33.0,0.0,6.0,0.0
23,225,Orthopedic Surgery,-0.138462,56.0,0.0,0.160714,65.0,0.0,-0.081967,56.0,0.0,0.051724,61.0,0.0,0.348837,58.0,0.0,43.0,0.0
24,230,Otolaryngology,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
25,235,Pathology,-0.262626,73.0,0.0,-0.029412,99.0,0.0,0.133333,102.0,0.0,0.500000,90.0,0.0,0.176471,60.0,0.0,51.0,0.0
26,240,Pediatric-Allergy,-0.454545,6.0,0.0,-0.153846,11.0,0.0,-0.380952,13.0,0.0,0.615385,21.0,0.0,0.300000,13.0,0.0,10.0,0.0
27,245,Pediatric-Cardiology,-0.357143,18.0,0.0,-0.200000,28.0,0.0,0.029412,35.0,0.0,0.360000,34.0,0.0,0.086957,25.0,0.0,23.0,0.0
28,250,Pediatric-Surgery,-0.500000,7.0,0.0,-0.125000,14.0,0.0,-0.111111,16.0,0.0,1.250000,18.0,0.0,0.142857,8.0,0.0,7.0,0.0
29,255,Pediatric Medicine,-0.374517,162.0,0.0,0.097458,259.0,0.0,-0.008403,236.0,0.0,0.190000,238.0,0.0,0.459854,200.0,0.0,137.0,0.0
30,260,Physical Medicine/Rehabilitation,-0.200000,16.0,0.0,0.176471,20.0,0.0,0.133333,17.0,0.0,0.500000,15.0,0.0,0.666667,10.0,0.0,6.0,0.0
31,265,Plastic and Reconstructive Surgery,-0.088235,31.0,0.0,0.133333,34.0,0.0,-0.090909,30.0,0.0,0.000000,33.0,0.0,0.571429,33.0,0.0,21.0,0.0
32,270,Podiatry,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
33,275,Psychiatry,-0.215190,62.0,0.0,-0.059524,79.0,0.0,-0.151515,84.0,0.0,-0.108108,99.0,0.0,0.000000,111.0,0.0,0.0,0.0
34,280,Public Health,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
35,285,Pulmonary Disease,-0.578125,81.0,0.0,0.010526,192.0,0.0,0.010638,190.0,0.0,1.473684,188.0,0.0,0.206349,76.0,0.0,63.0,0.0
36,290,Radiology,0.280702,73.0,0.0,0.357143,57.0,0.0,0.448276,42.0,0.0,-0.843243,29.0,0.0,0.761905,185.0,0.0,105.0,0.0
37,295,Therapeutic Radiology,-0.138462,112.0,0.0,-0.015152,130.0,0.0,0.007634,132.0,0.0,0.000000,131.0,0.0,0.000000,0.0,0.0,0.0,0.0
38,300,Thoracic Surgery,-0.461538,7.0,0.0,0.000000,13.0,0.0,0.181818,13.0,0.0,0.000000,11.0,0.0,1.200000,11.0,0.0,5.0,0.0
39,305,Urology,0.173913,54.0,0.0,0.150000,46.0,0.0,0.025641,40.0,0.0,-0.204082,39.0,0.0,0.580645,49.0,0.0,31.0,0.0
40,310,Vascular Surgery,-0.250000,30.0,0.0,-0.047619,40.0,0.0,-0.045455,42.0,0.0,1.315789,44.0,0.0,0.187500,19.0,0.0,16.0,0.0
41,315,Other Specialties,-0.247387,216.0,0.0,0.157258,287.0,0.0,0.209756,248.0,0.0,0.000000,205.0,0.0,0.000000,0.0,0.0,0.0,0.0
42,320,TOTAL,-0.209612,2549.0,0.0,0.083669,3225.0,0.0,0.072046,2976.0,0.0,0.100714,2776.0,0.0,0.570361,2522.0,0.0,1606.0,0.0

In [10]:
for year in range(2025, 2020, -1):
  doc_headcount_df[f"{year}_Total_Hosp_doc"] = doc_headcount_df[f"{year}_Board Certified"] + doc_headcount_df[f"{year}_Board Eligible"]

doc_headcount_df

,Line No,Clinical Specialty,Unnamed: 2_level_0_Unnamed: 2_level_1_Change total Headcounts from Prev. Year,2025_Board Certified,2025_Board Eligible,2025_Hospital Based_Change total Headcounts from Prev. Year,2024_Board Certified,2024_Board Eligible,2024_Hospital Based_Change total Headcounts from Prev. Year,2023_Board Certified,...,2022_Hospital Based_Change total Headcounts from Prev. Year,2021_Board Certified,2021_Board Eligible,2020_Board Certified,2020_Board Eligible,2025_Total_Hosp_doc,2024_Total_Hosp_doc,2023_Total_Hosp_doc,2022_Total_Hosp_doc,2021_Total_Hosp_doc
0,110,Aerospace Medicine,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,115,Allergy and Immunology,-0.380952,13.0,0.0,0.500000,21.0,0.0,-0.125000,14.0,...,-0.272727,8.0,0.0,11.0,0.0,13.0,21.0,14.0,16.0,8.0
2,120,Anesthesiology,0.005076,198.0,0.0,-0.019900,197.0,0.0,0.092391,201.0,...,0.589928,221.0,0.0,139.0,0.0,198.0,197.0,201.0,184.0,221.0
3,125,Cardiovascular Diseases,-0.449198,103.0,0.0,0.044693,187.0,0.0,0.000000,179.0,...,0.000000,0.0,0.0,0.0,0.0,103.0,187.0,179.0,179.0,0.0
4,130,Child Psychiatry,-0.409091,13.0,0.0,0.157895,22.0,0.0,0.000000,19.0,...,0.000000,0.0,0.0,0.0,0.0,13.0,22.0,19.0,0.0,0.0
5,135,Colon and Rectal Surgery,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,140,Dental,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,...,0.000000,19.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19.0
7,145,Dermatology,-0.161290,52.0,0.0,0.319149,62.0,0.0,0.236842,47.0,...,0.142857,32.0,0.0,28.0,0.0,52.0,62.0,47.0,38.0,32.0
8,150,Diagnostic Radiology,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,155,Forensic Pathology,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,160,Gastroenterology,0.250000,5.0,0.0,0.000000,4.0,0.0,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,5.0,4.0,0.0,0.0,0.0
11,165,General/Family Practice,-0.416667,49.0,0.0,1.333333,84.0,0.0,0.161290,36.0,...,0.538462,60.0,0.0,39.0,0.0,49.0,84.0,36.0,31.0,60.0
12,170,General Preventative Medicine,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,175,General Surgery,-0.163043,77.0,0.0,0.010989,92.0,0.0,0.045977,91.0,...,0.989362,187.0,0.0,94.0,0.0,77.0,92.0,91.0,87.0,187.0
14,180,Internal Medicine,-0.088924,584.0,0.0,0.232692,641.0,0.0,0.241050,520.0,...,0.263948,589.0,0.0,466.0,0.0,584.0,641.0,520.0,419.0,589.0
15,185,Neurological Surgery,-0.074074,25.0,0.0,0.038462,27.0,0.0,0.300000,26.0,...,1.000000,44.0,0.0,22.0,0.0,25.0,27.0,26.0,20.0,44.0
16,190,Neurology,-0.238411,115.0,0.0,0.013423,151.0,0.0,-0.006667,149.0,...,0.524390,125.0,0.0,82.0,0.0,115.0,151.0,149.0,150.0,125.0
17,195,Nuclear Medicine,-0.090909,10.0,0.0,0.000000,11.0,0.0,0.000000,11.0,...,0.222222,11.0,0.0,9.0,0.0,10.0,11.0,11.0,11.0,11.0
18,200,Obstetrics and Gynecology,-0.270833,70.0,0.0,-0.172414,96.0,0.0,0.054545,116.0,...,0.979592,97.0,0.0,49.0,0.0,70.0,96.0,116.0,110.0,97.0
19,205,Occupational Medicine,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,210,Oncology,-0.339181,113.0,0.0,-0.065574,171.0,0.0,0.045714,183.0,...,0.507246,104.0,0.0,69.0,0.0,113.0,171.0,183.0,175.0,104.0
21,215,Ophthalmology,0.405405,104.0,0.0,-0.051282,74.0,0.0,-0.133333,78.0,...,0.810811,134.0,0.0,74.0,0.0,104.0,74.0,78.0,90.0,134.0
22,220,Oral Surgery (Dentists Only),0.272727,14.0,0.0,0.100000,11.0,0.0,0.000000,10.0,...,4.500000,33.0,0.0,6.0,0.0,14.0,11.0,10.0,10.0,33.0
23,225,Orthopedic Surgery,-0.138462,56.0,0.0,0.160714,65.0,0.0,-0.081967,56.0,...,0.348837,58.0,0.0,43.0,0.0,56.0,65.0,56.0,61.0,58.0
24,230,Otolaryngology,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,235,Pathology,-0.262626,73.0,0.0,-0.029412,99.0,0.0,0.133333,102.0,...,0.176471,60.0,0.0,51.0,0.0,73.0,99.0,102.0,90.0,60.0
26,240,Pediatric-Allergy,-0.454545,6.0,0.0,-0.153846,11.0,0.0,-0.380952,13.0,...,0.300000,13.0,0.0,10.0,0.0,6.0,11.0,13.0,21.0,13.0
27,245,Pediatric-Cardiology,-0.357143,18.0,0.0,-0.200000,28.0,0.0,0.029412,35.0,...,0.086957,25.0,0.0,23.0,0.0,18.0,28.0,35.0,34.0,25.0
28,250,Pediatric-Surgery,-0.500000,7.0,0.0,-0.125000,14.0,0.0,-0.111111,16.0,...,0.142857,8.0,0.0,7.0,0.0,7.0,14.0,16.0,18.0,8.0
29,255,Pediatric Medicine,-0.374517,162.0,0.0,0.097458,259.0,0.0,-0.008403,236.0,...,0.459854,200.0,0.0,137.0,0.0,162.0,259.0,236.0,238.0,200.0
30,260,Physical Medicine/Rehabilitation,-0.200000,16.0,0.0,0.176471,20.0,0.0,0.133333,17.0,...,0.666667,10.0,0.0,6.0,0.0,16.0,20.0,17.0,15.0,10.0
31,265,Plastic and Reconstructive Surgery,-0.088235,31.0,0.0,0.133333,34.0,0.0,-0.090909,30.0,...,0.571429,33.0,0.0,21.0,0.0,31.0,34.0,30.0,33.0,33.0
32,270,Podiatry,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,275,Psychiatry,-0.215190,62.0,0.0,-0.059524,79.0,0.0,-0.151515,84.0,...,0.000000,111.0,0.0,0.0,0.0,62.0,79.0,84.0,99.0,111.0
34,280,Public Health,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35,285,Pulmonary Disease,-0.578125,81.0,0.0,0.010526,192.0,0.0,0.010638,190.0,...,0.206349,76.0,0.0,63.0,0.0,81.0,192.0,190.0,188.0,76.0
36,290,Radiology,0.280702,73.0,0.0,0.357143,57.0,0.0,0.448276,42.0,...,0.761905,185.0,0.0,105.0,0.0,73.0,57.0,42.0,29.0,185.0
37,295,Therapeutic Radiology,-0.138462,112.0,0.0,-0.015152,130.0,0.0,0.007634,132.0,...,0.000000,0.0,0.0,0.0,0.0,112.0,130.0,132.0,131.0,0.0
38,300,Thoracic Surgery,-0.461538,7.0,0.0,0.000000,13.0,0.0,0.181818,13.0,...,1.200000,11.0,0.0,5.0,0.0,7.0,13.0,13.0,11.0,11.0
39,305,Urology,0.173913,54.0,0.0,0.150000,46.0,0.0,0.025641,40.0,...,0.580645,49.0,0.0,31.0,0.0,54.0,46.0,40.0,39.0,49.0
40,310,Vascular Surgery,-0.250000,30.0,0.0,-0.047619,40.0,0.0,-0.045455,42.0,...,0.187500,19.0,0.0,16.0,0.0,30.0,40.0,42.0,44.0,19.0
41,315,Other Specialties,-0.247387,216.0,0.0,0.157258,287.0,0.0,0.209756,248.0,...,0.000000,0.0,0.0,0.0,0.0,216.0,287.0,248.0,205.0,0.0
42,320,TOTAL,-0.209612,2549.0,0.0,0.083669,3225.0,0.0,0.072046,2976.0,...,0.570361,2522.0,0.0,1606.0,0.0,2549.0,3225.0,2976.0,2776.0,2522.0

In [18]:
category_details = pd.read_excel("/content/Cost_rept_comp_categories.xlsx")

In [20]:
category_details['Cost_rev_row'] = category_details['Cost_rev_row'].fillna(0).astype(int)

In [21]:
category_details

,Clinical Specialty,Cost_rev_row,Rev_prod_center,Standard Unit\nof Measure
0,Anesthesiology,245,Anesthesiology,Anesthesia Minutes
1,Diagnostic Radiology,300,Radiology - Diagnostic,Procedures
2,Gastroenterology,355,Gastro-Intestinal Services,Procedures
3,Neurological Surgery,0,NaN,NaN
4,Ophthalmology,0,NaN,NaN
5,Orthopedic Surgery,0,NaN,NaN
6,Pulmonary Disease,340,Pulmonary Function Services,Procedures
7,Pulmonary Disease,335,Respiratory Therapy,Respiratory Therapy Adj. Inpatient Days
8,Radiology,0,NaN,NaN
9,Therapeutic Radiology,305,Radiology - Therapeutic,Procedures
10,Psychiatry,385,Psychiatric/Psychological Testing,Sessions
11,Psychiatry,390,Psychiatric Individual/Group Therapy,Sessions
12,Psychiatry,380,Electroconvulsive Therapy,Treatments
13,Psychiatry,170,Psychiatric Emergency Rooms,Visits
14,Child Psychiatry,0,NaN,NaN
15,Pediatric-Allergy,0,NaN,NaN
16,Pediatric-Cardiology,0,NaN,NaN
17,Pediatric-Surgery,20,Neonatal Intensive Care,Patient Census Days
18,Pediatric Medicine,20,Neonatal Intensive Care,Patient Census Days
19,Pediatric-Surgery,15,Pediatric Intensive Care,Patient Census Days
20,Pediatric Medicine,15,Pediatric Intensive Care,Patient Census Days
21,Obstetrics and Gynecology,230,Labor and Delivery Services,Deliveries
22,Pediatric-Surgery,50,Pediatric Acute,Patient Census Days
23,Pediatric Medicine,50,Pediatric Acute,Patient Census Days
24,Urology,350,Lithotripsy,Procedures
25,Cardiovascular Diseases,280,Cardiac Catheterization Services,Procedures
26,Cardiovascular Diseases,285,Cardiology Services,Procedures