<a href="https://colab.research.google.com/github/tougheye/Data_processing/blob/main/Doctor_workload_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This project is to take in the medical cost reports and compare the doctor workload data year over year

In [352]:
import pandas as pd

hosp_name = "Hillcrest"          #update the hospital name
cost_report_file_path = "/content/Hillcrest_doc_workload.xlsx"    #update file path
cost_report_file = pd.ExcelFile(cost_report_file_path)
file_tabs = cost_report_file.sheet_names
file_tabs

['Sheet1', 'Sheet2', 'Sheet3']

Read the Doctor count tab

In [353]:
doc_headcount_df = cost_report_file.parse(file_tabs[0], header=[0,1,2])
doc_headcount_df.head()

  Unnamed: 0_level_0       Unnamed: 1_level_0  \
  Unnamed: 0_level_1       Unnamed: 1_level_1
            Line No.       Clinical Specialty
0                110       Aerospace Medicine
1                115   Allergy and Immunology
2                120           Anesthesiology
3                125  Cardiovascular Diseases
4                130         Child Psychiatry

                                 Unnamed: 2_level_0                 2025  \
                                 Unnamed: 2_level_1       Hospital Based
  Change of Total Hospital Based from previous year (1)\nBoard Certified
0                                               NaN                  NaN
1                                               NaN                  NaN
2                                          0.434783                  9.0
3                                          0.222222                 10.0
4                                               NaN                  NaN

                                                                 \
                                             Non-Hospital Based
  (2)\nBoard Eligible Total Hospital Based (4)\nBoard Certified
0                 NaN                    0                  NaN
1                 NaN                    0                 75.0
2                24.0                   33                201.0
3                12.0                   22                341.0
4                 NaN                    0                  8.0

                                                                 ...  \
                                 Residents/Fellows (Enter FTEs)  ...
  (5)\nBoard Eligible (6)\nOther                 (7)\nResidents  ...
0                 NaN        NaN                            NaN  ...
1                 NaN        NaN                            NaN  ...
2                 NaN        NaN                           37.0  ...
3                 NaN        NaN                            NaN  ...
4                 NaN        NaN                            NaN  ...

                            2021                              2020  \
  Residents/Fellows (Enter FTEs)                    Hospital Based
                  (7)\nResidents (8)\nFellows (1)\nBoard Certified
0                            NaN          NaN                  NaN
1                            NaN         0.19                  NaN
2                          32.85         9.53                  7.0
3                            NaN          NaN                  4.0
4                            NaN          NaN                  NaN

                                                                 \
                                             Non-Hospital Based
  (2)\nBoard Eligible Total Hospital Based (4)\nBoard Certified
0                 NaN                    0                  NaN
1                 NaN                    0                  9.0
2                 1.0                    8                124.0
3                 NaN                    4                159.0
4                 NaN                    0                  4.0


                                 Residents/Fellows (Enter FTEs)
  (5)\nBoard Eligible (6)\nOther                 (7)\nResidents (8)\nFellows
0                 NaN        NaN                            NaN          NaN
1                 2.0        NaN                            NaN         1.59
2                 NaN        NaN                           32.8         9.05
3                 NaN        NaN                            NaN          NaN
4                 NaN        NaN                            NaN          NaN

[5 rows x 53 columns]

In [354]:
doc_headcount_df.columns = [f"{year}_{hosp}_{cat}" for year, hosp, cat in doc_headcount_df.columns]

# doc_headcount_df.columns

In [355]:
column_dict = {'Unnamed: 0_level_0_Unnamed: 0_level_1_Line No.': "Line No",
               'Unnamed: 1_level_0_Unnamed: 1_level_1_Clinical Specialty': "Clinical Specialty",
                '2025_Hospital Based_(1)\nBoard Certified': '2025_Board Certified',
                '2025_Hospital Based_(2)\nBoard Eligible': '2025_Board Eligible',
                '2024_Hospital Based_(1)\nBoard Certified': '2024_Board Certified',
                '2024_Hospital Based_(2)\nBoard Eligible': '2024_Board Eligible',
                '2023_Hospital Based_(1)\nBoard Certified': '2023_Board Certified',
                '2023_Hospital Based_(2)\nBoard Eligible': '2023_Board Eligible',
                '2022_Hospital Based_(1)\nBoard Certified': '2022_Board Certified',
                '2022_Hospital Based_(2)\nBoard Eligible': '2022_Board Eligible',
                '2021_Hospital Based_(1)\nBoard Certified': '2021_Board Certified',
                '2021_Hospital Based_(2)\nBoard Eligible': '2021_Board Eligible',
                '2020_Hospital Based_(1)\nBoard Certified': '2020_Board Certified',
                '2020_Hospital Based_(2)\nBoard Eligible': '2020_Board Eligible'}

In [356]:
doc_headcount_df.rename(columns=column_dict, inplace=True)
doc_headcount_df.fillna(0, inplace=True)
doc_headcount_df.head()

,Line No,Clinical Specialty,Unnamed: 2_level_0_Unnamed: 2_level_1_Change of Total Hospital Based from previous year,2025_Board Certified,2025_Board Eligible,2025_Hospital Based_Total Hospital Based,2025_Non-Hospital Based_(4)\nBoard Certified,2025_Non-Hospital Based_(5)\nBoard Eligible,2025_Non-Hospital Based_(6)\nOther,2025_Residents/Fellows (Enter FTEs)_(7)\nResidents,...,2021_Residents/Fellows (Enter FTEs)_(7)\nResidents,2021_Residents/Fellows (Enter FTEs)_(8)\nFellows,2020_Board Certified,2020_Board Eligible,2020_Hospital Based_Total Hospital Based,2020_Non-Hospital Based_(4)\nBoard Certified,2020_Non-Hospital Based_(5)\nBoard Eligible,2020_Non-Hospital Based_(6)\nOther,2020_Residents/Fellows (Enter FTEs)_(7)\nResidents,2020_Residents/Fellows (Enter FTEs)_(8)\nFellows
0,110,Aerospace Medicine,0.000000,0.0,0.0,0,0.0,0.0,0.0,0.0,...,0.00,0.00,0.0,0.0,0,0.0,0.0,0.0,0.0,0.00
1,115,Allergy and Immunology,0.000000,0.0,0.0,0,75.0,0.0,0.0,0.0,...,0.00,0.19,0.0,0.0,0,9.0,2.0,0.0,0.0,1.59
2,120,Anesthesiology,0.434783,9.0,24.0,33,201.0,0.0,0.0,37.0,...,32.85,9.53,7.0,1.0,8,124.0,0.0,0.0,32.8,9.05
3,125,Cardiovascular Diseases,0.222222,10.0,12.0,22,341.0,0.0,0.0,0.0,...,0.00,0.00,4.0,0.0,4,159.0,0.0,0.0,0.0,0.00
4,130,Child Psychiatry,0.000000,0.0,0.0,0,8.0,0.0,0.0,0.0,...,0.00,0.00,0.0,0.0,0,4.0,0.0,0.0,0.0,0.00

In [357]:
# REad the cost report category comparison file to get the specialty matches with service categories

category_details = pd.read_excel("/content/drive/MyDrive/Cost_rept_comp_categories.xlsx")

In [358]:
category_details['Cost_rev_row'] = category_details['Cost_rev_row'].fillna(0).astype(int)

Read the Services data from the updloaded file

In [359]:
service_unit_df = cost_report_file.parse(file_tabs[2], header=[0,1])
# service_unit_df.head()

In [360]:
service_unit_df.columns = [f"{year}_{cat}" for year, cat in service_unit_df.columns]

In [361]:
col_dict = {'Unnamed: 0_level_0_Line No.': "Line No",
            'Unnamed: 1_level_0_Revenue Producing Centers': "Revenue Producing Centers",
            '2025_(1)\nUnits of Service\nfrom Pg 17 Col 13': "2025_Units of Service",
            '2024_(1)\nUnits of Service\nfrom Pg 17 Col 13': "2024_Units of Service",
            '2023_(1)\nUnits of Service\nfrom Pg 17 Col 13': "2023_Units of Service",
            '2022_(1)\nUnits of Service\nfrom Pg 17 Col 13': "2022_Units of Service",
            '2021_(1)\nUnits of Service\nfrom Pg 17 Col 13': "2021_Units of Service",
            '2020_(1)\nUnits of Service\nfrom Pg 17 Col 13': "2020_Units of Service"}

In [362]:
service_unit_df.rename(columns=col_dict, inplace=True)
service_unit_df.head()

,Line No,Revenue Producing Centers,2025_Units of Service,2025_(4)\nTotal Patient\nCare Costs\nfrom Pg 20 Col 16\nLns 505 thru 915,2025_(11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22,2024_Units of Service,2024_(4)\nTotal Patient\nCare Costs\nfrom Pg 20 Col 16\nLns 505 thru 915,2024_(11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22,2023_Units of Service,2023_(4)\nTotal Patient\nCare Costs\nfrom Pg 20 Col 16\nLns 505 thru 915,2023_(11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22,2022_Units of Service,2022_(4)\nTotal Patient\nCare Costs\nfrom Pg 20 Col 16\nLns 505 thru 915,2022_(11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22,2021_Units of Service,2021_(4)\nTotal Patient\nCare Costs\nfrom Pg 20 Col 16\nLns 505 thru 915,2021_(11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22,2020_Units of Service,2020_(4)\nTotal Patient\nCare Costs\nfrom Pg 20 Col 16\nLns 505 thru 915,2020_(11)\nGross Revenue\nfrom Pg 12\nCols 21 + 22
0,NaN,Daily Hospital Services,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5.0,Medical/Surgical Intensive Care,17770.0,145363195.0,677389484.0,14060.0,93499610.0,422634968.0,14018.0,85240424.0,347975955.0,14248.0,70379681.0,331068821.0,14090.0,64373486.0,309522188.0,14128.0,65390586.0,258418630.0
2,10.0,Coronary Care,16223.0,79684660.0,216050024.0,16506.0,86816037.0,255894711.0,16133.0,85030988.0,226173342.0,16137.0,79312508.0,209106206.0,15977.0,72304289.0,206067753.0,15608.0,72351198.0,190409775.0
3,15.0,Pediatric Intensive Care,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20.0,Neonatal Intensive Care,13294.0,53138985.0,166709253.0,11033.0,54191037.0,220358666.0,13514.0,52374919.0,151890583.0,12543.0,46414121.0,128736176.0,10746.0,36918991.0,100674131.0,11764.0,41267537.0,107243797.0

In [363]:
# cast the line no to int to match the cost report file
service_unit_df['Line No'] = service_unit_df['Line No'].fillna(0).astype(int)

In [364]:
serv_unit_col_list = ['Line No', 'Revenue Producing Centers']
for year in range(2025, 2019, -1):
  col_label = f"{year}_Units of Service"
  serv_unit_col_list.append(col_label)
  service_unit_df[col_label] = service_unit_df[col_label].fillna(0).astype(int)

# serv_unit_col_list

In [365]:
# doc_per_serv_unit = pd.DataFrame()
col_list = ['Line No', 'Clinical Specialty']
for year in range(2025, 2019, -1):
  col_label = f"{year}_Hosp_doc"
  doc_headcount_df[col_label] = doc_headcount_df[f"{year}_Board Certified"] + doc_headcount_df[f"{year}_Board Eligible"]
  doc_headcount_df[col_label] = doc_headcount_df[col_label].astype(int)
  col_list.append(col_label)

**Create the doctor vs workload comparison dataframe**

In [366]:
doc_v_service_df = category_details.merge(doc_headcount_df[col_list], on= 'Clinical Specialty', how='left').rename(columns={'Line No': 'Line No_doc', 'Clinical Specialty': "Doc_Specialty" })
doc_v_service_df = doc_v_service_df.merge(service_unit_df[serv_unit_col_list], left_on='Cost_rev_row', right_on='Line No', how='inner').drop(columns=['Line No_doc', 'Line No',"Revenue Producing Centers"]).drop_duplicates().reset_index(drop=True)

Calculate services per doctors

In [367]:
import numpy as np
for year in range(2025, 2019, -1):
  col_label = f"{year}_serv_per_doc"

  denominator = doc_v_service_df[f"{year}_Hosp_doc"]
  # handle the doctor count 0 preventing an infinity
  doc_v_service_df[col_label] = doc_v_service_df[f"{year}_Units of Service"].div(denominator.replace(0, np.nan)).round(2)

In [368]:
doc_v_service_df.columns

Index(['Doc_Specialty', 'Cost_rev_row', 'Rev_prod_center',
       'Standard Unit\nof Measure', '2025_Hosp_doc', '2024_Hosp_doc',
       '2023_Hosp_doc', '2022_Hosp_doc', '2021_Hosp_doc', '2020_Hosp_doc',
       '2025_Units of Service', '2024_Units of Service',
       '2023_Units of Service', '2022_Units of Service',
       '2021_Units of Service', '2020_Units of Service', '2025_serv_per_doc',
       '2024_serv_per_doc', '2023_serv_per_doc', '2022_serv_per_doc',
       '2021_serv_per_doc', '2020_serv_per_doc'],
      dtype='object')

Add doctor count comparison from 2020 to 2025

In [369]:
from IPython.utils.py3compat import re
from os import replace

def calc_pct_change(col_name):    #col_name is the string after the year of the category to update

  denom = doc_v_service_df[f'2020_{col_name}']
  nom = doc_v_service_df[f'2025_{col_name}'] - doc_v_service_df[f'2020_{col_name}']
  doc_v_service_df[f'{col_name}_chg_2020_2025'] = (
      nom.div(denom.replace(0,np.nan))  * 100
  ).map('{:.2f}%'.format)
  return doc_v_service_df

In [370]:
doc_v_service_df = calc_pct_change('serv_per_doc').rename(columns={'Total_serv_per_doc_chg_2020_2025': 'Serv_per_doc_change_2020-25'})
doc_v_service_df = calc_pct_change('Hosp_doc').rename(columns={'Total_Hosp_doc_chg_2020_2025': 'Doc_Cnt_Chg_2020-25',
                                                               'Standard Unit\nof Measure': 'Unit_of_Measure'})
doc_v_service_df.head()

,Doc_Specialty,Cost_rev_row,Rev_prod_center,Unit_of_Measure,2025_Hosp_doc,2024_Hosp_doc,2023_Hosp_doc,2022_Hosp_doc,2021_Hosp_doc,2020_Hosp_doc,...,2021_Units of Service,2020_Units of Service,2025_serv_per_doc,2024_serv_per_doc,2023_serv_per_doc,2022_serv_per_doc,2021_serv_per_doc,2020_serv_per_doc,serv_per_doc_chg_2020_2025,Hosp_doc_chg_2020_2025
0,Anesthesiology,245,Anesthesiology,Anesthesia Minutes,33,23,7,7,7,8,...,5189616,4605193,217237.94,286575.70,873057.43,808026.71,741373.71,575649.12,-62.26%,312.50%
1,Diagnostic Radiology,300,Radiology - Diagnostic,Procedures,2,4,2,1,1,0,...,195123,187955,120026.00,59567.75,110709.50,211207.00,195123.00,NaN,nan%,nan%
2,Gastroenterology,355,Gastro-Intestinal Services,Procedures,5,4,3,0,0,6,...,0,0,4280.60,0.00,0.00,NaN,NaN,0.00,nan%,-16.67%
3,Neurological Surgery,0,NaN,NaN,2,1,1,5,5,4,...,0,0,0.00,0.00,0.00,0.00,0.00,0.00,nan%,-50.00%
4,Ophthalmology,0,NaN,NaN,10,9,4,2,2,10,...,0,0,0.00,0.00,0.00,0.00,0.00,0.00,nan%,0.00%

Set columns in the right order

In [372]:
col_order = ['Rev_prod_center','Cost_rev_row',
       'Unit_of_Measure', 'serv_per_doc_chg_2020_2025',
       'Hosp_doc_chg_2020_2025', '2025_serv_per_doc', '2024_serv_per_doc',
       '2023_serv_per_doc', '2022_serv_per_doc', '2021_serv_per_doc',
       '2020_serv_per_doc' , "Doc_Specialty", '2025_Hosp_doc', '2024_Hosp_doc',
       '2023_Hosp_doc', '2022_Hosp_doc', '2021_Hosp_doc', '2020_Hosp_doc', '2025_Units of Service',
       '2024_Units of Service', '2023_Units of Service',
       '2022_Units of Service', '2021_Units of Service',
       '2020_Units of Service']

In [373]:
doc_v_service_df = doc_v_service_df[col_order]

In [374]:
doc_v_service_df.to_excel(f"{hosp_name}_doc_v_service.xlsx")