<a href="https://colab.research.google.com/github/tougheye/Data_processing/blob/main/Doctor_workload_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This project is to take in the medical cost reports and compare the doctor workload data year over year

In [24]:
import pandas as pd

cost_report_file_path = "/content/Reagan_Doc_Workload_Anal.xlsx"
cost_report_file = pd.ExcelFile(cost_report_file_path)
file_tabs = cost_report_file.sheet_names

In [25]:
doc_headcount_df = cost_report_file.parse(file_tabs[0], header=[0,1])
doc_headcount_df.head()

  Unnamed: 0_level_0       Unnamed: 1_level_0                 2025  \
            Line No.       Clinical Specialty (1)\nBoard Certified
0                110       Aerospace Medicine                  NaN
1                115   Allergy and Immunology                 13.0
2                120           Anesthesiology                198.0
3                125  Cardiovascular Diseases                103.0
4                130         Child Psychiatry                 13.0

                                      2024                      \
  (2)\nBoard Eligible (1)\nBoard Certified (2)\nBoard Eligible
0                 NaN                  NaN                 NaN
1                 NaN                 21.0                 NaN
2                 NaN                197.0                 NaN
3                 NaN                187.0                 NaN
4                 NaN                 22.0                 NaN

                  2023                                     2022  \
  (1)\nBoard Certified (2)\nBoard Eligible (1)\nBoard Certified
0                  NaN                 NaN                  NaN
1                 14.0                 NaN                 16.0
2                201.0                 NaN                184.0
3                179.0                 NaN                179.0
4                 19.0                 NaN                  NaN

                                      2021                      \
  (2)\nBoard Eligible (1)\nBoard Certified (2)\nBoard Eligible
0                 NaN                  NaN                 NaN
1                 NaN                  8.0                 NaN
2                 NaN                221.0                 NaN
3                 NaN                  NaN                 NaN
4                 NaN                  NaN                 NaN

                  2020
  (1)\nBoard Certified (2)\nBoard Eligible
0                  NaN                 NaN
1                 11.0                 NaN
2                139.0                 NaN
3                  NaN                 NaN
4                  NaN                 NaN

In [26]:
doc_headcount_df.columns

MultiIndex([('Unnamed: 0_level_0',             'Line No.'),
            ('Unnamed: 1_level_0',   'Clinical Specialty'),
            (                2025, '(1)\nBoard Certified'),
            (                2025,  '(2)\nBoard Eligible'),
            (                2024, '(1)\nBoard Certified'),
            (                2024,  '(2)\nBoard Eligible'),
            (                2023, '(1)\nBoard Certified'),
            (                2023,  '(2)\nBoard Eligible'),
            (                2022, '(1)\nBoard Certified'),
            (                2022,  '(2)\nBoard Eligible'),
            (                2021, '(1)\nBoard Certified'),
            (                2021,  '(2)\nBoard Eligible'),
            (                2020, '(1)\nBoard Certified'),
            (                2020,  '(2)\nBoard Eligible')],
           )

In [27]:
doc_headcount_df.columns = [f"{year}_{cat}" for year, cat in doc_headcount_df.columns]

# doc_headcount_df.columns

Index(['Unnamed: 0_level_0_Line No.', 'Unnamed: 1_level_0_Clinical Specialty',
       '2025_(1)\nBoard Certified', '2025_(2)\nBoard Eligible',
       '2024_(1)\nBoard Certified', '2024_(2)\nBoard Eligible',
       '2023_(1)\nBoard Certified', '2023_(2)\nBoard Eligible',
       '2022_(1)\nBoard Certified', '2022_(2)\nBoard Eligible',
       '2021_(1)\nBoard Certified', '2021_(2)\nBoard Eligible',
       '2020_(1)\nBoard Certified', '2020_(2)\nBoard Eligible'],
      dtype='object')

In [29]:
column_dict = {'Unnamed: 0_level_0_Line No.': "Line No", 'Unnamed: 1_level_0_Clinical Specialty': "Clinical Specialty",
       '2025_(1)\nBoard Certified': '2025_Board Certified', '2025_(2)\nBoard Eligible': '2025_Board Eligible',
       '2024_(1)\nBoard Certified': '2024_Board Certified', '2024_(2)\nBoard Eligible': '2024_Board Eligible',
       '2023_(1)\nBoard Certified': '2023_Board Certified', '2023_(2)\nBoard Eligible': '2023_Board Eligible',
       '2022_(1)\nBoard Certified': '2022_Board Certified', '2022_(2)\nBoard Eligible': '2022_Board Eligible',
       '2021_(1)\nBoard Certified': '2021_Board Certified', '2021_(2)\nBoard Eligible': '2021_Board Eligible',
       '2020_(1)\nBoard Certified': '2020_Board Certified', '2020_(2)\nBoard Eligible': '2020_Board Eligible'}

In [30]:
doc_headcount_df.rename(columns=column_dict, inplace=True)
doc_headcount_df

,Line No,Clinical Specialty,2025_Board Certified,2025_Board Eligible,2024_Board Certified,2024_Board Eligible,2023_Board Certified,2023_Board Eligible,2022_Board Certified,2022_Board Eligible,2021_Board Certified,2021_Board Eligible,2020_Board Certified,2020_Board Eligible
0,110,Aerospace Medicine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,115,Allergy and Immunology,13.0,NaN,21.0,NaN,14.0,NaN,16.0,NaN,8.0,NaN,11.0,NaN
2,120,Anesthesiology,198.0,NaN,197.0,NaN,201.0,NaN,184.0,NaN,221.0,NaN,139.0,NaN
3,125,Cardiovascular Diseases,103.0,NaN,187.0,NaN,179.0,NaN,179.0,NaN,NaN,NaN,NaN,NaN
4,130,Child Psychiatry,13.0,NaN,22.0,NaN,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,135,Colon and Rectal Surgery,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,140,Dental,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.0,NaN,NaN,NaN
7,145,Dermatology,52.0,NaN,62.0,NaN,47.0,NaN,38.0,NaN,32.0,NaN,28.0,NaN
8,150,Diagnostic Radiology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,155,Forensic Pathology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,160,Gastroenterology,5.0,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,165,General/Family Practice,49.0,NaN,84.0,NaN,36.0,NaN,31.0,NaN,60.0,NaN,39.0,NaN
12,170,General Preventative Medicine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,175,General Surgery,77.0,NaN,92.0,NaN,91.0,NaN,87.0,NaN,187.0,NaN,94.0,NaN
14,180,Internal Medicine,584.0,NaN,641.0,NaN,520.0,NaN,419.0,NaN,589.0,NaN,466.0,NaN
15,185,Neurological Surgery,25.0,NaN,27.0,NaN,26.0,NaN,20.0,NaN,44.0,NaN,22.0,NaN
16,190,Neurology,115.0,NaN,151.0,NaN,149.0,NaN,150.0,NaN,125.0,NaN,82.0,NaN
17,195,Nuclear Medicine,10.0,NaN,11.0,NaN,11.0,NaN,11.0,NaN,11.0,NaN,9.0,NaN
18,200,Obstetrics and Gynecology,70.0,NaN,96.0,NaN,116.0,NaN,110.0,NaN,97.0,NaN,49.0,NaN
19,205,Occupational Medicine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,210,Oncology,113.0,NaN,171.0,NaN,183.0,NaN,175.0,NaN,104.0,NaN,69.0,NaN
21,215,Ophthalmology,104.0,NaN,74.0,NaN,78.0,NaN,90.0,NaN,134.0,NaN,74.0,NaN
22,220,Oral Surgery (Dentists Only),14.0,NaN,11.0,NaN,10.0,NaN,10.0,NaN,33.0,NaN,6.0,NaN
23,225,Orthopedic Surgery,56.0,NaN,65.0,NaN,56.0,NaN,61.0,NaN,58.0,NaN,43.0,NaN
24,230,Otolaryngology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,235,Pathology,73.0,NaN,99.0,NaN,102.0,NaN,90.0,NaN,60.0,NaN,51.0,NaN
26,240,Pediatric-Allergy,6.0,NaN,11.0,NaN,13.0,NaN,21.0,NaN,13.0,NaN,10.0,NaN
27,245,Pediatric-Cardiology,18.0,NaN,28.0,NaN,35.0,NaN,34.0,NaN,25.0,NaN,23.0,NaN
28,250,Pediatric-Surgery,7.0,NaN,14.0,NaN,16.0,NaN,18.0,NaN,8.0,NaN,7.0,NaN
29,255,Pediatric Medicine,162.0,NaN,259.0,NaN,236.0,NaN,238.0,NaN,200.0,NaN,137.0,NaN
30,260,Physical Medicine/Rehabilitation,16.0,NaN,20.0,NaN,17.0,NaN,15.0,NaN,10.0,NaN,6.0,NaN
31,265,Plastic and Reconstructive Surgery,31.0,NaN,34.0,NaN,30.0,NaN,33.0,NaN,33.0,NaN,21.0,NaN
32,270,Podiatry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,275,Psychiatry,62.0,NaN,79.0,NaN,84.0,NaN,99.0,NaN,111.0,NaN,NaN,NaN
34,280,Public Health,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,285,Pulmonary Disease,81.0,NaN,192.0,NaN,190.0,NaN,188.0,NaN,76.0,NaN,63.0,NaN
36,290,Radiology,73.0,NaN,57.0,NaN,42.0,NaN,29.0,NaN,185.0,NaN,105.0,NaN
37,295,Therapeutic Radiology,112.0,NaN,130.0,NaN,132.0,NaN,131.0,NaN,NaN,NaN,NaN,NaN
38,300,Thoracic Surgery,7.0,NaN,13.0,NaN,13.0,NaN,11.0,NaN,11.0,NaN,5.0,NaN
39,305,Urology,54.0,NaN,46.0,NaN,40.0,NaN,39.0,NaN,49.0,NaN,31.0,NaN
40,310,Vascular Surgery,30.0,NaN,40.0,NaN,42.0,NaN,44.0,NaN,19.0,NaN,16.0,NaN
41,315,Other Specialties,216.0,NaN,287.0,NaN,248.0,NaN,205.0,NaN,NaN,NaN,NaN,NaN
42,320,TOTAL,2549.0,NaN,3225.0,NaN,2976.0,NaN,2776.0,NaN,2522.0,NaN,1606.0,NaN