<a href="https://colab.research.google.com/github/tougheye/Data_processing/blob/main/Old_juris_match.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

path_to_juris_folder = "/content/drive/MyDrive/Data/Juris Files/Combined_juris"

juris_2023 = pd.ExcelFile(f"{path_to_juris_folder}/2023_combined_juris.xlsx")

In [4]:
juris_2023.sheet_names

['2023_combined_juris']

In [33]:
dtype_mapping = {
    'EE ID': str,
    'Location': str
}
juris_2023_df = juris_2023.parse('2023_combined_juris', dtype=dtype_mapping)

In [6]:
juris_2023_df.shape

(254678, 124)

In [44]:
juris_2023_df[juris_2023_df['EE ID'].isin(['10119621', '10551385'])]

,Source File Name,Unit,Location,EE ID,Action,Action Type,Employee Name,Name 2,Home Address 1,Home Address 2,...,ARC_8,(Blank)_9,Title Code_9,Title Name_9,Annualized Pay_9,Appt %_9,Appt Type_9,TUC_9,ARC_9,X
4325,jurisW1OCT23.txt,HX,13,10119621,U,MNTHLY-NO CHG,"MOSHFEGH,ANAHITA",NaN,3624 MILITARY AVE.,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X
7400,jurisW1OCT23.txt,HX,16,10551385,U,MNTHLY-NO CHG,"BELL,CHARLES F",NaN,926 DE HARO STREET,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X
24033,jurisW1APR23.txt,HX,13,10119621,U,MNTHLY-NO CHG,"MOSHFEGH,ANAHITA",NaN,3624 MILITARY AVE.,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X
26988,jurisW1APR23.txt,HX,16,10551385,U,MNTHLY-NO CHG,"BELL,CHARLES F",NaN,926 DE HARO STREET,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X
44009,jurisW1MAR23.txt,HX,13,10119621,U,MNTHLY-NO CHG,"""MOSHFEGH,ANAHITA""",NaN,3624 MILITARY AVE.,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X
46972,jurisW1MAR23.txt,HX,16,10551385,U,MNTHLY-NO CHG,"""BELL,CHARLES F""",NaN,926 DE HARO STREET,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X
61651,jurisW1JUL23.txt,HX,13,10119621,U,MNTHLY-NO CHG,"MOSHFEGH,ANAHITA",NaN,3624 MILITARY AVE.,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X
64622,jurisW1JUL23.txt,HX,16,10551385,U,MNTHLY-NO CHG,"BELL,CHARLES F",NaN,926 DE HARO STREET,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X
80934,jurisW1FEB23.txt,HX,13,10119621,U,MNTHLY-NO CHG,"""MOSHFEGH,ANAHITA""",NaN,3624 MILITARY AVE.,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X
83893,jurisW1FEB23.txt,HX,16,10551385,U,MNTHLY-NO CHG,"""BELL,CHARLES F""",NaN,926 DE HARO STREET,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X
101290,jurisW1DEC23.txt,HX,13,10119621,U,MNTHLY-NO CHG,"MOSHFEGH,ANAHITA",NaN,3624 MILITARY AVE.,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X
104387,jurisW1DEC23.txt,HX,16,10551385,U,MNTHLY-NO CHG,"BELL,CHARLES F",NaN,926 DE HARO STREET,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X
120688,jurisW1SEP23.txt,HX,13,10119621,U,MNTHLY-NO CHG,"""MOSHFEGH,ANAHITA""",NaN,3624 MILITARY AVE.,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X
123687,jurisW1SEP23.txt,HX,16,10551385,U,MNTHLY-NO CHG,"""BELL,CHARLES F""",NaN,926 DE HARO STREET,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X
135342,jurisW2MAY23.txt,HX,16,10551385,C,OTHER CHANGE,"BELL,CHARLES F",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X
140424,jurisW1MAY23.txt,HX,13,10119621,U,MNTHLY-NO CHG,"MOSHFEGH,ANAHITA",NaN,3624 MILITARY AVE.,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X
143370,jurisW1MAY23.txt,HX,16,10551385,C,OTHER CHANGE,"BELL,CHARLES F",NaN,926 DE HARO STREET,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X
156874,jurisW1JUN23.txt,HX,13,10119621,U,MNTHLY-NO CHG,"MOSHFEGH,ANAHITA",NaN,3624 MILITARY AVE.,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X
159830,jurisW1JUN23.txt,HX,16,10551385,U,MNTHLY-NO CHG,"BELL,CHARLES F",NaN,926 DE HARO STREET,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X
174519,jurisW1NOV23.txt,HX,13,10119621,U,MNTHLY-NO CHG,"MOSHFEGH,ANAHITA",NaN,3624 MILITARY AVE.,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X
177590,jurisW1NOV23.txt,HX,16,10551385,U,MNTHLY-NO CHG,"BELL,CHARLES F",NaN,926 DE HARO STREET,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X
191186,jurisW2JUL23.txt,HX,13,10119621,C,OTHER CHANGE,"MOSHFEGH,ANAHITA",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X
194138,jurisW2JUL23.txt,HX,16,10551385,C,OTHER CHANGE,"BELL,CHARLES F",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X
204203,jurisW3APR23.txt,HX,16,10551385,C,OTHER CHANGE,"BELL,CHARLES F",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X
218084,jurisW1JAN23.txt,HX,13,10119621,U,MNTHLY-NO CHG,"""MOSHFEGH,ANAHITA""",NaN,3624 MILITARY AVE.,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X
221031,jurisW1JAN23.txt,HX,16,10551385,U,MNTHLY-NO CHG,"""BELL,CHARLES F""",NaN,926 DE HARO STREET,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X
237031,jurisW1AUG23.txt,HX,13,10119621,U,MNTHLY-NO CHG,"MOSHFEGH,ANAHITA",NaN,3624 MILITARY AVE.,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X
240037,jurisW1AUG23.txt,HX,16,10551385,U,MNTHLY-NO CHG,"BELL,CHARLES F",NaN,926 DE HARO STREET,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X

In [9]:
juris_2023_df.columns

Index(['Source File Name', 'Unit', 'Location', 'EE ID', 'Action',
       'Action Type', 'Employee Name', 'Name 2', 'Home Address 1',
       'Home Address 2',
       ...
       'ARC_8', '(Blank)_9', 'Title Code_9', 'Title Name_9',
       'Annualized Pay_9', 'Appt %_9', 'Appt Type_9', 'TUC_9', 'ARC_9', 'X'],
      dtype='object', length=124)

In [31]:
juris_2023_df.dtypes

Source File Name    object
Unit                object
Location             int64
EE ID               object
Action              object
                     ...
Appt %_9            object
Appt Type_9         object
TUC_9               object
ARC_9               object
X                   object
Length: 124, dtype: object

In [29]:
juris_2023_df[juris_2023_df['EE ID']=='10119621']

Empty DataFrame
Columns: [Source File Name, Unit, Location, EE ID, Action, Action Type, Employee Name, Name 2, Home Address 1, Home Address 2, Home City, Home State, Home Zip, Home Discls, Home Phone, Phone Discls, Personal Email, Email Discls, Personal Cell, Cell Discls, Hire Date, Appt Begin Date, Appt End Date, Dept Address, Dept Name, Work Loc Add 1, Work Loc Add 2, Work Loc City, Work Loc State, Work Loc Zip, Zip +4, Work Bldg, Work Flr, Work Room, Work Cube, Work Email, Work Phone, Work Cell, LOA Begin, LOA Return, LOA Code, LOA Discp, START %, START Begin, START End, Separation, Sep Reason, Dues Indicator, Home Dept Code, MC/C, (Blank), # of Titles, Title Code, Title Name, Annualized Pay, Appt %, Appt Type, TUC, ARC, (Blank)_2, Title Code_2, Title Name_2, Annualized Pay_2, Appt %_2, Appt Type_2, TUC_2, ARC_2, (Blank)_3, Title Code_3, Title Name_3, Annualized Pay_3, Appt %_3, Appt Type_3, TUC_3, ARC_3, (Blank)_4, Title Code_4, Title Name_4, Annualized Pay_4, Appt %_4, Appt Type_4, TUC_4, ARC_4, (Blank)_5, Title Code_5, Title Name_5, Annualized Pay_5, Appt %_5, Appt Type_5, TUC_5, ARC_5, (Blank)_6, Title Code_6, Title Name_6, Annualized Pay_6, Appt %_6, Appt Type_6, TUC_6, ARC_6, (Blank)_7, ...]
Index: []

[0 rows x 124 columns]

In [7]:
Healthplan_data_path = "/content/drive/MyDrive/Research/Bargaining Data 2024/Agitational Resources/UPTE RFI 4.12.23. Response to Item No. 20_Medical Benefit Plans(revised) sorted.xlsx"

In [15]:
healthplan_file = pd.ExcelFile(Healthplan_data_path)
tab_names = healthplan_file.sheet_names
tab_names

['Employees wBenefit plan', 'Sheet1', 'Employees -Opted Out', 'Key', 'Sheet2']

In [18]:
# Define the data types for specific columns
dtype_mapping = {
    'Employee ID': str,
    'Union Code': str,
    'Job Code': str
}

# Parse the excel sheet specifying the column data types
healthplan_df = healthplan_file.parse(tab_names[0], dtype=dtype_mapping)

In [37]:
healthplan_df.shape

(16355, 14)

In [39]:
healthplan_df['Employee ID'].nunique()

16203

In [48]:
healthplan_w_location_df = healthplan_df.merge(juris_2023_df[['Location', 'EE ID']], left_on='Employee ID', right_on='EE ID', how='left').drop_duplicates('Employee ID')
healthplan_w_location_df.shape

(16204, 16)

In [45]:
healthplan_w_location_df['Location'].unique()

array(['13', '16', '4', '15', '12', '8', '3', '14', '2', '6', '1', '10',
       '9', '7', '5', '94', '18', '19', nan], dtype=object)

In [47]:
location_dict = {
'1': "BKCMP", '19':'UCOP1', '94': 'LBNL1',
'13': 'LAMED', '4': 'LACMP',
'16': 'SFMED', '2': 'SFCMP',
'15': 'IRMED', '9': 'IRCMP',
'12': 'DVMED', '3': 'DVCMP', '18': "UCANR",
'8': "SBCMP",
'14': 'SDMED', '6': 'SDCMP',
'10': 'MECMP',
'7': 'SCCMP',
'5': 'RVCMP'}

In [42]:
ee_id_list = ['10119621', '10551385']

In [49]:
healthplan_w_location_df['Business Unit'] = healthplan_w_location_df['Location'].map(location_dict)
healthplan_w_location_df.head()

,Effective Date,Employee ID,Employee Name,Union Code,Job Code,Job Code Description,Unnamed: 6,Medical Plan Code,Medical Coverage Code,Medical Plan Name,Age,Actual Current Year MCB Band Description,Medical Insurance Premium Employee Paid,Medical Insurance Premium UC Paid,Location,EE ID,Business Unit
0,2023-04-01,10119621,"Moshfegh,Anahita",HX,007866,AUDIOLOGIST SR EX,AUDIOLOGIST SR EX,CORE,U,CORE,53.583333,"between $129,001 and $194,000",0.0,264.76,13,10119621,LAMED
13,2023-04-01,10551385,"Bell,Charles f",HX,007870,CASE MGR EX,CASE MGR EX,CORE,U,CORE,54.000000,"$194,001 and greater",0.0,264.76,16,10551385,SFMED
28,2023-04-01,10634160,"Huang,Sumian Grace",HX,007870,CASE MGR EX,CASE MGR EX,CORE,U,CORE,52.833333,"between $129,001 and $194,000",0.0,264.76,4,10634160,LACMP
42,2023-04-01,10625280,"Hogan,Dolores Casalme",HX,007870,CASE MGR EX,CASE MGR EX,CORE,U,CORE,52.250000,"between $129,001 and $194,000",0.0,264.76,4,10625280,LACMP
60,2023-04-01,10575753,"Nanao,Jenica",HX,007870,CASE MGR EX,CASE MGR EX,CORE,U,CORE,31.500000,"between $129,001 and $194,000",0.0,264.76,13,10575753,LAMED

In [50]:
healthplan_w_location_df.drop(columns=['EE ID'], inplace=True)

In [52]:
healthplan_w_location_df.to_excel("healthplan_w_location_2023_Apr_unique_EE_ID.xlsx")

In [53]:
healthplan_w_location_df.columns

Index(['Effective Date', 'Employee ID', 'Employee Name', 'Union Code',
       'Job Code', 'Job Code Description', 'Unnamed: 6', 'Medical Plan Code',
       'Medical Coverage Code', 'Medical Plan Name', 'Age',
       'Actual Current Year MCB Band Description',
       'Medical Insurance Premium Employee Paid',
       'Medical Insurance Premium UC Paid', 'Location', 'Business Unit'],
      dtype='object')

In [54]:
healthplan_w_location_df.pivot_table(values='Employee Name', index='Business Unit', aggfunc='count', columns='Medical Plan Name')

Medical Plan Name,CORE,Kaiser,"UC Blue & ""Gold"" HMO",UC Care,UC Health Savings Plan
Business Unit,,,,,
BKCMP,32.0,333.0,70.0,49.0,18.0
DVCMP,58.0,747.0,659.0,83.0,91.0
DVMED,22.0,256.0,435.0,39.0,54.0
IRCMP,33.0,240.0,116.0,68.0,40.0
IRMED,27.0,190.0,124.0,61.0,58.0
LACMP,103.0,617.0,613.0,240.0,102.0
LAMED,47.0,195.0,353.0,192.0,54.0
LBNL1,13.0,139.0,42.0,12.0,5.0
MECMP,4.0,2.0,13.0,4.0,5.0
RVCMP,15.0,94.0,29.0,13.0,5.0
SBCMP,25.0,12.0,124.0,31.0,20.0
SCCMP,7.0,39.0,NaN,35.0,6.0
SDCMP,82.0,613.0,695.0,176.0,157.0
SDMED,17.0,144.0,365.0,42.0,75.0
SFCMP,138.0,932.0,428.0,144.0,107.0
SFMED,57.0,415.0,327.0,112.0,79.0
UCANR,5.0,17.0,10.0,7.0,13.0
UCOP1,NaN,8.0,2.0,2.0,1.0

In [57]:
healthplan_w_location_df['Business Unit'].groupby('Employee Name').value_counts()

KeyError: 'Employee Name'

In [ ]:
juris_2024_df = juris_2024.parse("2024_combined_juris_Jan-Jul")

In [ ]:
ucla_2024_juris = juris_2024_df[juris_2024_df['Location']==4]

In [ ]:
ucla_2024_juris.to_excel("ucla_2024_juris.xlsx")

In [ ]:
juris_2024_df.head()

,Source File Name,Unit,Location,EE ID,Action,Action Type,Employee Name,Name 2,Home Address 1,Home Address 2,...,ARC_8,(Blank)_9,Title Code_9,Title Name_9,Annualized Pay_9,Appt %_9,Appt Type_9,TUC_9,ARC_9,X
0,jurisW2JUN24.txt,HX,1,10147383,C,OTHER CHANGE,"CAPONE,DON-ANTHONY L",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X
1,jurisW2JUN24.txt,HX,1,10147732,C,OTHER CHANGE,"BLUM,SASHA A",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X
2,jurisW2JUN24.txt,HX,1,10148267,C,OTHER CHANGE,"LUM,KWUN CHEUNG",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X
3,jurisW2JUN24.txt,HX,1,10148727,C,OTHER CHANGE,"LIN,TIFFANY H",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X
4,jurisW2JUN24.txt,HX,1,10150184,C,OTHER CHANGE,"LEE TSUGAWA,KAREN M",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X