<a href="https://colab.research.google.com/github/tougheye/Data_processing/blob/main/TCS_payrate_comparison.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

upte_jan_df = pd.read_excel("/content/UPTE_Job_Summary_Represented_JobCode_01132026.xlsx")
upte_jan_df.shape
# (44017, 30)

(44017, 30)

In [ ]:
upte_jan_df.columns

Index(['Salary Plan SETID', 'Status - Job Code', 'Job Code',
       'Job Code Description', 'Eff Date - Salary Grade',
       'Salary Grade Eff Status', 'Union Code', 'FLSA Status',
       'Personnel Program/CLASS_INDC', 'OnCall Eligible', 'Elig Shift Diff',
       'Sal Plan', 'Sal Plan Description', 'Grade', 'Rate Code', 'Comp Freq',
       'UCPATH Step', 'UC  Half Step', 'Hrly Rate', 'Monthly Rt', 'Annual Rt',
       'CTO/OS Subgroup', 'CTO Description', 'SOC Code',
       'SOC Code Description', 'Census/OCC Code',
       'Census/OCC Code Description', 'EEO1 Reporting Code',
       'EEO1 Reporting Cod Description', 'OSHPD Code'],
      dtype='object')

In [ ]:
upte_mar_df = pd.read_excel("/content/UPTE_Job_Summary_Represented_JobCode_032026.xlsx", sheet_name='Represented Job Codes')
upte_mar_df.shape
# (46098, 30)

(46098, 30)

In [ ]:
upte_merged_df = upte_mar_df.merge(upte_jan_df[['Salary Plan SETID','Job Code','UCPATH Step', 'Sal Plan', 'Sal Plan Description','Grade', 'UC  Half Step','Hrly Rate', 'Monthly Rt', 'Annual Rt']],
                  on=['Salary Plan SETID','Job Code','UCPATH Step', 'Grade','UC  Half Step', 'Sal Plan', 'Sal Plan Description'],suffixes=('_mar', '_jan'), how='left')
upte_merged_df.shape

(46098, 33)

In [ ]:
upte_merged_df.columns

Index(['Salary Plan SETID', 'Status - Job Code', 'Job Code',
       'Job Code Description', 'Eff Date - Salary Grade',
       'Salary Grade Eff Status', 'Union Code', 'FLSA Status',
       'Personnel Program/CLASS_INDC', 'OnCall Eligible', 'Elig Shift Diff',
       'Sal Plan', 'Sal Plan Description', 'Grade', 'Rate Code', 'Comp Freq',
       'UCPATH Step', 'UC  Half Step', 'Hrly Rate_mar', 'Monthly Rt_mar',
       'Annual Rt_mar', 'CTO/OS Subgroup', 'CTO Description', 'SOC Code',
       'SOC Code Description', 'Census/OCC Code',
       'Census/OCC Code Description', 'EEO1 Reporting Code',
       'EEO1 Reporting Cod Description', 'OSHPD Code', 'Hrly Rate_jan',
       'Monthly Rt_jan', 'Annual Rt_jan'],
      dtype='object')

In [ ]:
cols_to_keep = ['Salary Plan SETID', 'Job Code','Job Code Description', 'UCPATH Step', 'UC  Half Step',
                'Hrly Rate_mar', 'Monthly Rt_mar','Annual Rt_mar', 'Hrly Rate_jan','Monthly Rt_jan',
                'Annual Rt_jan', 'Grade', 'Sal Plan', 'Sal Plan Description']

In [ ]:
upte_merged_df[cols_to_keep][upte_merged_df[cols_to_keep].duplicated()==True].sort_values(by=['Salary Plan SETID','Job Code','UCPATH Step', 'UC  Half Step'])

,Salary Plan SETID,Job Code,Job Code Description,UCPATH Step,UC Half Step,Hrly Rate_mar,Monthly Rt_mar,Annual Rt_mar,Hrly Rate_jan,Monthly Rt_jan,Annual Rt_jan,Grade
17648,LBNL1,381.1,Research Assoc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T80
17649,LBNL1,381.1,Research Assoc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T80
17650,LBNL1,381.1,Research Assoc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T80
17652,LBNL1,381.2,Research Assoc Sr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T83
17653,LBNL1,381.2,Research Assoc Sr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T83
...,...,...,...,...,...,...,...,...,...,...,...,...
52666,UCANR,9724.0,MUSEUM SCI AST,9.0,9.0,27.58,4798.92,57587.04,27.58,4798.92,57587.04,112
52667,UCANR,9724.0,MUSEUM SCI AST,9.0,9.0,27.58,4798.92,57587.04,27.58,4798.92,57587.04,112
52686,UCANR,9724.0,MUSEUM SCI AST,9.0,9.0,27.74,4826.76,57921.12,27.74,4826.76,57921.12,110
52687,UCANR,9724.0,MUSEUM SCI AST,9.0,9.0,27.74,4826.76,57921.12,27.74,4826.76,57921.12,110
52688,UCANR,9724.0,MUSEUM SCI AST,9.0,9.0,27.74,4826.76,57921.12,27.74,4826.76,57921.12,110

In [ ]:
upte_merged_df[(upte_merged_df['Salary Plan SETID'] == 'UCANR') & (upte_merged_df['Job Code'] == 4031.0)]

,Salary Plan SETID,Status - Job Code,Job Code,Job Code Description,Eff Date - Salary Grade,Salary Grade Eff Status,Union Code,FLSA Status,Personnel Program/CLASS_INDC,OnCall Eligible,...,SOC Code,SOC Code Description,Census/OCC Code,Census/OCC Code Description,EEO1 Reporting Code,EEO1 Reporting Cod Description,OSHPD Code,Hrly Rate_jan,Monthly Rt_jan,Annual Rt_jan
37527,UCANR,A,4031.0,LIFEGUARD,2020-07-12,I,TX,N,1,Y,...,33-9092,"Lifeguards And Other Recreational, And All Oth...",3960,Other Protective Service Workers,9,Service Workers,01,15.68,2728.32,32739.84
37528,UCANR,A,4031.0,LIFEGUARD,2020-07-12,I,TX,N,1,Y,...,33-9092,"Lifeguards And Other Recreational, And All Oth...",3960,Other Protective Service Workers,9,Service Workers,01,15.68,2728.32,32739.84
37529,UCANR,A,4031.0,LIFEGUARD,2020-07-12,I,TX,N,1,Y,...,33-9092,"Lifeguards And Other Recreational, And All Oth...",3960,Other Protective Service Workers,9,Service Workers,01,15.61,2716.14,32593.68
37530,UCANR,A,4031.0,LIFEGUARD,2020-07-12,I,TX,N,1,Y,...,33-9092,"Lifeguards And Other Recreational, And All Oth...",3960,Other Protective Service Workers,9,Service Workers,01,15.61,2716.14,32593.68
37531,UCANR,A,4031.0,LIFEGUARD,2020-07-12,I,TX,N,1,Y,...,33-9092,"Lifeguards And Other Recreational, And All Oth...",3960,Other Protective Service Workers,9,Service Workers,01,17.62,3065.88,36790.56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37791,UCANR,A,4031.0,LIFEGUARD,2020-07-12,I,TX,N,1,Y,...,33-9092,"Lifeguards And Other Recreational, And All Oth...",3960,Other Protective Service Workers,9,Service Workers,01,17.64,3069.36,36832.32
37792,UCANR,A,4031.0,LIFEGUARD,2020-07-12,I,TX,N,1,Y,...,33-9092,"Lifeguards And Other Recreational, And All Oth...",3960,Other Protective Service Workers,9,Service Workers,01,17.64,3069.36,36832.32
37793,UCANR,A,4031.0,LIFEGUARD,2020-07-12,I,TX,N,1,Y,...,33-9092,"Lifeguards And Other Recreational, And All Oth...",3960,Other Protective Service Workers,9,Service Workers,01,19.93,3467.82,41613.84
37794,UCANR,A,4031.0,LIFEGUARD,2020-07-12,I,TX,N,1,Y,...,33-9092,"Lifeguards And Other Recreational, And All Oth...",3960,Other Protective Service Workers,9,Service Workers,01,17.74,3086.76,37041.12
37795,UCANR,A,4031.0,LIFEGUARD,2020-07-12,I,TX,N,1,Y,...,33-9092,"Lifeguards And Other Recreational, And All Oth...",3960,Other Protective Service Workers,9,Service Workers,01,17.74,3086.76,37041.12

Warning: Total number of columns (33) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
upte_merged_df.sort_values(by=['Salary Plan SETID','Job Code','UCPATH Step', 'UC  Half Step'],inplace=True)
upte_merged_df[['Salary Plan SETID', 'Job Code',
       'Job Code Description', 'UCPATH Step', 'UC  Half Step', 'Hrly Rate_mar', 'Monthly Rt_mar',
       'Annual Rt_mar', 'Hrly Rate_jan',
       'Monthly Rt_jan', 'Annual Rt_jan']].head(100)

,Salary Plan SETID,Job Code,Job Code Description,UCPATH Step,UC Half Step,Hrly Rate_mar,Monthly Rt_mar,Annual Rt_mar,Hrly Rate_jan,Monthly Rt_jan,Annual Rt_jan
7,BKCMP,4031.0,LIFEGUARD,1.0,1.0,25.75,4480.50,53766.00,20.54,3573.96,42887.52
6,BKCMP,4031.0,LIFEGUARD,2.0,1.5,26.27,4570.98,54851.76,20.97,3648.78,43785.36
4,BKCMP,4031.0,LIFEGUARD,3.0,2.0,26.79,4661.46,55937.52,21.38,3720.12,44641.44
8,BKCMP,4031.0,LIFEGUARD,4.0,2.5,27.33,4755.42,57065.04,21.80,3793.20,45518.40
0,BKCMP,4031.0,LIFEGUARD,5.0,3.0,27.87,4849.38,58192.56,22.25,3871.50,46458.00
...,...,...,...,...,...,...,...,...,...,...,...
95,BKCMP,4497.0,MUSEUM EDUCATOR 1 TX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,BKCMP,4498.0,MUSEUM EDUCATOR 2 TX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,BKCMP,4499.0,MUSEUM EDUCATOR 3 TX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,BKCMP,4505.0,EDUC TCHL SPEC 3 TX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,BKCMP,4506.0,EDUC TCHL SPEC 4 TX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
upte_merged_df.columns

Index(['Salary Plan SETID', 'Status - Job Code', 'Job Code',
       'Job Code Description', 'Eff Date - Salary Grade',
       'Salary Grade Eff Status', 'Union Code', 'FLSA Status',
       'Personnel Program/CLASS_INDC', 'OnCall Eligible', 'Elig Shift Diff',
       'Sal Plan', 'Sal Plan Description', 'Grade', 'Rate Code', 'Comp Freq',
       'UCPATH Step', 'UC  Half Step', 'Hrly Rate_mar', 'Monthly Rt_mar',
       'Annual Rt_mar', 'CTO/OS Subgroup', 'CTO Description', 'SOC Code',
       'SOC Code Description', 'Census/OCC Code',
       'Census/OCC Code Description', 'EEO1 Reporting Code',
       'EEO1 Reporting Cod Description', 'OSHPD Code', 'Hrly Rate_jan',
       'Monthly Rt_jan', 'Annual Rt_jan'],
      dtype='object')

In [ ]:
final_comparison_df = upte_merged_df[cols_to_keep]

In [ ]:
final_comparison_df['Hrly_Inc%'] = (final_comparison_df['Hrly Rate_mar']-final_comparison_df['Hrly Rate_jan'])\
                                    /final_comparison_df['Hrly Rate_jan']
final_comparison_df['Monthly_Inc%'] = (final_comparison_df['Monthly Rt_mar']-final_comparison_df['Monthly Rt_jan'])\
                                    /final_comparison_df['Monthly Rt_jan']
final_comparison_df['Annual_Inc%'] = (final_comparison_df['Annual Rt_mar']-final_comparison_df['Annual Rt_jan'])\
                                    /final_comparison_df['Annual Rt_jan']
final_comparison_df.head(25)

/tmp/ipykernel_1101/1555968869.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_comparison_df['Hrly_Inc%'] = (final_comparison_df['Hrly Rate_mar']-final_comparison_df['Hrly Rate_jan'])\
/tmp/ipykernel_1101/1555968869.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_comparison_df['Monthly_Inc%'] = (final_comparison_df['Monthly Rt_mar']-final_comparison_df['Monthly Rt_jan'])\
/tmp/ipykernel_1101/1555968869.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_comparison_df['Annual_Inc%'] = (final_comparison_df['Annual Rt_mar']-final_comparison_df['Annual Rt_jan'])\

,Salary Plan SETID,Job Code,Job Code Description,UCPATH Step,UC Half Step,Hrly Rate_mar,Monthly Rt_mar,Annual Rt_mar,Hrly Rate_jan,Monthly Rt_jan,Annual Rt_jan,Grade,Sal Plan,Sal Plan Description,Hrly_Inc%,Monthly_Inc%,Annual_Inc%
0,BKCMP,4031.0,LIFEGUARD,5.0,3.0,27.870000,4849.380,58192.56,22.250000,3871.500,46458.00,100,UCTX,TX Salary Plan,0.252584,0.252584,0.252584
1,BKCMP,4031.0,LIFEGUARD,6.0,3.5,28.430000,4946.820,59361.84,22.680000,3946.320,47355.84,100,UCTX,TX Salary Plan,0.253527,0.253527,0.253527
2,BKCMP,4031.0,LIFEGUARD,8.0,4.5,29.580000,5146.920,61763.04,23.590000,4104.660,49255.92,100,UCTX,TX Salary Plan,0.253921,0.253921,0.253921
3,BKCMP,4031.0,LIFEGUARD,9.0,5.0,30.170000,5249.580,62994.96,24.080000,4189.920,50279.04,100,UCTX,TX Salary Plan,0.252907,0.252907,0.252907
4,BKCMP,4031.0,LIFEGUARD,3.0,2.0,26.790000,4661.460,55937.52,21.380000,3720.120,44641.44,100,UCTX,TX Salary Plan,0.253040,0.253040,0.253040
5,BKCMP,4031.0,LIFEGUARD,7.0,4.0,28.990000,5044.260,60531.12,23.130000,4024.620,48295.44,100,UCTX,TX Salary Plan,0.253351,0.253351,0.253351
6,BKCMP,4031.0,LIFEGUARD,2.0,1.5,26.270000,4570.980,54851.76,20.970000,3648.780,43785.36,100,UCTX,TX Salary Plan,0.252742,0.252742,0.252742
7,BKCMP,4031.0,LIFEGUARD,1.0,1.0,25.750000,4480.500,53766.00,20.540000,3573.960,42887.52,100,UCTX,TX Salary Plan,0.253651,0.253651,0.253651
8,BKCMP,4031.0,LIFEGUARD,4.0,2.5,27.330000,4755.420,57065.04,21.800000,3793.200,45518.40,100,UCTX,TX Salary Plan,0.253670,0.253670,0.253670
9,BKCMP,4218.0,MUSEUM PREPARATOR PRN PD,1.0,1.0,37.190000,6471.060,77652.72,36.110000,6283.140,75397.68,213,UCTX,TX Salary Plan,0.029909,0.029909,0.029909
10,BKCMP,4312.0,REHAB SVC SPEC 4 HX,12.0,12.0,85.264200,14835.971,178031.65,84.420000,14689.080,176268.96,125,UCHX,HX Salary Plan,0.010000,0.010000,0.010000
11,BKCMP,4312.0,REHAB SVC SPEC 4 HX,8.0,8.0,78.773937,13706.665,164479.98,77.993999,13570.956,162851.47,125,UCHX,HX Salary Plan,0.010000,0.010000,0.010000
12,BKCMP,4312.0,REHAB SVC SPEC 4 HX,6.0,6.0,75.719698,13175.228,158102.73,74.970000,13044.780,156537.36,125,UCHX,HX Salary Plan,0.010000,0.010000,0.010000
13,BKCMP,4312.0,REHAB SVC SPEC 4 HX,5.0,5.0,74.235000,12916.890,155002.68,73.500000,12789.000,153468.00,125,UCHX,HX Salary Plan,0.010000,0.010000,0.010000
14,BKCMP,4312.0,REHAB SVC SPEC 4 HX,14.0,14.0,88.721427,15437.528,185250.34,87.842998,15284.682,183416.18,125,UCHX,HX Salary Plan,0.010000,0.010000,0.010000
15,BKCMP,4312.0,REHAB SVC SPEC 4 HX,13.0,13.0,86.971604,15133.059,181596.71,86.110498,14983.227,179798.72,125,UCHX,HX Salary Plan,0.010000,0.010000,0.010000
16,BKCMP,4312.0,REHAB SVC SPEC 4 HX,7.0,7.0,77.236212,13439.101,161269.21,76.471499,13306.041,159672.49,125,UCHX,HX Salary Plan,0.010000,0.010000,0.010000
17,BKCMP,4312.0,REHAB SVC SPEC 4 HX,10.0,10.0,81.966049,14262.093,171145.11,81.154502,14120.883,169450.60,125,UCHX,HX Salary Plan,0.010000,0.010000,0.010000
18,BKCMP,4312.0,REHAB SVC SPEC 4 HX,1.0,1.0,68.582538,11933.362,143200.34,67.903501,11815.209,141782.51,125,UCHX,HX Salary Plan,0.010000,0.010000,0.010000
19,BKCMP,4312.0,REHAB SVC SPEC 4 HX,9.0,9.0,80.354085,13981.611,167779.33,79.558501,13843.179,166118.15,125,UCHX,HX Salary Plan,0.010000,0.010000,0.010000
20,BKCMP,4312.0,REHAB SVC SPEC 4 HX,15.0,15.0,90.471255,15741.998,188903.98,89.575498,15586.137,187033.64,125,UCHX,HX Salary Plan,0.010000,0.010000,0.010000
21,BKCMP,4312.0,REHAB SVC SPEC 4 HX,11.0,11.0,83.599215,14546.263,174555.16,82.771499,14402.241,172826.89,125,UCHX,HX Salary Plan,0.010000,0.010000,0.010000
22,BKCMP,4312.0,REHAB SVC SPEC 4 HX,16.0,16.0,92.284713,16057.540,192690.48,91.371001,15898.554,190782.65,125,UCHX,HX Salary Plan,0.010000,0.010000,0.010000
23,BKCMP,4312.0,REHAB SVC SPEC 4 HX,2.0,2.0,69.950580,12171.401,146056.81,69.257998,12050.892,144610.70,125,UCHX,HX Salary Plan,0.010000,0.010000,0.010000
24,BKCMP,4312.0,REHAB SVC SPEC 4 HX,3.0,3.0,71.350441,12414.977,148979.72,70.643999,12292.056,147504.67,125,UCHX,HX Salary Plan,0.010000,0.010000,0.010000

In [ ]:
final_comparison_df.head()

,Salary Plan SETID,Job Code,Job Code Description,UCPATH Step,UC Half Step,Hrly Rate_mar,Monthly Rt_mar,Annual Rt_mar,Hrly Rate_jan,Monthly Rt_jan,Annual Rt_jan,Grade,Sal Plan,Sal Plan Description,Hrly_Inc%,Monthly_Inc%,Annual_Inc%
0,BKCMP,4031.0,LIFEGUARD,5.0,3.0,27.87,4849.38,58192.56,22.25,3871.50,46458.00,100,UCTX,TX Salary Plan,0.252584,0.252584,0.252584
1,BKCMP,4031.0,LIFEGUARD,6.0,3.5,28.43,4946.82,59361.84,22.68,3946.32,47355.84,100,UCTX,TX Salary Plan,0.253527,0.253527,0.253527
2,BKCMP,4031.0,LIFEGUARD,8.0,4.5,29.58,5146.92,61763.04,23.59,4104.66,49255.92,100,UCTX,TX Salary Plan,0.253921,0.253921,0.253921
3,BKCMP,4031.0,LIFEGUARD,9.0,5.0,30.17,5249.58,62994.96,24.08,4189.92,50279.04,100,UCTX,TX Salary Plan,0.252907,0.252907,0.252907
4,BKCMP,4031.0,LIFEGUARD,3.0,2.0,26.79,4661.46,55937.52,21.38,3720.12,44641.44,100,UCTX,TX Salary Plan,0.253040,0.253040,0.253040

In [ ]:
final_comparison_df.to_excel('upte_payrate_comp.xlsx')