<a href="https://colab.research.google.com/github/tougheye/Data_processing/blob/main/TCS_Job_Code_summary_review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
job_code_review_df = pd.read_csv("/content/Job Code Summary_1.13.26_review.csv")
job_code_review_df.tail()

,Salary Plan SETID,Jobcode SETID,Job Code,Eff Date,Salary Grade Eff Status,Descr,Short Descr,Job Function,Sal Admin Plan,Grade,...,Last Update,Last Updated by,Last Updated Date Time,Key Job Code,CTO/OS Subgroup,Sys/Local Ind,OnCall Eligible,Elig Shift Diff,Classified,OSHPD Code
63747,UCSHR,LBNL1,CONV,01/01/1950,I,LBNL Default,CONV,,T021,1,...,06/03/2020,10002570,06/03/2020 9:15:44 AM,N,LBL,L,N,N,C,
63748,UCSHR,UCSHR,CONV,07/01/2022,I,CONVERSION JOB CODE,CONV,,T021,3,...,08/13/2014,10291160,07/05/2022 6:57:08 PM,N,TST,S,N,N,1,09
63749,UCSHR,LBNL1,CONV,01/01/1950,I,LBNL Default,CONV,,T009,4,...,06/03/2020,10002570,06/03/2020 9:15:44 AM,N,LBL,L,N,N,C,
63750,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63751,1/13/26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# drop the last 2 rows since they are not part of the data
drop_row_index = [ 63750, 63751]
job_code_review_clean_df = job_code_review_df.drop(drop_row_index)
# job_code_review_clean_df.tail()
job_code_review_clean_df.shape

(63750, 48)

In [ ]:
job_code_review_clean_df.columns

Index(['Salary Plan SETID', 'Jobcode SETID', 'Job Code', 'Eff Date',
       'Salary Grade Eff Status', 'Descr', 'Short Descr', 'Job Function',
       'Sal Admin Plan', 'Grade', 'Step', 'Manager Level', 'Survey Salary',
       'Union Code', 'Retro Rate', 'Retro Percent', 'Currency', 'Stnd Hrs/Wk',
       'Work Period', 'Comp Frequency', 'Job Family', 'Reg/Temp', 'Tipped',
       'Med Checkup', 'FLSA Status', 'EEO-1 Cat', 'EEO-4 Cat', 'EEO-5 Cat',
       'EEO-6 Cat', 'SOC', 'IPEDSS Code', 'OCC', 'Telework', 'Company',
       'Encmb Indc', 'Posn Mgmt?', 'Enc Sal Optn', 'Enc Sal Amt',
       'Last Update ', 'Last Updated by', 'Last Updated Date Time',
       'Key Job Code', 'CTO/OS Subgroup', 'Sys/Local Ind', 'OnCall Eligible',
       'Elig Shift Diff', 'Classified', 'OSHPD Code'],
      dtype='object')

In [ ]:
job_code_review_clean_df.groupby('CTO/OS Subgroup')['Short Descr'].nunique().to_frame()

                 Short Descr
CTO/OS Subgroup
010                       11
011                        7
012                        2
016                        1
030                        1
...                      ...
S46                        1
S56                        3
TST                        2
Z20                        2
Z25                        2

[100 rows x 1 columns]

In [ ]:
job_code_review_clean_df['Short Descr'].value_counts()

Short Descr
ASSOC PROF    2062
ASST PROF     1547
ACT ASSOC     1107
ACT ASST P     992
PROF OF TE     687
              ...
INV RISK D       1
PUBL EQU         1
INV RISK M       1
ASSET ALLO       1
AVP STRAT        1
Name: count, Length: 3491, dtype: int64

In [ ]:
from numpy import astype
CTO_vs_BU_short_desc_crosstab = job_code_review_clean_df.pivot_table(values='Short Descr', index='CTO/OS Subgroup', columns= 'Union Code',
                                     aggfunc='nunique', fill_value=0, margins=True).astype(int)
CTO_vs_BU_short_desc_crosstab

Union Code,,87,99,9C,9F,9J,9K,9N,9U,A%,...,UH,UL,WC,WE,WH,WK,WN,WS,WT,All
CTO/OS Subgroup,,,,,,,,,,,,,,,,,,,,,
010,0,0,2,0,0,0,0,0,0,9,...,0,0,0,0,0,0,0,0,0,11
011,0,0,3,0,0,0,0,0,0,4,...,0,0,0,0,0,0,0,0,0,7
012,0,0,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
016,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
030,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
S56,0,0,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3
TST,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
Z20,0,0,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
Z25,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
All,3,2,1943,17,80,25,2,31,2,26,...,2,1,12,40,14,1,12,6,1,3491

In [ ]:
CTO_vs_BU_short_desc_crosstab.to_csv('CTO_vs_BU_short_desc_crosstab.csv')

In [ ]:
# cross tab to calculate row percentages
CTO_vs_BU_short_desc_crosstab_row_pct = CTO_vs_BU_short_desc_crosstab.div(CTO_vs_BU_short_desc_crosstab.sum(axis=1), axis=0) * 100
CTO_vs_BU_short_desc_crosstab_row_pct_rounded = CTO_vs_BU_short_desc_crosstab_row_pct.round(2)
CTO_vs_BU_short_desc_crosstab_row_pct_rounded

Union Code,,87,99,9C,9F,9J,9K,9N,9U,A%,...,UF,UH,UL,WC,WE,WH,WK,WN,WS,WT
CTO/OS Subgroup,,,,,,,,,,,,,,,,,,,,,
010,0.0,0.0,18.18,0.0,0.0,0.0,0.0,0.0,0.0,81.82,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
011,0.0,0.0,42.86,0.0,0.0,0.0,0.0,0.0,0.0,57.14,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
012,0.0,0.0,100.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
016,0.0,0.0,100.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
030,0.0,0.0,100.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
S46,0.0,0.0,100.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
S56,0.0,0.0,100.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TST,50.0,0.0,50.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Z20,0.0,0.0,100.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Z25,0.0,0.0,50.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
CTO_vs_BU_short_desc_crosstab_row_pct_rounded.to_csv('CTO_vs_BU_short_desc_crosstab_row_pct_rounded.csv')
#

In [ ]:
CTO_vs_Short_desc_crosstb = pd.crosstab(index=job_code_review_clean_df['Short Descr'], columns=job_code_review_clean_df['CTO/OS Subgroup'], values= job_code_review_clean_df['Jobcode SETID'],margins=True, aggfunc='nunique')

In [ ]:
CTO_vs_Short_desc_crosstb

CTO/OS Subgroup,010,011,012,016,030,040,114,124,210,211,...,M20,S21,S24,S31,S46,S56,TST,Z20,Z25,All
Short Descr,,,,,,,,,,,,,,,,,,,,,
079.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
197.3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
197.3J,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
197.3S,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
198.4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Z40.5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
ZONE LD,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
ZONE MECH,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
conv,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,214,0,0,214
All,1090,917,2,1,3,32,896,528,1293,640,...,40,41,39,17,192,229,428,14,22,63750

In [ ]:
CTO_vs_Short_desc_crosstb.to_csv('CTO_vs_Short_desc_crosstb.csv')

In [ ]:
# target_CTO = ['D10','D15','E10','H65', 'H85','I10','I20','I25','H80','E20','F10']

target_CTO = ["A10", "A15", "B15", "C10", "D10", "D15", "E10", "E20", "F10", "F20", "G15", "G45",
"H15", "H20", "H35", "H40", "H45", "H50", "H65", "H80", "H85", "I10", "I20", "I25", "LBL"]

upload the Non-represented job codes tab to summarize the 99 targets

In [ ]:
import pandas as pd
job_codes_99_df = pd.read_csv("/content/Job Code Summary_1.13.26_non_represented_codes.csv")
job_codes_99_df.shape

(23614, 33)

In [ ]:
job_codes_99_df.columns

Index(['Salary Plan SETID', 'Status - Job Code', 'Job Code',
       'Job Code Description', 'Eff Date - Salary Grade',
       'Salary Grade Eff Status', 'Union Code', 'FLSA Status',
       'Personnel Program/CLASS_INDC', 'Elig Shift Diff', 'OnCall Eligible',
       'Sal Plan', 'Sal Plan Description', 'Grade', 'Comp Freq', 'Min/Hour',
       'Midpt/Hour', 'Max/Hour', 'Min/Month', 'Midpt/Month', 'Max/Month',
       'Min/Annual', 'Midpt/Annual', 'Max/Annual', 'CTO/OS Subgroup',
       'CTO Description', 'SOC Code', 'SOC Code Description',
       'Census/OCC Code', 'Census/OCC Code Description', 'EEO1 Reporting Code',
       'EEO1 Reporting Cod Description', 'OSHPD Code'],
      dtype='object')

In [ ]:
job_codes_99_df.tail()

,Salary Plan SETID,Status - Job Code,Job Code,Job Code Description,Eff Date - Salary Grade,Salary Grade Eff Status,Union Code,FLSA Status,Personnel Program/CLASS_INDC,Elig Shift Diff,...,Max/Annual,CTO/OS Subgroup,CTO Description,SOC Code,SOC Code Description,Census/OCC Code,Census/OCC Code Description,EEO1 Reporting Code,EEO1 Reporting Cod Description,OSHPD Code
23609,UCSHR,A,CONV,LBNL Default,01/01/1910,I,99,N,C,N,...,"21,516",LBL,LBNL,,,,NaN,N,No EEO-1 Reporting,
23610,UCSHR,A,CONV,LBNL Default,01/01/1910,I,99,N,C,N,...,"18,636",LBL,LBNL,,,,NaN,N,No EEO-1 Reporting,
23611,UCSHR,A,CONV,LBNL Default,07/01/2018,I,99,N,C,N,...,0,LBL,LBNL,,,,NaN,N,No EEO-1 Reporting,
23612,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23613,1/13/26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
drop_row_index = [ 23613, 23612]
job_codes_99_clean_df = job_codes_99_df.drop(drop_row_index)

In [ ]:
job_codes_99_clean_df.tail()

,Salary Plan SETID,Status - Job Code,Job Code,Job Code Description,Eff Date - Salary Grade,Salary Grade Eff Status,Union Code,FLSA Status,Personnel Program/CLASS_INDC,Elig Shift Diff,...,Max/Annual,CTO/OS Subgroup,CTO Description,SOC Code,SOC Code Description,Census/OCC Code,Census/OCC Code Description,EEO1 Reporting Code,EEO1 Reporting Cod Description,OSHPD Code
23607,UCSHR,A,CONV,LBNL Default,10/01/2020,I,99,N,C,N,...,0,LBL,LBNL,,,,NaN,N,No EEO-1 Reporting,
23608,UCSHR,A,CONV,LBNL Default,10/01/2020,I,99,N,C,N,...,0,LBL,LBNL,,,,NaN,N,No EEO-1 Reporting,
23609,UCSHR,A,CONV,LBNL Default,01/01/1910,I,99,N,C,N,...,"21,516",LBL,LBNL,,,,NaN,N,No EEO-1 Reporting,
23610,UCSHR,A,CONV,LBNL Default,01/01/1910,I,99,N,C,N,...,"18,636",LBL,LBNL,,,,NaN,N,No EEO-1 Reporting,
23611,UCSHR,A,CONV,LBNL Default,07/01/2018,I,99,N,C,N,...,0,LBL,LBNL,,,,NaN,N,No EEO-1 Reporting,

In [ ]:
# Get unique job codes & titles with necessary details
non_repr_code_details = job_codes_99_clean_df.groupby(['CTO/OS Subgroup',
       'CTO Description','Job Code','Job Code Description',  'Census/OCC Code',
       'Census/OCC Code Description','EEO1 Reporting Code',
       'EEO1 Reporting Cod Description']).size().reset_index(name='count')
non_repr_code_details.shape

(2155, 9)

In [ ]:
CTOs_outside_UPTE =['426', '436','456','577','621', '627', 'A20', 'A25', 'A30', 'A35', 'B30', 'Z25',
'C15', 'C25', 'F15', 'F25', 'F30', 'F35', 'F40', 'F45', 'G25', 'G35', 'G55', 'G65',
'G75', 'H10', 'I15', 'J10', 'J15', 'M05', 'M10', 'M20', 'S31', 'S56', 'TST', 'Z20']

In [ ]:
non_repr_code_w_short_des = non_repr_code_details.merge(job_code_review_clean_df[['Job Code', 'Short Descr']].drop_duplicates(), on='Job Code', how='left')

In [ ]:
target_99_titles_TCS = non_repr_code_w_short_des[non_repr_code_w_short_des['CTO/OS Subgroup'].isin(target_CTO)].reset_index(drop=True)
target_99_titles_TCS.shape

(938, 10)

In [ ]:
target_99_titles_TCS.to_excel('target_99_titles_TCS.xlsx', index=False)

In [ ]:
non_repr_code_w_short_des.shape

(2155, 10)

In [ ]:
non_repr_code_w_short_des['Job Code'] = non_repr_code_w_short_des['Job Code'].astype(str).str.zfill(5)
non_repr_code_w_short_des['Census/OCC Code'] = non_repr_code_w_short_des['Census/OCC Code'].astype(str).str.zfill(6)
non_repr_code_w_short_des['EEO1 Reporting Code'] = non_repr_code_w_short_des['EEO1 Reporting Code'].astype(str).str.zfill(3)

non_repr_code_w_short_des.to_excel('non_repr_code_w_short_des.xlsx', index=False)

In [ ]:
Out_of_UPTE_titles_TCS = non_repr_code_w_short_des[non_repr_code_w_short_des['CTO/OS Subgroup'].isin(CTOs_outside_UPTE)].reset_index(drop=True)
Out_of_UPTE_titles_TCS.shape

(1217, 10)

In [ ]:
Out_of_UPTE_titles_TCS.to_excel('Out_of_UPTE_titles_TCS.xlsx', index=False)

In [ ]:
target_99_titles_TCS

,Job Code,Job Code Description,CTO/OS Subgroup,CTO Description,Census/OCC Code,Census/OCC Code Description,EEO1 Reporting Code,EEO1 Reporting Cod Description,count,Short Descr
0,000266,SUSTAIN OFCR 4,E10,ARCHITECTURE & PLANNING,000750,"Business Operations Specialists, All Other",002,Professionals,17,SUSTAIN OF
1,000296,EHS SUPV 2,E10,ARCHITECTURE & PLANNING,001980,Occupational Health and Safety Specialists and...,003,Technicians,22,EHS SUPV 2
2,000343,DESIGN AND CONST MGT SPEC 5,E10,ARCHITECTURE & PLANNING,000710,Management Analysts,002,Professionals,13,DESIGN AND
3,000346,AEROSPACE ENGR 4,E20,ENGINEERING,001320,Aerospace Engineers,002,Professionals,5,AEROSPACE
4,000347,AEROSPACE ENGR 5,E20,ENGINEERING,001320,Aerospace Engineers,002,Professionals,4,AEROSPACE
...,...,...,...,...,...,...,...,...,...,...
368,009547,CLIN RSCH SUPV 2,I20,LABORATORY AND RESEARCH SUPPORT,001650,Medical scientists,002,Professionals,10,CLIN RSCH
369,009548,CLIN RSCH SUPV 1,I20,LABORATORY AND RESEARCH SUPPORT,001650,Medical scientists,002,Professionals,9,CLIN RSCH
370,009549,CLIN RSCH ANL 4,I20,LABORATORY AND RESEARCH SUPPORT,001650,Medical scientists,002,Professionals,11,CLIN RSCH
371,009551,BOTANICAL GARDEN ARBOR MGR SR,I20,LABORATORY AND RESEARCH SUPPORT,000205,"Farmers, Ranchers, And Other Agricultural Mana...",00B,First/Mid Level Officials,2,BOTANICAL
372,009980,PROGR ANL 2 SOD,F10,INFORMATION TECHNOLOGY SERVICES,001005,Computer and Information Research Scientists,002,Professionals,1,PROGR ANL

In [ ]:
target_99_titles_TCS.to_excel('target_99_titles_TCS.xlsx', index=False)