<a href="https://colab.research.google.com/github/tougheye/Data_processing/blob/main/TX_mapping_99.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

full_99_list = pd.read_excel('/content/drive/MyDrive/UPTE-26-019_99 List_April 2026 (2) (2).xlsx', sheet_name="Report Page")
full_99_list.head()

,UPTE Title,Location/Business Unit,Employee Lived Name,Job Code,Job Code Description,Most Recent Date of Hire in Empl Rcd,Job Expected End Date,Employee Class,Employee Class Description,FTE,...,EE Work Location Address 1,EE Work Location Address 2,EE Work Location Address 3,EE Work Location Floor,EE Work Location City,EE Work Location State,EE Work Location Zip Code,EE Work Email Address,EE Work Phone,Employee Relation Description
0,NaN,ASLA1,"Chapman,Scott",7239,ANL 6,1995-12-18,NaT,2,Staff: Career,1.0,...,308 Westwood Plaza,ACKERMAN,,,Los Angeles,CA,90095,schapman@asucla.ucla.edu,310/825-2827,"All Others, Not Confidential"
1,NaN,ASLA1,"Baskin,Jane",7234,ANL 1,2006-08-21,NaT,2,Staff: Career,1.0,...,308 Westwood Plaza,ACKERMAN,,,Los Angeles,CA,90095,jbaskin@asucla.ucla.edu,310/206-0775,"All Others, Not Confidential"
2,NaN,ASLA1,"Krieger,Christian",7235,ANL 2,2021-08-12,NaT,2,Staff: Career,1.0,...,308 Westwood Plaza,ACKERMAN,,,Los Angeles,CA,90095,ckrieger@asucla.ucla.edu,310/825-7410,"All Others, Not Confidential"
3,NaN,ASLA1,Student,4921,STDT 2,2025-11-01,2026-10-31,5,Student: Casual/Restricted,0.1,...,308 Westwood Plaza,ACKERMAN,,,Los Angeles,CA,90095,amandabaquir24@ucla.edu,Pending,"All Others, Not Confidential"
4,NaN,ASLA1,"Camacho Osuna,Jose",7234,ANL 1,2025-12-15,NaT,2,Staff: Career,1.0,...,308 Westwood Plaza,ACKERMAN,,,Los Angeles,CA,90095,jcamacho@asucla.ucla.edu,310/206-0776,"All Others, Not Confidential"

In [4]:
titles_of_interest = ['APPLICATIONS PROGR 1', 'APPLICATIONS PROGR 2', 'APPLICATIONS PROGR 3', 'APPLICATIONS PROGR 3 GF',
'BUS SYS ANL 1', 'BUS SYS ANL 2', 'BUS SYS ANL 3', 'BUS SYS ANL 3 GF', 'DATA SYS ANL 1', 'DATA SYS ANL 2', 'DATA SYS ANL 3',
'DATA SYS ANL 3 GF', 'INFO SYS ANL 1', 'INFO SYS ANL 2', 'INFO SYS ANL 3', 'INFO SYS ANL 3 GF','INSTRUCTIONAL DESIGNER 1',
'INSTRUCTIONAL DESIGNER 2', 'INSTRUCTIONAL DESIGNER 3', 'INSTRUCTIONAL DESIGNER 4', 'INSTRUCTIONAL DESIGNER 4 GF']

filter out the titles of interest from the main 99 list

In [5]:
unit_99_titles_of_interest = full_99_list[full_99_list['Job Code Description'].isin(titles_of_interest)]
unit_99_titles_of_interest.head()

,UPTE Title,Location/Business Unit,Employee Lived Name,Job Code,Job Code Description,Most Recent Date of Hire in Empl Rcd,Job Expected End Date,Employee Class,Employee Class Description,FTE,...,EE Work Location Address 1,EE Work Location Address 2,EE Work Location Address 3,EE Work Location Floor,EE Work Location City,EE Work Location State,EE Work Location Zip Code,EE Work Email Address,EE Work Phone,Employee Relation Description
2028,NaN,BKCMP,"Lee,Harold",7309,INFO SYS ANL 3,2004-05-17,NaT,2,Staff: Career,1.0,...,1995 University Avenue,,,F04,Berkeley,CA,94704,hllee@berkeley.edu,510/664-9000,"All Others, Not Confidential"
2032,NaN,BKCMP,"Hanway,Katherine",7584,BUS SYS ANL 3,2001-06-04,NaT,2,Staff: Career,1.0,...,1995 University Avenue,,,F04,Berkeley,CA,94704,khanway@berkeley.edu,360/808-0160,"All Others, Not Confidential"
2080,NaN,BKCMP,"Gergardt,Oleksandr",7309,INFO SYS ANL 3,2013-10-07,NaT,2,Staff: Career,1.0,...,1995 University Avenue,,,F04,Berkeley,CA,94704,ogergardt@berkeley.edu,Pending,"All Others, Not Confidential"
2098,NaN,BKCMP,"Farris,James",7300,APPLICATIONS PROGR 3,2015-04-27,NaT,2,Staff: Career,1.0,...,1995 University Avenue,,,F04,Berkeley,CA,94704,jfarris@berkeley.edu,510/642-1212,"All Others, Not Confidential"
2126,NaN,BKCMP,"Drexler,Santiago",7199,DATA SYS ANL 3,2012-12-12,NaT,2,Staff: Career,1.0,...,1995 University Avenue,,,F04,Berkeley,CA,94704,jmenuisier@berkeley.edu,415/335-0521,"All Others, Not Confidential"

In [6]:
unit_99_titles_of_interest.shape

(2258, 25)

Add the title groups to 99 list

In [ ]:
title_group_dict = {'APPLICATIONS PROGR 1 - 3': ['APPLICATIONS PROGR 1', 'APPLICATIONS PROGR 2', 'APPLICATIONS PROGR 3', 'APPLICATIONS PROGR 3 GF'],
                    'BUS SYS ANL 1 - 3': ['BUS SYS ANL 1', 'BUS SYS ANL 2', 'BUS SYS ANL 3', 'BUS SYS ANL 3 GF'],
                    'DATA SYS ANL 1 - 3': ['DATA SYS ANL 1', 'DATA SYS ANL 2', 'DATA SYS ANL 3', 'DATA SYS ANL 3 GF'],
                    'INFO SYS ANL 1 - 3': ['INFO SYS ANL 1', 'INFO SYS ANL 2', 'INFO SYS ANL 3', 'INFO SYS ANL 3 GF'],
                    'INSTRUCTIONAL DESIGNER 1 - 4': ['INSTRUCTIONAL DESIGNER 1', 'INSTRUCTIONAL DESIGNER 2', 'INSTRUCTIONAL DESIGNER 3', 'INSTRUCTIONAL DESIGNER 4', 'INSTRUCTIONAL DESIGNER 4 GF']}

In [ ]:
title_group_df = pd.Series(title_group_dict).explode().reset_index()
title_group_df.columns = ['Job Title Group', 'Job Code Description']
title_group_df.head()

            Job Title Group     Job Code Description
0  APPLICATIONS PROGR 1 - 3     APPLICATIONS PROGR 1
1  APPLICATIONS PROGR 1 - 3     APPLICATIONS PROGR 2
2  APPLICATIONS PROGR 1 - 3     APPLICATIONS PROGR 3
3  APPLICATIONS PROGR 1 - 3  APPLICATIONS PROGR 3 GF
4         BUS SYS ANL 1 - 3            BUS SYS ANL 1

In [ ]:
unit_99_titles_of_interest = unit_99_titles_of_interest.merge(title_group_df, on='Job Code Description', how='left')
unit_99_titles_of_interest.head()

,UPTE Title,Location/Business Unit,Employee Lived Name,Job Code,Job Code Description,Most Recent Date of Hire in Empl Rcd,Job Expected End Date,Employee Class,Employee Class Description,FTE,...,EE Work Location Address 2,EE Work Location Address 3,EE Work Location Floor,EE Work Location City,EE Work Location State,EE Work Location Zip Code,EE Work Email Address,EE Work Phone,Employee Relation Description,Job Title Group
0,NaN,BKCMP,"Lee,Harold",7309,INFO SYS ANL 3,2004-05-17,NaT,2,Staff: Career,1.0,...,,,F04,Berkeley,CA,94704,hllee@berkeley.edu,510/664-9000,"All Others, Not Confidential",INFO SYS ANL 1 - 3
1,NaN,BKCMP,"Hanway,Katherine",7584,BUS SYS ANL 3,2001-06-04,NaT,2,Staff: Career,1.0,...,,,F04,Berkeley,CA,94704,khanway@berkeley.edu,360/808-0160,"All Others, Not Confidential",BUS SYS ANL 1 - 3
2,NaN,BKCMP,"Gergardt,Oleksandr",7309,INFO SYS ANL 3,2013-10-07,NaT,2,Staff: Career,1.0,...,,,F04,Berkeley,CA,94704,ogergardt@berkeley.edu,Pending,"All Others, Not Confidential",INFO SYS ANL 1 - 3
3,NaN,BKCMP,"Farris,James",7300,APPLICATIONS PROGR 3,2015-04-27,NaT,2,Staff: Career,1.0,...,,,F04,Berkeley,CA,94704,jfarris@berkeley.edu,510/642-1212,"All Others, Not Confidential",APPLICATIONS PROGR 1 - 3
4,NaN,BKCMP,"Drexler,Santiago",7199,DATA SYS ANL 3,2012-12-12,NaT,2,Staff: Career,1.0,...,,,F04,Berkeley,CA,94704,jmenuisier@berkeley.edu,415/335-0521,"All Others, Not Confidential",DATA SYS ANL 1 - 3

In [18]:
unit_99_titles_of_interest.to_excel('unit_99_titles_of_interest.xlsx')

create pivot tables with departments and job title groups

In [7]:
unit_99_pivot_title_groups = unit_99_titles_of_interest.pivot_table(index=['Location/Business Unit', 'Department Description'],
                                       columns = 'Job Code Description',
                                       values = 'Employee Lived Name',
                                       aggfunc = 'count', fill_value=0)
unit_99_pivot_title_groups = unit_99_pivot_title_groups.reset_index()

In [8]:
unit_99_pivot_title_groups.head()

Job Code Description,Location/Business Unit,Department Description,APPLICATIONS PROGR 1,APPLICATIONS PROGR 2,APPLICATIONS PROGR 3,APPLICATIONS PROGR 3 GF,BUS SYS ANL 1,BUS SYS ANL 2,BUS SYS ANL 3,BUS SYS ANL 3 GF,...,DATA SYS ANL 3 GF,INFO SYS ANL 1,INFO SYS ANL 2,INFO SYS ANL 3,INFO SYS ANL 3 GF,INSTRUCTIONAL DESIGNER 1,INSTRUCTIONAL DESIGNER 2,INSTRUCTIONAL DESIGNER 3,INSTRUCTIONAL DESIGNER 4,INSTRUCTIONAL DESIGNER 4 GF
0,BKCMP,Astronomy,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1,BKCMP,BFS Business Systems,0,0,0,0,0,0,4,0,...,0,0,0,0,0,0,0,0,0,0
2,BKCMP,Berkeley International Office,0,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,BKCMP,Berkeley Seismological Lab,0,0,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,BKCMP,Biosciences Divisional Srvcs,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

Warning: Total number of columns (23) exceeds max_columns (20) limiting to first (20) columns.

importing the juris list that already includes the title group column

In [9]:
TX_juris_df = pd.read_excel('/content/TX_I254_DATA_05042026_045959.xlsx', sheet_name='juris_list')
TX_juris_df.shape

(6282, 32)

In [10]:
TX_pivot_table_dept_title_groups = TX_juris_df.pivot_table(index=['Location/Business Unit', 'Department ID Description'],
                                       columns = 'Job Title Group',
                                       values = 'Employee Name',
                                       aggfunc = 'count', fill_value=0,
                                       margins = True, margins_name='Total_TX_Cnt')

TX_pivot_table_dept_title_groups = TX_pivot_table_dept_title_groups.reset_index()

In [11]:
tx_pivot_key_cols = ['Location/Business Unit', 'Department ID Description', 'Total_TX_Cnt']
tx_pivot_col_order =  tx_pivot_key_cols + [col for col in TX_pivot_table_dept_title_groups.columns if col not in tx_pivot_key_cols]
TX_pivot_table_dept_title_groups = TX_pivot_table_dept_title_groups[tx_pivot_col_order]

In [12]:
TX_pivot_table_dept_title_groups.head()

Job Title Group,Location/Business Unit,Department ID Description,Total_TX_Cnt,ANML HEALTH TCHN,ANML TCHN,ART MODEL,ARTIST,AV IT ENGR,Accelerator Operator,BROADCAST COMM SPEC,...,TECH SUPP ANL,TELESCOPE TCHN,TELEVISION ENGR,TELEVISION TCHN,TRANSLATOR,Telecomm Network/Data Comm,USER EXP DESIGNER,Video Prod. & Editing Spec,WARDROBE TCHN,WRITER
0,BKCMP,Art History,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,BKCMP,Art Mus & Pacific Film Archive,22,0,0,0,0,0,0,0,...,0,0,1,2,0,0,0,0,0,0
2,BKCMP,Art Practice,4,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,BKCMP,Astronomy,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,BKCMP,BFS Business Systems,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Merge the 2 pivot tables keeping the unit 99 table as the main table

In [13]:
# reset index to get the location and departments as regular columns
unit_99_pivot_title_groups.reset_index()
TX_pivot_table_dept_title_groups.reset_index()

Job Title Group,index,Location/Business Unit,Department ID Description,Total_TX_Cnt,ANML HEALTH TCHN,ANML TCHN,ART MODEL,ARTIST,AV IT ENGR,Accelerator Operator,...,TECH SUPP ANL,TELESCOPE TCHN,TELEVISION ENGR,TELEVISION TCHN,TRANSLATOR,Telecomm Network/Data Comm,USER EXP DESIGNER,Video Prod. & Editing Spec,WARDROBE TCHN,WRITER
0,0,BKCMP,Art History,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,BKCMP,Art Mus & Pacific Film Archive,22,0,0,0,0,0,0,...,0,0,1,2,0,0,0,0,0,0
2,2,BKCMP,Art Practice,4,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,BKCMP,Astronomy,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,BKCMP,BFS Business Systems,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
897,897,UCOP1,IMMED OFFICE GENERAL COUNSEL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
898,898,UCOP1,IT SECURITY/PRIVACY,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
899,899,UCOP1,TECHNOLOGY DELIVERY SERVICES,65,0,0,0,0,0,0,...,12,0,0,0,0,0,1,0,0,0
900,900,UCOP1,UC PRESS BOOKS,2,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
901,901,Total_TX_Cnt,,6282,317,518,8,71,37,17,...,13,19,10,62,13,7,78,2,16,13

In [14]:
merged_df_all =  unit_99_pivot_title_groups.merge(TX_pivot_table_dept_title_groups,left_on=['Location/Business Unit', 'Department Description'],
                                 right_on = ['Location/Business Unit', 'Department ID Description'], how='left')

In [15]:
merged_df_all.drop(columns=['Department ID Description'], inplace=True)

print the merged df into an excel with the tabs being the locations

In [ ]:
with pd.ExcelWriter('upte_99_title_groups__tx_cnts_universe.xlsx') as writer:

  for location, group in merged_df_all.groupby('Location/Business Unit'):
    sheet_name = location
    group.to_excel(writer, sheet_name=sheet_name, index=False)
#

Prepare the dataset keeping only the departments where UPTE members work

In [16]:
merged_upte_depts_df = merged_df_all[~merged_df_all['Total_TX_Cnt'].isna()]

In [17]:
with pd.ExcelWriter('upte_99_titles_tx_group_cnts_tx_depts.xlsx') as writer:

  for location, group in merged_upte_depts_df.groupby('Location/Business Unit'):
    sheet_name = location
    group.to_excel(writer, sheet_name=sheet_name, index=False)

In [ ]:
unit_99_target_dept_cnt = merged_df_all['Location/Business Unit'].value_counts().reset_index()
unit_99_target_dept_cnt.columns = ['Location/Business Unit', 'Total_99_Cnt']

In [ ]:
tx_dept_overlap_cnt = merged_upte_depts_df['Location/Business Unit'].value_counts().reset_index()
tx_dept_overlap_cnt.columns = ['Location/Business Unit', 'Total_TX_Cnt']

In [ ]:
dept_comparison_df = unit_99_target_dept_cnt.merge(tx_dept_overlap_cnt, on='Location/Business Unit', how='left')

In [ ]:
dept_comparison_df.to_csv('dept_comparison.csv')