<a href="https://colab.research.google.com/github/tougheye/Data_processing/blob/main/TX_mapping_99.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

full_99_list = pd.read_excel('/content/drive/MyDrive/UPTE-26-019_99 List_April 2026 (2) (2).xlsx', sheet_name="Report Page")
full_99_list.head()

,UPTE Title,Location/Business Unit,Employee Lived Name,Job Code,Job Code Description,Most Recent Date of Hire in Empl Rcd,Job Expected End Date,Employee Class,Employee Class Description,FTE,...,EE Work Location Address 1,EE Work Location Address 2,EE Work Location Address 3,EE Work Location Floor,EE Work Location City,EE Work Location State,EE Work Location Zip Code,EE Work Email Address,EE Work Phone,Employee Relation Description
0,NaN,ASLA1,"Chapman,Scott",7239,ANL 6,1995-12-18,NaT,2,Staff: Career,1.0,...,308 Westwood Plaza,ACKERMAN,,,Los Angeles,CA,90095,schapman@asucla.ucla.edu,310/825-2827,"All Others, Not Confidential"
1,NaN,ASLA1,"Baskin,Jane",7234,ANL 1,2006-08-21,NaT,2,Staff: Career,1.0,...,308 Westwood Plaza,ACKERMAN,,,Los Angeles,CA,90095,jbaskin@asucla.ucla.edu,310/206-0775,"All Others, Not Confidential"
2,NaN,ASLA1,"Krieger,Christian",7235,ANL 2,2021-08-12,NaT,2,Staff: Career,1.0,...,308 Westwood Plaza,ACKERMAN,,,Los Angeles,CA,90095,ckrieger@asucla.ucla.edu,310/825-7410,"All Others, Not Confidential"
3,NaN,ASLA1,Student,4921,STDT 2,2025-11-01,2026-10-31,5,Student: Casual/Restricted,0.1,...,308 Westwood Plaza,ACKERMAN,,,Los Angeles,CA,90095,amandabaquir24@ucla.edu,Pending,"All Others, Not Confidential"
4,NaN,ASLA1,"Camacho Osuna,Jose",7234,ANL 1,2025-12-15,NaT,2,Staff: Career,1.0,...,308 Westwood Plaza,ACKERMAN,,,Los Angeles,CA,90095,jcamacho@asucla.ucla.edu,310/206-0776,"All Others, Not Confidential"

Warning: Total number of columns (25) exceeds max_columns (20) limiting to first (20) columns.

In [4]:
titles_of_interest = ['APPLICATIONS PROGR 1', 'APPLICATIONS PROGR 2', 'APPLICATIONS PROGR 3', 'APPLICATIONS PROGR 3 GF',
'BUS SYS ANL 1', 'BUS SYS ANL 2', 'BUS SYS ANL 3', 'BUS SYS ANL 3 GF', 'DATA SYS ANL 1', 'DATA SYS ANL 2', 'DATA SYS ANL 3',
'DATA SYS ANL 3 GF', 'INFO SYS ANL 1', 'INFO SYS ANL 2', 'INFO SYS ANL 3', 'INFO SYS ANL 3 GF','INSTRUCTIONAL DESIGNER 1',
'INSTRUCTIONAL DESIGNER 2', 'INSTRUCTIONAL DESIGNER 3', 'INSTRUCTIONAL DESIGNER 4', 'INSTRUCTIONAL DESIGNER 4 GF']

In [8]:
unit_99_titles_of_interest = full_99_list[full_99_list['Job Code Description'].isin(titles_of_interest)]
unit_99_titles_of_interest.head()

,UPTE Title,Location/Business Unit,Employee Lived Name,Job Code,Job Code Description,Most Recent Date of Hire in Empl Rcd,Job Expected End Date,Employee Class,Employee Class Description,FTE,...,EE Work Location Address 1,EE Work Location Address 2,EE Work Location Address 3,EE Work Location Floor,EE Work Location City,EE Work Location State,EE Work Location Zip Code,EE Work Email Address,EE Work Phone,Employee Relation Description
2028,NaN,BKCMP,"Lee,Harold",7309,INFO SYS ANL 3,2004-05-17,NaT,2,Staff: Career,1.0,...,1995 University Avenue,,,F04,Berkeley,CA,94704,hllee@berkeley.edu,510/664-9000,"All Others, Not Confidential"
2032,NaN,BKCMP,"Hanway,Katherine",7584,BUS SYS ANL 3,2001-06-04,NaT,2,Staff: Career,1.0,...,1995 University Avenue,,,F04,Berkeley,CA,94704,khanway@berkeley.edu,360/808-0160,"All Others, Not Confidential"
2080,NaN,BKCMP,"Gergardt,Oleksandr",7309,INFO SYS ANL 3,2013-10-07,NaT,2,Staff: Career,1.0,...,1995 University Avenue,,,F04,Berkeley,CA,94704,ogergardt@berkeley.edu,Pending,"All Others, Not Confidential"
2098,NaN,BKCMP,"Farris,James",7300,APPLICATIONS PROGR 3,2015-04-27,NaT,2,Staff: Career,1.0,...,1995 University Avenue,,,F04,Berkeley,CA,94704,jfarris@berkeley.edu,510/642-1212,"All Others, Not Confidential"
2126,NaN,BKCMP,"Drexler,Santiago",7199,DATA SYS ANL 3,2012-12-12,NaT,2,Staff: Career,1.0,...,1995 University Avenue,,,F04,Berkeley,CA,94704,jmenuisier@berkeley.edu,415/335-0521,"All Others, Not Confidential"

In [9]:
unit_99_titles_of_interest.shape

(2258, 25)

In [ ]:
unit_99_titles_of_interest.pivot_table()

In [10]:
unit_99_titles_of_interest.columns

Index(['UPTE Title', 'Location/Business Unit', 'Employee Lived Name',
       'Job Code', 'Job Code Description',
       'Most Recent Date of Hire in Empl Rcd', 'Job Expected End Date',
       'Employee Class', 'Employee Class Description', 'FTE',
       'Job Hourly Rate', 'Annual Salary', 'Department Description',
       'Location Code', 'Location Code Description',
       'EE Work Location Address 1', 'EE Work Location Address 2',
       'EE Work Location Address 3', 'EE Work Location Floor',
       'EE Work Location City', 'EE Work Location State',
       'EE Work Location Zip Code', 'EE Work Email Address', 'EE Work Phone',
       'Employee Relation Description'],
      dtype='object')

importing the juris list that already includes the title group column

In [6]:
TX_juris_df = pd.read_excel('/content/TX_I254_DATA_05042026_045959.xlsx', sheet_name='juris_list')
TX_juris_df.shape

(6282, 32)

In [ ]:
unit_99_titles_of_interest.merge(TX_juris_df, left_on=)