<a href="https://colab.research.google.com/github/tougheye/Data_processing/blob/main/UCSF_Clin_prof_HCOMP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import pandas as pd

latest_99_file = pd.ExcelFile("/content/drive/MyDrive/Data/Unit_99_Title_Claim/Historical 99 Data/UPTE_99_as_of_6_3_2026.xlsx")
latest_99_file_sheet_names = latest_99_file.sheet_names
print(latest_99_file_sheet_names)

['Sheet1']

In [19]:
latest_99_df = latest_99_file.parse(latest_99_file_sheet_names[0])
latest_99_df.shape

(172900, 25)

In [20]:
latest_99_df.columns

Index(['Location/Business Unit', 'Employee Lived Name', 'Job Code',
       'Job Code Description', 'Most Recent Date of Hire in Empl Rcd',
       'Job Expected End Date', 'Employee Class', 'Employee Class Description',
       'FTE', 'Job Hourly Rate', 'Annual Salary', 'Department ID',
       'Department Description', 'Location Code', 'Location Code Description',
       'EE Work Location Address 1', 'EE Work Location Address 2',
       'EE Work Location Address 3', 'EE Work Location Floor',
       'EE Work Location City', 'EE Work Location State',
       'EE Work Location Zip Code', 'EE Work Email Address', 'EE Work Phone',
       'Employee Relation Description'],
      dtype='object')

In [21]:
latest_99_df.head()

,Location/Business Unit,Employee Lived Name,Job Code,Job Code Description,Most Recent Date of Hire in Empl Rcd,Job Expected End Date,Employee Class,Employee Class Description,FTE,Job Hourly Rate,...,EE Work Location Address 1,EE Work Location Address 2,EE Work Location Address 3,EE Work Location Floor,EE Work Location City,EE Work Location State,EE Work Location Zip Code,EE Work Email Address,EE Work Phone,Employee Relation Description
0,ASLA1,"Chapman,Scott",007239,ANL 6,1995-12-18,NaT,2,Staff: Career,1.0,55.948276,...,308 Westwood Plaza,ACKERMAN,,,Los Angeles,CA,90095,schapman@asucla.ucla.edu,310/825-2827,"All Others, Not Confidential"
1,ASLA1,"Baskin,Jane",007234,ANL 1,2006-08-21,NaT,2,Staff: Career,1.0,30.982759,...,308 Westwood Plaza,ACKERMAN,,,Los Angeles,CA,90095,jbaskin@asucla.ucla.edu,310/206-0775,"All Others, Not Confidential"
2,ASLA1,"Krieger,Christian",007235,ANL 2,2021-08-12,NaT,2,Staff: Career,1.0,25.540230,...,308 Westwood Plaza,ACKERMAN,,,Los Angeles,CA,90095,ckrieger@asucla.ucla.edu,310/825-7410,"All Others, Not Confidential"
3,ASLA1,NaN,004921,STDT 2,2025-11-01,2026-10-31,5,Student: Casual/Restricted,0.1,17.900000,...,308 Westwood Plaza,ACKERMAN,,,Los Angeles,CA,90095,amandabaquir24@ucla.edu,Pending,"All Others, Not Confidential"
4,ASLA1,"Camacho Osuna,Jose",007234,ANL 1,2025-12-15,NaT,2,Staff: Career,1.0,26.340994,...,308 Westwood Plaza,ACKERMAN,,,Los Angeles,CA,90095,jcamacho@asucla.ucla.edu,310/206-0776,"All Others, Not Confidential"

In [22]:
from numpy._core.fromnumeric import shape
# Get the UCSF Psychs list in
ucsf_file = pd.read_excel("/content/UCSF HS CLIN PROF Psychologists.xlsx")
ucsf_file.shape

(57, 92)

In [6]:
ucsf_file.columns

Index(['UPTE Leader', 'Unit', 'Physician/Faculty In Boradstripes Database',
       'Campus', 'Job Title', 'Department', 'First/Preferred Name',
       'Middle Name', 'Last Name', 'Pronouns', 'Assessment',
       'Survey Completed?', 'Member Notes', 'Organizer Notes', 'Issue ID',
       'UPTE Member History',
       'Last Name and/or Address Matches to UPTE Members', 'Working Title',
       'Director?', 'UC Provided Work Location', 'Building', 'Room',
       'Location notes: remote, office hours, etc.', 'Personal Email',
       'Personal Email 2', 'Personal Email 3', 'UC Email', 'UC Email 2',
       'UC Email 3', 'OPT OUT OF EMAILS?', 'Cell Phone', 'Home Phone',
       'Work Phone', 'LinkedIn URL', 'Other Website(s)', 'Home Address', 'Age',
       'Research Notes', 'Hire Date', 'Job Expected End Date',
       'Employee Class Description', 'FTE', 'Job Hourly Rate',
       'Employee Relation Description', 'Location/Business Unit',
       'UC Employee Name', 'Sheet ID', 'Medical License #',
       'Address on Record - Medical License', 'Profession',
       'Medical Title (MD, PT, etc.)',
       'Year Graduated Medical School (if applicable)', 'Medical School',
       'Medical Specialty', 'Medical School 1 Name',
       'Medical School 1 Gradation Year', 'Medical School 1 Degree',
       'Medical School 1 Description', 'Medical School 2 Name',
       'Medical School 2 Gradation Year', 'Medical School 2 Degree',
       'Medical School 2 Description', 'Residency Location 1',
       'Residency Description 1', 'Residency Location 2',
       'Residency Description 2', 'Fellowship Location 1',
       'Fellowship Description', 'Fellowship Location 2',
       'Fellowship Description 2', 'Other Universities/Colleges',
       'Other Institution 1 Name', 'Other Institution 1 Gradation Year',
       'Other Institution 1 Degree', 'Other Institution 1 Description',
       'Other Institution 2 Name', 'Other Institution 2 Gradation Year',
       'Other Institution 2 Degree', 'Other Institution 2 Description',
       'Other Institution 3 Name', 'Other Institution 3 Gradation Year',
       'Other Institution 3 Degree', 'Other Institution 3 Description',
       'Professional Organizations', 'Works Clinically at UC?',
       'Researcher Name', 'Research Date', 'Research Round 1 Complete?',
       'Researcher Name - Social Mapping', 'Social Mapping Research Date',
       'Social Mapping Research Complete?', 'Source Spreadsheet'],
      dtype='object')

In [26]:
col_list = ['Location/Business Unit','UC Employee Name', 'UC Email', 'Job Title', 'Department']

ucsf_psych_match_99 = latest_99_df.merge(ucsf_file[col_list], left_on=['Location/Business Unit', 'Employee Lived Name'],
                   right_on=['Location/Business Unit', 'UC Employee Name'])
ucsf_psych_match_99.shape

(56, 29)

In [27]:
ucsf_psych_match_99.to_excel("UCSF_psychologists_in_99.xlsx")

In [16]:
# filter out the 99 rows of the UCSF psychs
ucsf_psychs_in_99 = latest_99_df[latest_99_df['EE Work Email Address'].isin(ucsf_file['UC Email'])]
ucsf_psychs_in_99.shape

(37, 25)

In [15]:
latest_99_df[latest_99_df['EE Work Email Address'].isin(ucsf_file['UC Email'])]

,Location/Business Unit,Employee Lived Name,Job Code,Job Code Description,Most Recent Date of Hire in Empl Rcd,Job Expected End Date,Employee Class,Employee Class Description,FTE,Job Hourly Rate,...,EE Work Location Address 1,EE Work Location Address 2,EE Work Location Address 3,EE Work Location Floor,EE Work Location City,EE Work Location State,EE Work Location Zip Code,EE Work Email Address,EE Work Phone,Employee Relation Description
16081,BKCMP,"Shaller,Esme",002040,HS ASST CLIN PROF-AY,2013-07-01,2028-06-30,9,Academic: Faculty,0.00,0.000000,...,2121 Berkeley Way,,,SITE,Berkeley,CA,94720,esme.shaller@ucsf.edu,415/476-7227,"All Others, Not Confidential"
150357,SFCMP,"Sullivan,Alexandra",001728,ASST ADJ PROF-HCOMP,2022-08-15,2026-06-30,9,Academic: Faculty,1.00,63.649425,...,675 18th Street,Nancy Friend Pritzker Psychiatry Building,0100,00,San Francisco,CA,94107,allie.sullivan@ucsf.edu,Pending,"All Others, Not Confidential"
151124,SFCMP,"Weyer Jamora,Christina",001734,HS CLIN PROF-HCOMP,2008-03-06,2026-06-30,9,Academic: Faculty,1.00,115.229885,...,400 Parnassus Avenue,ACC Building,A808,08,San Francisco,CA,94143,christina.weyerjamora@ucsf.edu,628/206-8426,"All Others, Not Confidential"
151152,SFCMP,"Jimenez,Tina",001732,HS ASST CLIN PROF-HCOMP,2025-06-01,2026-06-30,9,Academic: Faculty,1.00,77.873563,...,521 Parnassus Avenue,,6101,06,San Francisco,CA,94117,tina.jimenez@ucsf.edu,310/206-7438,"All Others, Not Confidential"
154240,SFCMP,"Shaller,Esme",001734,HS CLIN PROF-HCOMP,2007-10-08,2026-06-30,9,Academic: Faculty,0.85,100.574713,...,1550 Fourth Street,Rock Hall,282,02,San Francisco,CA,94158,esme.shaller@ucsf.edu,415/476-7227,"All Others, Not Confidential"
154241,SFCMP,"Zalecki,Christine",001734,HS CLIN PROF-HCOMP,2018-04-01,2026-06-30,9,Academic: Faculty,1.00,100.574713,...,1550 Fourth Street,Rock Hall,282,02,San Francisco,CA,94158,christine.zalecki2@ucsf.edu,415/476-7849,"All Others, Not Confidential"
154251,SFCMP,"Jou Santacreu,Joan",001733,HS ASSOC CLIN PROF-HCOMP,2018-11-01,2026-06-30,9,Academic: Faculty,1.00,81.417626,...,1550 Fourth Street,Rock Hall,282,02,San Francisco,CA,94158,joan.jousantacreu@ucsf.edu,415/502-9665,"All Others, Not Confidential"
154281,SFCMP,"Haack,Lauren",001733,HS ASSOC CLIN PROF-HCOMP,2017-08-14,2026-06-30,9,Academic: Faculty,1.00,93.390805,...,1550 Fourth Street,Rock Hall,282,02,San Francisco,CA,94158,lauren.haack@ucsf.edu,415/502-8060,"All Others, Not Confidential"
154289,SFCMP,"Keyser,Jessica",001734,HS CLIN PROF-HCOMP,2013-03-01,2026-06-30,9,Academic: Faculty,1.00,97.701149,...,1550 Fourth Street,Rock Hall,282,02,San Francisco,CA,94158,jessica.keyser@ucsf.edu,415/502-4637,"All Others, Not Confidential"
154291,SFCMP,"Lin,Enjey",001734,HS CLIN PROF-HCOMP,2010-09-01,2026-06-30,9,Academic: Faculty,1.00,95.785443,...,1550 Fourth Street,Rock Hall,282,02,San Francisco,CA,94158,enjey.lin@ucsf.edu,Pending,"All Others, Not Confidential"
154355,SFCMP,"Arnold,Allison",001733,HS ASSOC CLIN PROF-HCOMP,2015-01-14,2026-06-30,9,Academic: Faculty,1.00,86.206897,...,1550 Fourth Street,Rock Hall,282,02,San Francisco,CA,94158,allison.libby@ucsf.edu,415/502-3124,"All Others, Not Confidential"
154356,SFCMP,"Forsberg,Sarah",001734,HS CLIN PROF-HCOMP,2015-09-16,2026-06-30,9,Academic: Faculty,1.00,95.785443,...,1550 Fourth Street,Rock Hall,282,02,San Francisco,CA,94158,sarah.forsberg@ucsf.edu,415/476-7463,"All Others, Not Confidential"
154362,SFCMP,"Zamaria,Joseph",001734,HS CLIN PROF-HCOMP,2016-07-20,2026-06-30,9,Academic: Faculty,1.00,84.195402,...,675 18th Street,Nancy Friend Pritzker Psychiatry Building,4250,04,San Francisco,CA,94107,joseph.zamaria@ucsf.edu,415/502-7396,"All Others, Not Confidential"
154387,SFCMP,"Meredith,Samantha Fordwood",001734,HS CLIN PROF-HCOMP,2019-11-01,2026-06-30,9,Academic: Faculty,0.75,99.616858,...,675 Nelson Rising Lane,Sandler Center,560G,05,San Francisco,CA,94158,samantha.fordwood@ucsf.edu,415/514-6475,"All Others, Not Confidential"
154405,SFCMP,"Cullinan,Colleen",001733,HS ASSOC CLIN PROF-HCOMP,2023-03-01,2026-06-30,9,Academic: Faculty,1.00,81.417626,...,675 Nelson Rising Lane,Sandler Center,560G,05,San Francisco,CA,94158,colleen.cullinan@ucsf.edu,Pending,"All Others, Not Confidential"
154409,SFCMP,"Bose,Deepika",001732,HS ASST CLIN PROF-HCOMP,2024-01-16,2026-06-30,9,Academic: Faculty,1.00,63.697316,...,675 Nelson Rising Lane,Sandler Center,560G,05,San Francisco,CA,94158,deepika.bose@ucsf.edu,Pending,"All Others, Not Confidential"
154410,SFCMP,"Wei,Melissa",001732,HS ASST CLIN PROF-HCOMP,2024-03-01,2026-06-30,9,Academic: Faculty,1.00,63.697316,...,675 Nelson Rising Lane,Sandler Center,560G,05,San Francisco,CA,94158,melissa.wei@ucsf.edu,Pending,"All Others, Not Confidential"
154412,SFCMP,"Leckie,Amber",001732,HS ASST CLIN PROF-HCOMP,2024-05-13,2026-06-30,9,Academic: Faculty,1.00,63.697316,...,675 Nelson Rising Lane,Sandler Center,560G,05,San Francisco,CA,94158,amber.leckie2@ucsf.edu,Pending,"All Others, Not Confidential"
154418,SFCMP,"Garrison,Daniel",001733,HS ASSOC CLIN PROF-HCOMP,2025-11-03,2026-11-02,9,Academic: Faculty,1.00,82.375477,...,675 Nelson Rising Lane,Sandler Center,560G,05,San Francisco,CA,94158,daniel.garrison@ucsf.edu,Pending,"All Others, Not Confidential"
154496,SFCMP,"Hamlat,Elissa",001728,ASST ADJ PROF-HCOMP,2019-08-01,2026-06-30,9,Academic: Faculty,1.00,59.339080,...,654 Minnesota Street,,,1,San Francisco,CA,94107,elissa.hamlat@ucsf.edu,510/847-5633,"All Others, Not Confidential"
154504,SFCMP,"Radin,Rachel",001728,ASST ADJ PROF-HCOMP,2017-07-01,2026-06-30,9,Academic: Faculty,1.00,66.977489,...,654 Minnesota Street,,,1,San Francisco,CA,94107,rachel.radin@ucsf.edu,415/885-7733,"All Others, Not Confidential"
154546,SFCMP,"Reyes,Vilma",001733,HS ASSOC CLIN PROF-HCOMP,2009-09-01,2026-06-30,9,Academic: Faculty,1.00,85.249040,...,1001 Potrero Avenue,ZSFG Building 5,7M2,07,San Francisco,CA,94110,vilma.reyes@ucsf.edu,415/776-4010,"All Others, Not Confidential"
154730,SFCMP,"Leba,Nikki",001732,HS ASST CLIN PROF-HCOMP,2024-05-01,2026-06-30,9,Academic: Faculty,1.00,68.180557,...,654 Minnesota Street,,,1,San Francisco,CA,94107,nicole.vu@ucsf.edu,415/205-2490,"All Others, Not Confidential"
154833,SFCMP,"Mccuistian,Caravella",001732,HS ASST CLIN PROF-HCOMP,2018-07-01,2026-06-30,9,Academic: Faculty,1.00,71.942052,...,1001 Potrero Avenue,ZSFG Building 5,7G15,07,San Francisco,CA,94110,caravella.mccuistian@ucsf.edu,Pending,"All Others, Not Confidential"
154856,SFCMP,"Reilly,Erin",001728,ASST ADJ PROF-HCOMP,2022-01-03,2026-06-30,9,Academic: Faculty,1.00,76.047891,...,654 Minnesota Street,,,1,San Francisco,CA,94107,erin.reilly3@ucsf.edu,415/502-6861,"All Others, Not Confidential"
154934,SFCMP,"Chung,Sara",001732,HS ASST CLIN PROF-HCOMP,2021-12-01,2026-06-30,9,Academic: Faculty,1.00,62.260534,...,675 18th Street,Nancy Friend Pritzker Psychiatry Building,0100,00,San Francisco,CA,94107,sara.chung@ucsf.edu,Pending,"All Others, Not Confidential"
155246,SFCMP,"Darrow,Sabrina",001734,HS CLIN PROF-HCOMP,2011-09-01,2026-06-30,9,Academic: Faculty,0.75,95.785441,...,654 Minnesota Street,,,1,San Francisco,CA,94107,sabrina.darrow@ucsf.edu,Pending,"All Others, Not Confidential"
155249,SFCMP,"Gorrell,Sasha",001728,ASST ADJ PROF-HCOMP,2018-06-30,2026-06-30,9,Academic: Faculty,1.00,74.233718,...,401 Parnassus Avenue,Langley Porter Psych Inst,LP-257,02,San Francisco,CA,94143,sasha.gorrell@ucsf.edu,415/502-2716,"All Others, Not Confidential"
155266,SFCMP,"Hail,Lisa",001733,HS ASSOC CLIN PROF-HCOMP,2016-07-01,2026-06-30,9,Academic: Faculty,1.00,81.417626,...,654 Minnesota Street,,,1,San Francisco,CA,94107,lisa.hail@ucsf.edu,415/502-9691,"All Others, Not Confidential"
155273,SFCMP,"Mosti,Caterina",001733,HS ASSOC CLIN PROF-HCOMP,2019-08-26,2026-06-30,9,Academic: Faculty,1.00,73.209770,...,675 18th Street,Nancy Friend Pritzker Psychiatry Building,5124,05,San Francisco,CA,94107,caterina.mosti@ucsf.edu,Pending,"All Others, Not Confidential"
157962,SFCMP,"Mccuistian,Caravella",002050,HS ASST CLIN PROF-FY,2025-05-01,2026-06-30,9,Academic: Faculty,0.00,0.000000,...,550 16th Street,Mission Hall Building,3843,03,San Francisco,CA,94158,caravella.mccuistian@ucsf.edu,Pending,"All Others, Not Confidential"
160344,SFCMP,"Stephens,Melanie",001733,HS ASSOC CLIN PROF-HCOMP,2013-09-09,2026-06-30,9,Academic: Faculty,1.00,155.651339,...,1651 4th Street,Joan and Sanford I Weill Neurosciences Building,371D,03,San Francisco,CA,94158,melanie.stephens@ucsf.edu,415/476-2907,"All Others, Not Confidential"
160552,SFCMP,"Tsoy,Elena",001728,ASST ADJ PROF-HCOMP,2018-08-27,2026-06-30,9,Academic: Faculty,1.00,74.233718,...,35 Medical Center Way,Dolby Regeneration Medicine,1038,10,San Francisco,CA,94143,elena.tsoy@ucsf.edu,Pending,"All Others, Not Confidential"
160560,SFCMP,"Inkelis,Sarah",001728,ASST ADJ PROF-HCOMP,2024-01-15,2026-06-30,9,Academic: Faculty,1.00,73.754787,...,35 Medical Center Way,Dolby Regeneration Medicine,1038,10,San Francisco,CA,94143,sarah.inkelis@ucsf.edu,415/353-9220,"All Others, Not Confidential"
160617,SFCMP,"Paolillo,Emily",001728,ASST ADJ PROF-HCOMP,2023-09-01,2026-06-30,9,Academic: Faculty,1.00,79.022989,...,675 Nelson Rising Lane,Sandler Center,190F,01,San Francisco,CA,94158,emily.paolillo@ucsf.edu,Pending,"All Others, Not Confidential"
160618,SFCMP,"Saloner,Rowan",001728,ASST ADJ PROF-HCOMP,2021-07-01,2026-06-30,9,Academic: Faculty,1.00,71.839080,...,35 Medical Center Way,Dolby Regeneration Medicine,1038,10,San Francisco,CA,94143,rowan.saloner@ucsf.edu,Pending,"All Others, Not Confidential"
160620,SFCMP,"Hill-Jarrett,Tanisha",001728,ASST ADJ PROF-HCOMP,2023-10-01,2026-06-30,9,Academic: Faculty,1.00,86.685822,...,1651 4th Street,Joan and Sanford I Weill Neurosciences Building,371R,03,San Francisco,CA,94158,tanisha.hill-jarrett@ucsf.edu,Pending,"All Others, Not Confidential"

In [17]:
ucsf_psychs_in_99.to_excel("UCSF_psychologists_in_99_email_match.xlsx")

In [ ]:
HCOMP_file = pd.ExcelFile('/content/001732_HS ASST CLIN PROF-HCOMP_details.xlsx')
HCOMP_file.sheet_names

['Detail Information', 'Step Rates']

In [ ]:
hcomp_steps_df = HCOMP_file.parse(HCOMP_file.sheet_names[1])
hcomp_steps_df.shape

(60, 6)

In [ ]:
hcomp_step_salary = set(hcomp_steps_df['Salary Rate'].values)

Get the UcSF HS ASST CLIN PROF-HCOMP titles from the most recent 99 list

In [ ]:
sf_hcomp_df = latest_99_df[(latest_99_df['Job Code'] == '001732') & (latest_99_df['Location/Business Unit'] == 'SFCMP')]
sf_99_salary_set = set(sf_hcomp_df['Annual Salary'].values)
sf_99_salary_set

{np.float64(24960.0),
 np.float64(30093.75),
 np.float64(66963.0),
 np.float64(68950.0),
 np.float64(76262.3),
 np.float64(82675.0),
 np.float64(84150.0),
 np.float64(98475.0),
 np.float64(104280.88),
 np.float64(113840.0),
 np.float64(117200.0),
 np.float64(121900.0),
 np.float64(121950.0),
 np.float64(122136.0),
 np.float64(125848.11),
 np.float64(128000.0),
 np.float64(128100.0),
 np.float64(130000.0),
 np.float64(131660.2),
 np.float64(132388.9),
 np.float64(133000.0),
 np.float64(135000.0),
 np.float64(137600.0),
 np.float64(140000.0),
 np.float64(141064.5),
 np.float64(142275.0),
 np.float64(142300.0),
 np.float64(142361.0),
 np.float64(142475.25),
 np.float64(144500.0),
 np.float64(145153.2),
 np.float64(148611.2),
 np.float64(149720.0),
 np.float64(150215.0),
 np.float64(150420.0),
 np.float64(150974.4),
 np.float64(152382.0),
 np.float64(154700.0),
 np.float64(155000.0),
 np.float64(159700.0),
 np.float64(159873.1),
 np.float64(160000.0),
 np.float64(160500.0),
 np.float64(162600.0),
 np.float64(163440.0),
 np.float64(163530.0),
 np.float64(165000.0),
 np.float64(167601.6),
 np.float64(168700.0),
 np.float64(170000.0),
 np.float64(171093.75),
 np.float64(171300.0),
 np.float64(174700.0),
 np.float64(175000.0),
 np.float64(175380.0),
 np.float64(175673.4),
 np.float64(176510.0),
 np.float64(177884.25),
 np.float64(179032.95),
 np.float64(180000.0),
 np.float64(180600.0),
 np.float64(180900.0),
 np.float64(181441.5),
 np.float64(183860.72),
 np.float64(183960.0),
 np.float64(184999.62),
 np.float64(185600.0),
 np.float64(185800.0),
 np.float64(186224.0),
 np.float64(187742.699),
 np.float64(188086.0),
 np.float64(188719.0),
 np.float64(189127.0),
 np.float64(189314.0),
 np.float64(189319.0),
 np.float64(189479.0),
 np.float64(189497.0),
 np.float64(189600.0),
 np.float64(189743.2),
 np.float64(189967.0),
 np.float64(190000.0),
 np.float64(190005.97),
 np.float64(190008.0),
 np.float64(190800.0),
 np.float64(191118.38),
 np.float64(191374.0),
 np.float64(193496.0),
 np.float64(194625.0),
 np.float64(195000.0),
 np.float64(196450.4),
 np.float64(197025.0),
 np.float64(197366.0),
 np.float64(199301.0),
 np.float64(200000.0),
 np.float64(200034.315),
 np.float64(200625.0),
 np.float64(200843.0),
 np.float64(201110.215),
 np.float64(201159.0),
 np.float64(201450.0),
 np.float64(201602.15),
 np.float64(204020.0),
 np.float64(205000.0),
 np.float64(205040.0),
 np.float64(205633.7),
 np.float64(207000.0),
 np.float64(208019.2),
 np.float64(208125.0),
 np.float64(208560.0),
 np.float64(209736.02),
 np.float64(210000.0),
 np.float64(210940.0),
 np.float64(211420.0),
 np.float64(212000.0),
 np.float64(212800.0),
 np.float64(212883.0),
 np.float64(212891.36),
 np.float64(213295.0),
 np.float64(213300.0),
 np.float64(213318.55),
 np.float64(213461.1),
 np.float64(213461.103),
 np.float64(214375.0),
 np.float64(214789.9),
 np.float64(215228.0),
 np.float64(216389.0),
 np.float64(217161.4),
 np.float64(217729.8),
 np.float64(217877.1),
 np.float64(219184.0),
 np.float64(219865.5),
 np.float64(220000.0),
 np.float64(220805.0),
 np.float64(221415.0),
 np.float64(222084.9),
 np.float64(222568.24),
 np.float64(222780.0),
 np.float64(222880.0),
 np.float64(223568.0),
 np.float64(224400.0),
 np.float64(224640.0),
 np.float64(225000.0),
 np.float64(225150.0),
 np.float64(225304.0),
 np.float64(225630.0),
 np.float64(227000.0),
 np.float64(228039.0),
 np.float64(228125.0),
 np.float64(228480.0),
 np.float64(229567.0),
 np.float64(229635.375),
 np.float64(229811.0),
 np.float64(229825.9),
 np.float64(230000.0),
 np.float64(230120.0),
 np.float64(230407.0),
 np.float64(231325.0),
 np.float64(231423.5),
 np.float64(231828.0),
 np.float64(234406.0),
 np.float64(235000.0),
 np.float64(235109.0),
 np.float64(235280.0),
 np.float64(235401.0),
 np.float64(236500.0),
 np.float64(237000.0),
 np.float64(237179.0),
 np.float64(237180.0),
 np.float64(239700.0),
 np.float64(239739.0),
 np.float64(240000.0),
 np.float64(241000.0),
 np.float64(241363.65),
 np.float64(241922.0),
 np.float64(242738.0),
 np.float64(242755.2),
 np.float64(243515.0),
 np.float64(244017.6),
 np.float64(244780.0),
 np.float64(245000.0),
 np.float64(245244.21),
 np.float64(245514.0),
 np.float64(245563.0),
 np.float64(245579.0),
 np.float64(246761.0),
 np.float64(246840.0),
 np.float64(246959.2),
 np.float64(247179.0),
 np.float64(248000.0),
 np.float64(250000.0),
 np.float64(250308.0),
 np.float64(250475.0),
 np.float64(250700.0),
 np.float64(250962.0),
 np.float64(250963.0),
 np.float64(251393.0),
 np.float64(251600.0),
 np.float64(251624.0),
 np.float64(251634.0),
 np.float64(251922.0),
 np.float64(252038.0),
 np.float64(252694.0),
 np.float64(252739.0),
 np.float64(254000.0),
 np.float64(254300.0),
 np.float64(255000.0),
 np.float64(255484.0),
 np.float64(259200.0),
 np.float64(259475.0),
 np.float64(259839.9),
 np.float64(259840.0),
 np.float64(260000.0),
 np.float64(260024.0),
 np.float64(260048.7),
 np.float64(261538.0),
 np.float64(263169.0),
 np.float64(264000.0),
 np.float64(264275.0),
 np.float64(264600.0),
 np.float64(264617.6),
 np.float64(265000.0),
 np.float64(268386.0),
 np.float64(269000.0),
 np.float64(272565.0),
 np.float64(274275.0),
 np.float64(275000.0),
 np.float64(277500.0),
 np.float64(279000.0),
 np.float64(280000.0),
 np.float64(283000.0),
 np.float64(283595.0),
 np.float64(285000.0),
 np.float64(287864.0),
 np.float64(288000.0),
 np.float64(289900.0),
 np.float64(290000.0),
 np.float64(294099.0),
 np.float64(296400.0),
 np.float64(297871.0),
 np.float64(298000.0),
 np.float64(299700.0),
 np.float64(300000.0),
 np.float64(301500.0),
 np.float64(302430.0),
 np.float64(305000.0),
 np.float64(305022.0),
 np.float64(305040.0),
 np.float64(305400.0),
 np.float64(305694.0),
 np.float64(305800.0),
 np.float64(306259.0),
 np.float64(306500.0),
 np.float64(307200.0),
 np.float64(307400.0),
 np.float64(308252.0),
 np.float64(308256.0),
 np.float64(308700.0),
 np.float64(310000.0),
 np.float64(310703.0),
 np.float64(311325.0),
 np.float64(311573.0),
 np.float64(312000.0),
 np.float64(312075.0),
 np.float64(312399.0),
 np.float64(312500.0),
 np.float64(314533.8),
 np.float64(315382.0),
 np.float64(316540.0),
 np.float64(317000.0),
 np.float64(318000.0),
 np.float64(319300.0),
 np.float64(320114.0),
 np.float64(321895.0),
 np.float64(327461.0),
 np.float64(327920.0),
 np.float64(328629.0),
 np.float64(328879.0),
 np.float64(330000.0),
 np.float64(330772.0),
 np.float64(331361.0),
 np.float64(334138.0),
 np.float64(334148.0),
 np.float64(335941.0),
 np.float64(336196.0),
 np.float64(336741.0),
 np.float64(340000.0),
 np.float64(341400.0),
 np.float64(343959.0),
 np.float64(344850.0),
 np.float64(344859.0),
 np.float64(346196.0),
 np.float64(349482.0),
 np.float64(360000.0),
 np.float64(366000.0),
 np.float64(366424.0),
 np.float64(372394.0),
 np.float64(372400.0),
 np.float64(377868.0),
 np.float64(378364.0),
 np.float64(378700.0),
 np.float64(385200.0),
 np.float64(390884.0),
 np.float64(405000.0),
 np.float64(425000.0),
 np.float64(430000.0),
 np.float64(433187.0),
 np.float64(480871.0),
 np.float64(516250.0),
 np.float64(543364.0),
 np.float64(557800.0),
 np.float64(625000.0),
 np.float64(700000.0),
 np.float64(750000.0)}

In [ ]:
sf_hcomp_df.head()

,Location/Business Unit,Employee Lived Name,Job Code,Job Code Description,Most Recent Date of Hire in Empl Rcd,Job Expected End Date,Employee Class,Employee Class Description,FTE,Job Hourly Rate,...,EE Work Location Address 1,EE Work Location Address 2,EE Work Location Address 3,EE Work Location Floor,EE Work Location City,EE Work Location State,EE Work Location Zip Code,EE Work Email Address,EE Work Phone,Employee Relation Description
149882,SFCMP,"Hansen,Alex",001732,HS ASST CLIN PROF-HCOMP,2023-12-01,2026-06-30,9,Academic: Faculty,1.0,61.350575,...,1500 Owens Street,1500 Owens,400,04,San Francisco,CA,94158,alex.hansen@ucsf.edu,Pending,"All Others, Not Confidential"
149902,SFCMP,"Long,Arthur",001732,HS ASST CLIN PROF-HCOMP,2017-02-06,2026-06-30,9,Academic: Faculty,1.0,68.151339,...,1500 Owens Street,1500 Owens,400,04,San Francisco,CA,94158,Arthur.Long@ucsf.edu,Pending,"All Others, Not Confidential"
149921,SFCMP,"Ann,Vincent",001732,HS ASST CLIN PROF-HCOMP,2020-11-23,2026-06-30,9,Academic: Faculty,1.0,64.655172,...,1855 Folsom Street,Mission Center Building,563,05,San Francisco,CA,94103,Vincent.Ann@ucsf.edu,415/353-7598,"All Others, Not Confidential"
149926,SFCMP,"Dien,Alexander",001732,HS ASST CLIN PROF-HCOMP,2020-12-28,2026-06-30,9,Academic: Faculty,1.0,64.655172,...,1855 Folsom Street,Mission Center Building,563,05,San Francisco,CA,94103,Alexander.Dien@ucsf.edu,Pending,"All Others, Not Confidential"
149927,SFCMP,"Freitas,Nina",001732,HS ASST CLIN PROF-HCOMP,2024-10-01,2026-06-30,9,Academic: Faculty,0.8,70.162838,...,1855 Folsom Street,Mission Center Building,563,05,San Francisco,CA,94103,Nina.Freitas@ucsf.edu,Pending,"All Others, Not Confidential"

Warning: Total number of columns (25) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
sf_hcomp_df.to_excel('SF_HS ASST CLIN PROF-HCOMP1.xlsx', index=False, engine='openpyxl')