<a href="https://colab.research.google.com/github/tougheye/Data_processing/blob/main/UPTE_Payscale_TCS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This code would take in Job Summary Reports received from UC and convert them into tables for each campus and job titles producing the step tables.

In [1]:
import pandas as pd

tcs_backend_folder = "/content/drive/MyDrive/Data/UCOP_Job_Codes_Summary"

In [2]:
tcs_backend_file = pd.ExcelFile(f'{tcs_backend_folder}/R-349 Job Codes Summary_07282026.xlsx')
tcs_backend_file.sheet_names
#

['Job Code Review',
 'Represented Job Codes',
 'Non-Represented Job Codes',
 'Shift and On Call Rates']

In [3]:
tcs_backend_tabs = tcs_backend_file.sheet_names
represented_job_codes_df = tcs_backend_file.parse('Represented Job Codes', skiprows=9, skipfooter=2)
represented_job_codes_df.shape

(128803, 30)

In [11]:
represented_job_codes_df.columns

Index(['Salary Plan SETID', 'Status - Job Code', 'Job Code',
       'Job Code Description', 'Eff Date - Salary Grade',
       'Salary Grade Eff Status', 'Union Code', 'FLSA Status',
       'Personnel Program/CLASS_INDC', 'OnCall Eligible', 'Elig Shift Diff',
       'Sal Plan', 'Sal Plan Description', 'Grade', 'Rate Code', 'Comp Freq',
       'UCPATH Step', 'UC  Half Step', 'Hrly Rate', 'Monthly Rt', 'Annual Rt',
       'CTO/OS Subgroup', 'CTO Description', 'SOC Code',
       'SOC Code Description', 'Census/OCC Code',
       'Census/OCC Code Description', 'EEO1 Reporting Code',
       'EEO1 Reporting Cod Description', 'OSHPD Code'],
      dtype='object')

In [4]:
represented_active_df = represented_job_codes_df[represented_job_codes_df['Salary Grade Eff Status'] == 'A']
represented_active_df.shape

(109454, 30)

Filter the large dataset for UPTE bargaining unit titles

In [5]:
upte_represented_job_codes_df = represented_active_df[represented_active_df['Union Code'].isin(['HX', 'RX', 'TX'])]
upte_represented_job_codes_df.shape

(40459, 30)

**Need to further filter the values based on the "Eff Date - Salary Grade" column values with the most recent date.**

In [6]:
upte_job_title_Eff_date_cnt = upte_represented_job_codes_df.groupby(['Salary Plan SETID','Job Code Description'])['Eff Date - Salary Grade'].nunique().reset_index(name='Date Count')
multi_eff_date_setid_jobCode_cnt = upte_job_title_Eff_date_cnt.where(upte_job_title_Eff_date_cnt['Date Count'] > 1).dropna()

From the Active UPTE represented job codes, filter out the ones that have Effective date from before July 1, 2026. Later to be checked if they have other copies from a date later than July 1. 2026.

In [7]:
# filtered UPTE represented job codes
titles_not_updated = upte_represented_job_codes_df[upte_represented_job_codes_df['Eff Date - Salary Grade'] < '2026-07-01']
titles_not_updated.shape   # 1192 rows

(1192, 30)

In [8]:
# get the latest effective date for each job title
latest_eff_date_df = upte_represented_job_codes_df.groupby(['Salary Plan SETID','Job Code Description'])['Eff Date - Salary Grade'].max().reset_index(name='Latest Effective Date')

In [9]:
# Merge to get the latest effective date for each job title for which the effective date is before July 1, 2026
# WILL KEEP THIS ONE TO LATER TAKE CARE OF
titles_not_updated_w_max_date = titles_not_updated.merge(latest_eff_date_df, on=['Salary Plan SETID', 'Job Code Description'], how='inner')

# Drop the LBNL business units as they are not supposed to receive the 5% ATB in July 2026
titles_not_updated_w_max_date = titles_not_updated_w_max_date[titles_not_updated_w_max_date['Salary Plan SETID'] != 'LBNL1']
titles_not_updated_w_max_date.shape       # 1130 rows

(1130, 31)

Filter out the titles whose latest effective date is from before July 1, 2026

In [11]:

titles_not_updated_final = titles_not_updated_w_max_date[titles_not_updated_w_max_date['Latest Effective Date'] < '2026-07-01']

# get the job titles and locations of the titles not updated
# titles_not_updated_final[col_list].drop_duplicates(subset=['Salary Plan SETID', 'Job Code Description'], keep='first').sort_values('Job Code Description')
#

,Salary Plan SETID,Status - Job Code,Job Code,Job Code Description,Eff Date - Salary Grade,Latest Effective Date,UCPATH Step,UC Half Step,Hrly Rate,Monthly Rt,Annual Rt
229,SCCMP,A,004460,BEH HEALTH COUNSELOR 4 HX,2023-07-01,2023-07-01,NaN,NaN,NaN,NaN,NaN
523,SFCMP,I,004571,BEH HEALTH PSYCHIATRIC PROFL 2,2023-12-19,2023-12-19,NaN,NaN,NaN,NaN,NaN
81,LACMP,I,004571,BEH HEALTH PSYCHIATRIC PROFL 2,2023-12-19,2023-12-19,NaN,NaN,NaN,NaN,NaN
474,SDMED,I,004571,BEH HEALTH PSYCHIATRIC PROFL 2,2023-12-19,2023-12-19,NaN,NaN,NaN,NaN,NaN
70,IRMED,I,004571,BEH HEALTH PSYCHIATRIC PROFL 2,2023-12-19,2023-12-19,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
568,SFCMP,A,006396,USER EXP DESIGNER 4 TX GF,2026-03-01,2026-03-01,NaN,NaN,NaN,NaN,NaN
94,LACMP,A,006396,USER EXP DESIGNER 4 TX GF,2026-03-01,2026-03-01,NaN,NaN,NaN,NaN,NaN
1191,UCOP1,A,006396,USER EXP DESIGNER 4 TX GF,2026-03-01,2026-03-01,NaN,NaN,NaN,NaN,NaN
8,BKCMP,A,006397,USER EXP DESIGNER 5 TX GF,2026-03-01,2026-03-01,NaN,NaN,NaN,NaN,NaN
67,IRCMP,A,006397,USER EXP DESIGNER 5 TX GF,2026-03-01,2026-03-01,NaN,NaN,NaN,NaN,NaN

In [12]:
multi_eff_date_setid_jobCode_cnt

     Salary Plan SETID       Job Code Description  Date Count
22               BKCMP  BEH HEALTH COUNSELOR 3 HX         2.0
284              DVCMP  BEH HEALTH COUNSELOR 3 HX         2.0
333              DVCMP          CLIN LAB SCI APPR         2.0
580              DVCMP               SYS ADM 3 TX         2.0
638              DVMED  BEH HEALTH COUNSELOR 3 HX         2.0
...                ...                        ...         ...
4237             SFCMP        REHAB SVC SPEC 4 HX         2.0
4253             SFCMP       SPEECH PATHOLOGIST 1         2.0
4255             SFCMP       SPEECH PATHOLOGIST 2         2.0
4257             SFCMP    SPEECH PATHOLOGIST 3 HX         2.0
4333             SFMED  BEH HEALTH COUNSELOR 3 HX         2.0

[91 rows x 3 columns]

**FINAL PROCESSING OF THE OUTPUT FILES**

In [13]:

# Filter the rows with the latest effective date for each job title that have multiple effective dates
# THIS DF WILL BE CONCATENATED LATER TO CREATE THE FINAL DF WITH THE LATEST EFFECTIVE DATE

upte_represented_max_eff_date_df = upte_represented_job_codes_df\
    .merge(multi_eff_date_setid_jobCode_cnt,
           on=['Salary Plan SETID', 'Job Code Description'],
           how='inner')\
    .sort_values('Eff Date - Salary Grade', ascending=False)\
    .drop_duplicates(['Salary Plan SETID', 'Job Code Description', 'UCPATH Step', 'UC  Half Step'],
                     keep='first')

upte_represented_max_eff_date_df.shape

(1566, 31)

In [14]:
# Create unique identifier both in the master UPTE represented df and multiple effective date df

represented_key = upte_represented_job_codes_df['Salary Plan SETID'] + ' - ' + upte_represented_job_codes_df['Union Code'] + ' - ' + upte_represented_job_codes_df['Job Code Description']
unmatched_key = upte_represented_max_eff_date_df['Salary Plan SETID'] + ' - ' + upte_represented_max_eff_date_df['Union Code'] + ' - ' + upte_represented_max_eff_date_df['Job Code Description']

# filtering out the multiple effective date rows from the UPTE represented df based on the unique identifier keys
upte_represented_one_date_df = upte_represented_job_codes_df[~represented_key.isin(unmatched_key)]

In [15]:
upte_represented_final_df = pd.concat([upte_represented_one_date_df, upte_represented_max_eff_date_df.drop('Date Count', axis=1)])
upte_represented_final_df.shape

(39392, 30)

In [16]:
cols_to_keep = ['Salary Plan SETID', 'Job Code', 'Job Code Description', 'Union Code','FLSA Status', 'OnCall Eligible', 'Elig Shift Diff',
                'Rate Code', 'UCPATH Step', 'UC  Half Step', 'Hrly Rate', 'Monthly Rt', 'Annual Rt', 'Grade', 'Rate Code',
                'Eff Date - Salary Grade', 'Salary Grade Eff Status']
#

Create the Refined DF by keeping only the necessary columns to produce the final list-


1.   'Salary Plan SETID' - Excel file name
2.   'Job Code'
3.   'Job Code Description'    - Second level grouping
1.   'Union Code'.        - Tab name in Excel file
2.   'FLSA Status'        - In Group label for the second level
4.   'OnCall Eligible'.   - In Group label for the second level
5.   'Elig Shift Diff'.   - In Group label for the second level
6.   'Rate Code'.         - In Group label for the second level
7.   'Hrly Rate'          - transpose to column
8.   'Monthly Rt'         - transpose to column
9.   'Annual Rt'          - transpose to column
10.  'Short Descr'.       - First level grouping in tab
11.  'UCPATH Step'        - column label  
12.  'UC  Half Step'      - column label 2

In [17]:
upte_represented_job_codes_refined_df = upte_represented_final_df[cols_to_keep]
upte_represented_job_codes_refined_df.head()

,Salary Plan SETID,Job Code,Job Code Description,Union Code,FLSA Status,OnCall Eligible,Elig Shift Diff,Rate Code,UCPATH Step,UC Half Step,Hrly Rate,Monthly Rt,Annual Rt,Grade,Rate Code,Eff Date - Salary Grade,Salary Grade Eff Status
217,BKCMP,004031,LIFEGUARD,TX,N,Y,Y,UCHRLY,1.0,1.0,27.04,4704.96,56459.52,100,UCHRLY,2026-07-05,A
218,BKCMP,004031,LIFEGUARD,TX,N,Y,Y,UCHRLY,2.0,1.5,27.58,4798.92,57587.04,100,UCHRLY,2026-07-05,A
219,BKCMP,004031,LIFEGUARD,TX,N,Y,Y,UCHRLY,7.0,4.0,30.44,5296.56,63558.72,100,UCHRLY,2026-07-05,A
220,BKCMP,004031,LIFEGUARD,TX,N,Y,Y,UCHRLY,4.0,2.5,28.70,4993.80,59925.60,100,UCHRLY,2026-07-05,A
221,BKCMP,004031,LIFEGUARD,TX,N,Y,Y,UCHRLY,5.0,3.0,29.26,5091.24,61094.88,100,UCHRLY,2026-07-05,A

In [18]:
import math
# dictionary to store the job details
job_details_dict = {}

business_unit_list = upte_represented_job_codes_refined_df['Salary Plan SETID'].unique()

for business_unit in business_unit_list:
  job_details_dict[business_unit] = {}
  #define the current business unit
  current_bus_unit = upte_represented_job_codes_refined_df[
      upte_represented_job_codes_refined_df['Salary Plan SETID'] == business_unit]

  # loop through the bargaining units
  for bargaining_unit in current_bus_unit['Union Code'].unique():
    job_details_dict[business_unit][bargaining_unit] = {}

    # define the current bargaining unit
    current_bus_unit_bu_df = current_bus_unit[current_bus_unit['Union Code'] == bargaining_unit]

    title_list = sorted(current_bus_unit_bu_df['Job Code Description'].unique())

      # loop through the job_code in the current business unit
    for title in title_list:
      step_col = current_bus_unit_bu_df[current_bus_unit_bu_df['Job Code Description'] == title]['UCPATH Step'].unique()
      step_list = sorted([ float(k) if not math.isnan(k) else 0 for k in step_col])
      half_step_col = current_bus_unit_bu_df[current_bus_unit_bu_df['Job Code Description'] == title]['UC  Half Step'].unique()
      half_step_list = sorted([ float(k) if not math.isnan(k) else 0 for k in half_step_col])
      # create a check valve to indicate if the half steps are the same as the steps
      half_step_indicat = 'N' if step_list == half_step_list else 'Y'
      job_details_dict[business_unit][bargaining_unit][title] = {
            'Title' : title,
            'Job Code' : current_bus_unit_bu_df[current_bus_unit_bu_df['Job Code Description'] == title]['Job Code'].unique(),
            'TCS Effective Date': current_bus_unit_bu_df[current_bus_unit_bu_df['Job Code Description'] == title]['Eff Date - Salary Grade'].unique().strftime("%m/%d/%Y"),
            'Exempt Status' : current_bus_unit_bu_df[current_bus_unit_bu_df['Job Code Description'] == title]['FLSA Status'].unique(),
            'OnCall Eligibility Status' : current_bus_unit_bu_df[current_bus_unit_bu_df['Job Code Description'] == title]['OnCall Eligible'].unique(),
            'Shift Differential Status' : current_bus_unit_bu_df[current_bus_unit_bu_df['Job Code Description'] == title]['Elig Shift Diff'].unique(),
            'Steps' : step_list,
            'Half Steps' : half_step_list,
            'Half Steps Status' : half_step_indicat,
            'Hourly Rates': sorted(current_bus_unit_bu_df[current_bus_unit_bu_df['Job Code Description'] == title]['Hrly Rate'].unique()),
            'Monthly Rates': sorted(current_bus_unit_bu_df[current_bus_unit_bu_df['Job Code Description'] == title]['Monthly Rt'].unique()),
            'Annual Rates': sorted(current_bus_unit_bu_df[current_bus_unit_bu_df['Job Code Description'] == title]['Annual Rt'].unique())
    }

**Differential processing**

In [19]:
# Make the differential df
differential_full_df = tcs_backend_file.parse('Shift and On Call Rates', skiprows=9, skipfooter=2)
differential_full_df.shape

(33738, 11)

In [20]:
# isolate UPTE title differentials
upte_differential_df = differential_full_df.merge(upte_represented_job_codes_df[['Salary Plan SETID', 'Job Code', 'Union Code']], on=['Salary Plan SETID', 'Job Code'], how='inner')\
                                  .drop_duplicates().sort_values(['Salary Plan SETID','Job Description'])
upte_differential_df.shape
#

(6776, 12)

Transpose the dataframe based on the Earn Code Descriptions.

The Shift On Call Type column generally follow Earn Code Description.

There are 2 Shift On Call Types OCR and SD0 that have 2 different Earn Code Descriptions. However, UPTE does not have any differential of OCR2 and SDO1. In future, we should check them.

In [21]:
upte_differential_transposed_df = upte_differential_df.pivot_table(index=['Salary Plan SETID', 'Job Code', 'Job Description','Effective Date','Effective Status','Union Code'], \
                           columns='Earn Code Description', values='Hourly Rate', aggfunc = 'max')

In [22]:
# reset index to get the column names back from the pivot table

upte_differential_transposed_df.reset_index(inplace=True)
upte_differential_transposed_df = upte_differential_transposed_df.sort_values(by=['Salary Plan SETID','Job Description'])
# upte_differential_transposed_df.head()

In [23]:
# Change the Effective Date column to datetime format

upte_differential_transposed_df['Effective Date'] = \
        upte_differential_transposed_df['Effective Date'].dt.strftime('%m/%d/%Y')

In [34]:
upte_differential_transposed_df.head()

Earn Code Description,Salary Plan SETID,Job Code,Job Description,Effective Date,Effective Status,Union Code,Evening Shift Differential,NRA Charge Differential,Night Shift Differential *,Non Prod Evening Shift Diff,Non Prod Night Shift Diff,Non Prod Weekend Shift Diff,Time On Call,Weekend Day Shift Differential,Weekend Eve Shift Differential,Weekend Night Shift Differentl
77,BKCMP,009537,ANML HEALTH TCHN 1,01/01/1930,A,TX,0.72,NaN,0.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,BKCMP,009536,ANML HEALTH TCHN 2,01/01/1930,A,TX,0.67,NaN,0.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,BKCMP,009535,ANML HEALTH TCHN 3,01/01/1930,A,TX,0.57,NaN,0.57,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,BKCMP,009525,ANML TCHN,01/01/1930,A,TX,0.67,NaN,0.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,BKCMP,009523,ANML TCHN PRN,01/01/1930,A,TX,0.67,NaN,0.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Save the job details of interest in a dictionary

create 18 Dataframe structures and write them to EXCEL with separate tabs for each bargaining unit

In [ ]:
# take out UCOP and LBNL to prevent the code from crashing due to not having "HX" in those business units
folder_path = "/content/drive/MyDrive/UPTE Step Scales & Differentials"

campus_bu_list = [bus_unit for bus_unit in business_unit_list if bus_unit not in ['UCOP1', 'LBNL1']]

# create dictionary to capture the titles that have duplicate steps with different pay rates
manual_check_dict = {}

# Loop through the business units
for bus_unit in campus_bu_list:

    barg_units = ['HX', 'RX', 'TX']

    # start the excel writer outside the loop
    with pd.ExcelWriter(f'{folder_path}/{bus_unit}/{bus_unit}_tcs_scales_&_differentials_07282026.xlsx', engine='openpyxl') as writer:

# Loop through the bargaining units
      for barg_unit in barg_units:

        campus_bu = job_details_dict[bus_unit][barg_unit]
        # save the job titles in the bargaining unit in a list from the first layer of the dictionary
        curr_bu = pd.DataFrame(campus_bu).T.index.to_list()

        # Create a list to save all the resulting DataFrames in the current campus' bargaining unit
        campus_bu_list = []

        print(f"currently processing {bus_unit}'s {barg_unit}")


# loop through the job titles in the current bargaining unit
        for title in curr_bu:
          data = campus_bu[title]
          # Correctly construct header_row as a single-row DataFrame with named columns
          header_row = pd.DataFrame([{
              'Title': data['Title'],
              'Job Code': data['Job Code'][0],
              'TCS Effective Date': data['TCS Effective Date'][0],
              'Exempt Status': data['Exempt Status'][0],
              'OnCall Eligibility Status': data['OnCall Eligibility Status'][0],
              'Shift Differential Status': data['Shift Differential Status'][0]
          }])


          steps = [int(k) for k in data['Steps']] if data['Half Steps Status'] == 'N' else data['Half Steps']

          # Apparently, some titles have multiple same steps and half steps. Need to manually audit them
          if len(steps) == len(data['Hourly Rates']) == len(data['Monthly Rates']) == len(data['Annual Rates']):
            hourly_rates_row = pd.DataFrame([{'Row_Type': 'Hourly Rates', **{f'Step_{s}': f'${r:,.2f}' for s, r in zip(steps, data['Hourly Rates'])}}])
            monthly_rates_row = pd.DataFrame([{'Row_Type': 'Monthly Rates', **{f'Step_{s}': f'${r:,.2f}' for s, r in zip(steps, data['Monthly Rates'])}}])
            annual_rates_row = pd.DataFrame([{'Row_Type': 'Annual Rates', **{f'Step_{s}': f'${r:,.2f}' for s, r in zip(steps, data['Annual Rates'])}}])
            final_df = pd.concat([header_row,  hourly_rates_row, monthly_rates_row, annual_rates_row], ignore_index=True)

            trailing_empty_row = pd.DataFrame([[None] * len(final_df.columns)] * 3, columns=final_df.columns)
            final_df = pd.concat([final_df, trailing_empty_row], ignore_index=True)
            campus_bu_list.append(final_df)

# upload the manual check data in the dictionary to the excel file
          else:
            manual_job_code = f"{bus_unit} - {barg_unit} - {title}"
            manual_check_dict[manual_job_code] = {}
            manual_check_dict[manual_job_code]['Job Code Description'] = title
            manual_check_dict[manual_job_code]['Job Code'] = data['Job Code'][0]
            manual_check_dict[manual_job_code]['Salary Plan SETID'] = bus_unit
            manual_check_dict[manual_job_code]['Union Code'] = barg_unit


          for ind in range(len(campus_bu_list)):
            campus_bu_list[ind].to_excel(writer, sheet_name=barg_unit, startrow=ind*7, index=False)

          differential_df = upte_differential_transposed_df[(upte_differential_transposed_df['Salary Plan SETID'] == bus_unit) & \
                                                            (upte_differential_transposed_df['Union Code'] == barg_unit)]
          differential_df.to_excel(writer, sheet_name=f"{barg_unit}_Differential", index=False)

currently processing BKCMP's HX
currently processing BKCMP's RX
currently processing BKCMP's TX
currently processing DVCMP's HX
currently processing DVCMP's RX
currently processing DVCMP's TX
currently processing DVMED's HX
currently processing DVMED's RX
currently processing DVMED's TX
currently processing IRCMP's HX
currently processing IRCMP's RX
currently processing IRCMP's TX
currently processing IRMED's HX
currently processing IRMED's RX
currently processing IRMED's TX
currently processing LACMP's HX
currently processing LACMP's RX
currently processing LACMP's TX
currently processing LAMED's HX
currently processing LAMED's RX
currently processing LAMED's TX
currently processing MECMP's HX
currently processing MECMP's RX
currently processing MECMP's TX
currently processing RVCMP's HX
currently processing RVCMP's RX
currently processing RVCMP's TX
currently processing SBCMP's HX
currently processing SBCMP's RX
currently processing SBCMP's TX
currently processing SCCMP's HX
currently processing SCCMP's RX
currently processing SCCMP's TX
currently processing SDCMP's HX
currently processing SDCMP's RX
currently processing SDCMP's TX
currently processing SDMED's HX
currently processing SDMED's RX
currently processing SDMED's TX

In [37]:
# Now output the UCOP and LBNL with only RX and TX unit
# take out UCOP and LBNL to prevent the code from crashing due to not having "HX" in those business units
folder_path = "/content/drive/MyDrive/UPTE Step Scales & Differentials"
remaining_bu_list = ['UCOP1', 'LBNL1']

for bus_unit in remaining_bu_list:

  barg_units = ['RX', 'TX']

  # start the excel writer outside the loop
  with pd.ExcelWriter(f'{folder_path}/{bus_unit}/{bus_unit}_tcs_scales_&_differentials_07282026.xlsx', engine='openpyxl') as writer:

# Loop through the bargaining units
    for barg_unit in barg_units:

      campus_bu = job_details_dict[bus_unit][barg_unit]
      # save the job titles in the bargaining unit in a list from the first layer of the dictionary
      curr_bu = pd.DataFrame(campus_bu).T.index.to_list()

      # Create a list to save all the resulting DataFrames in the current campus' bargaining unit
      campus_bu_list = []

      print(f"currently processing {bus_unit}'s {barg_unit}")


# loop through the job titles in the current bargaining unit
      for title in curr_bu:
        data = campus_bu[title]
        # Correctly construct header_row as a single-row DataFrame with named columns
        header_row = pd.DataFrame([{
            'Title': data['Title'],
            'Job Code': data['Job Code'][0],
            'TCS Effective Date': data['TCS Effective Date'][0],
            'Exempt Status': data['Exempt Status'][0],
            'OnCall Eligibility Status': data['OnCall Eligibility Status'][0],
            'Shift Differential Status': data['Shift Differential Status'][0]
        }])


        steps = [int(k) for k in data['Steps']] if data['Half Steps Status'] == 'N' else data['Half Steps']

        # Apparently, some titles have multiple same steps and half steps. Need to manually audit them
        if len(steps) == len(data['Hourly Rates']) == len(data['Monthly Rates']) == len(data['Annual Rates']):
          hourly_rates_row = pd.DataFrame([{'Row_Type': 'Hourly Rates', **{f'Step_{s}': f'${r:,.2f}' for s, r in zip(steps, data['Hourly Rates'])}}])
          monthly_rates_row = pd.DataFrame([{'Row_Type': 'Monthly Rates', **{f'Step_{s}': f'${r:,.2f}' for s, r in zip(steps, data['Monthly Rates'])}}])
          annual_rates_row = pd.DataFrame([{'Row_Type': 'Annual Rates', **{f'Step_{s}': f'${r:,.2f}' for s, r in zip(steps, data['Annual Rates'])}}])
          final_df = pd.concat([header_row,  hourly_rates_row, monthly_rates_row, annual_rates_row], ignore_index=True)

          trailing_empty_row = pd.DataFrame([[None] * len(final_df.columns)] * 3, columns=final_df.columns)
          final_df = pd.concat([final_df, trailing_empty_row], ignore_index=True)
          campus_bu_list.append(final_df)

# upload the manual check data in the dictionary to the excel file
        else:
          manual_job_code = f"{bus_unit} - {barg_unit} - {title}"
          manual_check_dict[manual_job_code] = {}
          manual_check_dict[manual_job_code]['Job Code Description'] = title
          manual_check_dict[manual_job_code]['Job Code'] = data['Job Code'][0]
          manual_check_dict[manual_job_code]['Salary Plan SETID'] = bus_unit
          manual_check_dict[manual_job_code]['Union Code'] = barg_unit


        for ind in range(len(campus_bu_list)):
          campus_bu_list[ind].to_excel(writer, sheet_name=barg_unit, startrow=ind*7, index=False)


# add the differential tabs
      differential_df = upte_differential_transposed_df[(upte_differential_transposed_df['Salary Plan SETID'] == bus_unit) & \
                                                        (upte_differential_transposed_df['Union Code'] == barg_unit)]
      differential_df.to_excel(writer, sheet_name=f"{barg_unit}_Differential", index=False)

currently processing UCOP1's RX
currently processing UCOP1's TX
currently processing LBNL1's RX
currently processing LBNL1's TX

Finally, some UCANR job titles will remain for manual check. Export the manual check dataframe and see if there are titles from any other SETID left

In [35]:
manual_check_dict

{'UCANR - RX - SRA 1': {'Job Code Description': 'SRA 1',
  'Job Code': '009613',
  'Salary Plan SETID': 'UCANR',
  'Union Code': 'RX'},
 'UCANR - RX - SRA 2': {'Job Code Description': 'SRA 2',
  'Job Code': '009612',
  'Salary Plan SETID': 'UCANR',
  'Union Code': 'RX'},
 'UCANR - RX - SRA 2 NEX': {'Job Code Description': 'SRA 2 NEX',
  'Job Code': '009617',
  'Salary Plan SETID': 'UCANR',
  'Union Code': 'RX'},
 'UCANR - RX - SRA 3': {'Job Code Description': 'SRA 3',
  'Job Code': '009611',
  'Salary Plan SETID': 'UCANR',
  'Union Code': 'RX'},
 'UCANR - RX - SRA 4': {'Job Code Description': 'SRA 4',
  'Job Code': '009610',
  'Salary Plan SETID': 'UCANR',
  'Union Code': 'RX'},
 'UCANR - TX - ANML HEALTH TCHN 1': {'Job Code Description': 'ANML HEALTH TCHN 1',
  'Job Code': '009537',
  'Salary Plan SETID': 'UCANR',
  'Union Code': 'TX'},
 'UCANR - TX - ANML HEALTH TCHN 2': {'Job Code Description': 'ANML HEALTH TCHN 2',
  'Job Code': '009536',
  'Salary Plan SETID': 'UCANR',
  'Union Code': 'TX'},
 'UCANR - TX - ANML HEALTH TCHN 3': {'Job Code Description': 'ANML HEALTH TCHN 3',
  'Job Code': '009535',
  'Salary Plan SETID': 'UCANR',
  'Union Code': 'TX'},
 'UCANR - TX - ANML HEALTH TCHN 4 NEX': {'Job Code Description': 'ANML HEALTH TCHN 4 NEX',
  'Job Code': '009534',
  'Salary Plan SETID': 'UCANR',
  'Union Code': 'TX'},
 'UCANR - TX - ARTIST': {'Job Code Description': 'ARTIST',
  'Job Code': '006103',
  'Salary Plan SETID': 'UCANR',
  'Union Code': 'TX'},
 'UCANR - TX - ARTIST SR': {'Job Code Description': 'ARTIST SR',
  'Job Code': '006102',
  'Salary Plan SETID': 'UCANR',
  'Union Code': 'TX'},
 'UCANR - TX - BUS TCHL SUPP ANL 2 TX': {'Job Code Description': 'BUS TCHL SUPP ANL 2 TX',
  'Job Code': '007359',
  'Salary Plan SETID': 'UCANR',
  'Union Code': 'TX'},
 'UCANR - TX - BUS TCHL SUPP ANL 3 TX': {'Job Code Description': 'BUS TCHL SUPP ANL 3 TX',
  'Job Code': '007358',
  'Salary Plan SETID': 'UCANR',
  'Union Code': 'TX'},
 'UCANR - TX - COMPUTER RESC SPEC 1': {'Job Code Description': 'COMPUTER RESC SPEC 1',
  'Job Code': '004805',
  'Salary Plan SETID': 'UCANR',
  'Union Code': 'TX'},
 'UCANR - TX - COMPUTER RESC SPEC 2': {'Job Code Description': 'COMPUTER RESC SPEC 2',
  'Job Code': '004804',
  'Salary Plan SETID': 'UCANR',
  'Union Code': 'TX'},
 'UCANR - TX - EDITOR': {'Job Code Description': 'EDITOR',
  'Job Code': '007684',
  'Salary Plan SETID': 'UCANR',
  'Union Code': 'TX'},
 'UCANR - TX - EDITOR AST': {'Job Code Description': 'EDITOR AST',
  'Job Code': '007685',
  'Salary Plan SETID': 'UCANR',
  'Union Code': 'TX'},
 'UCANR - TX - ILLUSTRATOR': {'Job Code Description': 'ILLUSTRATOR',
  'Job Code': '006113',
  'Salary Plan SETID': 'UCANR',
  'Union Code': 'TX'},
 'UCANR - TX - ILLUSTRATOR AST': {'Job Code Description': 'ILLUSTRATOR AST',
  'Job Code': '006114',
  'Salary Plan SETID': 'UCANR',
  'Union Code': 'TX'},
 'UCANR - TX - ILLUSTRATOR PRN': {'Job Code Description': 'ILLUSTRATOR PRN',
  'Job Code': '006111',
  'Salary Plan SETID': 'UCANR',
  'Union Code': 'TX'},
 'UCANR - TX - ILLUSTRATOR SR': {'Job Code Description': 'ILLUSTRATOR SR',
  'Job Code': '006112',
  'Salary Plan SETID': 'UCANR',
  'Union Code': 'TX'},
 'UCANR - TX - LAB AST 2': {'Job Code Description': 'LAB AST 2',
  'Job Code': '009603',
  'Salary Plan SETID': 'UCANR',
  'Union Code': 'TX'},
 'UCANR - TX - LAB AST 3': {'Job Code Description': 'LAB AST 3',
  'Job Code': '009602',
  'Salary Plan SETID': 'UCANR',
  'Union Code': 'TX'},
 'UCANR - TX - LAB AST 4': {'Job Code Description': 'LAB AST 4',
  'Job Code': '009601',
  'Salary Plan SETID': 'UCANR',
  'Union Code': 'TX'},
 'UCANR - TX - PRODUCER DIR': {'Job Code Description': 'PRODUCER DIR',
  'Job Code': '006214',
  'Salary Plan SETID': 'UCANR',
  'Union Code': 'TX'},
 'UCANR - TX - PRODUCER DIR AST': {'Job Code Description': 'PRODUCER DIR AST',
  'Job Code': '006215',
  'Salary Plan SETID': 'UCANR',
  'Union Code': 'TX'},
 'UCANR - TX - PRODUCER DIR SR': {'Job Code Description': 'PRODUCER DIR SR',
  'Job Code': '006213',
  'Salary Plan SETID': 'UCANR',
  'Union Code': 'TX'},
 'UCANR - TX - WRITER': {'Job Code Description': 'WRITER',
  'Job Code': '007704',
  'Salary Plan SETID': 'UCANR',
  'Union Code': 'TX'},
 'UCANR - TX - WRITER AST': {'Job Code Description': 'WRITER AST',
  'Job Code': '007705',
  'Salary Plan SETID': 'UCANR',
  'Union Code': 'TX'}}

In [36]:
manual_input_df = pd.DataFrame(manual_check_dict).T
manual_input_w_details_df = manual_input_df.merge(upte_represented_job_codes_df, on=['Salary Plan SETID', 'Union Code', 'Job Code'], how='left')
manual_input_w_details_df.to_excel("unmatched_steps_and_rates.xlsx", engine='openpyxl')
# manual_input_w_details_df.head(100)

Exception ignored in: <function ZipFile.__del__ at 0x7f106538d120>
Traceback (most recent call last):
  File "/usr/lib/python3.12/zipfile/__init__.py", line 1966, in __del__
    self.close()
  File "/usr/lib/python3.12/zipfile/__init__.py", line 1983, in close
    self.fp.seek(self.start_dir)
ValueError: seek of closed file